/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedOpIndexRouteImport } from './routes/_authenticated/op/index'
import { Route as AuthenticatedMonIndexRouteImport } from './routes/_authenticated/mon/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedOpSettingsRouteRouteImport } from './routes/_authenticated/op/settings/route'
import { Route as AuthenticatedOpPrintRouteRouteImport } from './routes/_authenticated/op/print/route'
import { Route as AuthenticatedMonSettingsRouteRouteImport } from './routes/_authenticated/mon/settings/route'
import { Route as AuthenticatedOpTransactionsIndexRouteImport } from './routes/_authenticated/op/transactions/index'
import { Route as AuthenticatedOpTasksIndexRouteImport } from './routes/_authenticated/op/tasks/index'
import { Route as AuthenticatedOpShipmentsIndexRouteImport } from './routes/_authenticated/op/shipments/index'
import { Route as AuthenticatedOpRefundsIndexRouteImport } from './routes/_authenticated/op/refunds/index'
import { Route as AuthenticatedOpProductsIndexRouteImport } from './routes/_authenticated/op/products/index'
import { Route as AuthenticatedOpPaymentsIndexRouteImport } from './routes/_authenticated/op/payments/index'
import { Route as AuthenticatedOpOrdersIndexRouteImport } from './routes/_authenticated/op/orders/index'
import { Route as AuthenticatedOpMediaIndexRouteImport } from './routes/_authenticated/op/media/index'
import { Route as AuthenticatedOpInventoryIndexRouteImport } from './routes/_authenticated/op/inventory/index'
import { Route as AuthenticatedOpHelpCenterIndexRouteImport } from './routes/_authenticated/op/help-center/index'
import { Route as AuthenticatedOpCustomersIndexRouteImport } from './routes/_authenticated/op/customers/index'
import { Route as AuthenticatedOpCouponsIndexRouteImport } from './routes/_authenticated/op/coupons/index'
import { Route as AuthenticatedOpCombosIndexRouteImport } from './routes/_authenticated/op/combos/index'
import { Route as AuthenticatedOpChatsIndexRouteImport } from './routes/_authenticated/op/chats/index'
import { Route as AuthenticatedOpCategoriesIndexRouteImport } from './routes/_authenticated/op/categories/index'
import { Route as AuthenticatedOpCampaignsIndexRouteImport } from './routes/_authenticated/op/campaigns/index'
import { Route as AuthenticatedOpAttributesIndexRouteImport } from './routes/_authenticated/op/attributes/index'
import { Route as AuthenticatedOpAppsIndexRouteImport } from './routes/_authenticated/op/apps/index'
import { Route as AuthenticatedMonUsersIndexRouteImport } from './routes/_authenticated/mon/users/index'
import { Route as AuthenticatedMonHelpCenterIndexRouteImport } from './routes/_authenticated/mon/help-center/index'
import { Route as AuthenticatedMonAnalyticsIndexRouteImport } from './routes/_authenticated/mon/analytics/index'
import { Route as AuthenticatedMonActivityLogsIndexRouteImport } from './routes/_authenticated/mon/activity-logs/index'
import { Route as AuthenticatedOpOrdersIdRouteImport } from './routes/_authenticated/op/orders/$id'
import { Route as AuthenticatedOpSettingsPersonalIndexRouteImport } from './routes/_authenticated/op/settings/personal/index'
import { Route as AuthenticatedOpPrintBulkIndexRouteImport } from './routes/_authenticated/op/print/bulk/index'
import { Route as AuthenticatedMonSettingsTrackingIndexRouteImport } from './routes/_authenticated/mon/settings/tracking/index'
import { Route as AuthenticatedMonSettingsSystemIndexRouteImport } from './routes/_authenticated/mon/settings/system/index'
import { Route as AuthenticatedMonSettingsStorefrontIndexRouteImport } from './routes/_authenticated/mon/settings/storefront/index'
import { Route as AuthenticatedMonSettingsStorageIndexRouteImport } from './routes/_authenticated/mon/settings/storage/index'
import { Route as AuthenticatedMonSettingsOrderStatusesIndexRouteImport } from './routes/_authenticated/mon/settings/order-statuses/index'
import { Route as AuthenticatedMonSettingsGatewaysIndexRouteImport } from './routes/_authenticated/mon/settings/gateways/index'
import { Route as AuthenticatedMonSettingsCourierIndexRouteImport } from './routes/_authenticated/mon/settings/courier/index'
import { Route as AuthenticatedOpPrintStickerIdRouteImport } from './routes/_authenticated/op/print/sticker/$id'
import { Route as AuthenticatedOpPrintInvoiceIdRouteImport } from './routes/_authenticated/op/print/invoice/$id'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOpIndexRoute = AuthenticatedOpIndexRouteImport.update({
  id: '/op/',
  path: '/op/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonIndexRoute = AuthenticatedMonIndexRouteImport.update({
  id: '/mon/',
  path: '/mon/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpSettingsRouteRoute =
  AuthenticatedOpSettingsRouteRouteImport.update({
    id: '/op/settings',
    path: '/op/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpPrintRouteRoute =
  AuthenticatedOpPrintRouteRouteImport.update({
    id: '/op/print',
    path: '/op/print',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonSettingsRouteRoute =
  AuthenticatedMonSettingsRouteRouteImport.update({
    id: '/mon/settings',
    path: '/mon/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpTransactionsIndexRoute =
  AuthenticatedOpTransactionsIndexRouteImport.update({
    id: '/op/transactions/',
    path: '/op/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpTasksIndexRoute =
  AuthenticatedOpTasksIndexRouteImport.update({
    id: '/op/tasks/',
    path: '/op/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpShipmentsIndexRoute =
  AuthenticatedOpShipmentsIndexRouteImport.update({
    id: '/op/shipments/',
    path: '/op/shipments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpRefundsIndexRoute =
  AuthenticatedOpRefundsIndexRouteImport.update({
    id: '/op/refunds/',
    path: '/op/refunds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpProductsIndexRoute =
  AuthenticatedOpProductsIndexRouteImport.update({
    id: '/op/products/',
    path: '/op/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpPaymentsIndexRoute =
  AuthenticatedOpPaymentsIndexRouteImport.update({
    id: '/op/payments/',
    path: '/op/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpOrdersIndexRoute =
  AuthenticatedOpOrdersIndexRouteImport.update({
    id: '/op/orders/',
    path: '/op/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpMediaIndexRoute =
  AuthenticatedOpMediaIndexRouteImport.update({
    id: '/op/media/',
    path: '/op/media/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpInventoryIndexRoute =
  AuthenticatedOpInventoryIndexRouteImport.update({
    id: '/op/inventory/',
    path: '/op/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpHelpCenterIndexRoute =
  AuthenticatedOpHelpCenterIndexRouteImport.update({
    id: '/op/help-center/',
    path: '/op/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCustomersIndexRoute =
  AuthenticatedOpCustomersIndexRouteImport.update({
    id: '/op/customers/',
    path: '/op/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCouponsIndexRoute =
  AuthenticatedOpCouponsIndexRouteImport.update({
    id: '/op/coupons/',
    path: '/op/coupons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCombosIndexRoute =
  AuthenticatedOpCombosIndexRouteImport.update({
    id: '/op/combos/',
    path: '/op/combos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpChatsIndexRoute =
  AuthenticatedOpChatsIndexRouteImport.update({
    id: '/op/chats/',
    path: '/op/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCategoriesIndexRoute =
  AuthenticatedOpCategoriesIndexRouteImport.update({
    id: '/op/categories/',
    path: '/op/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCampaignsIndexRoute =
  AuthenticatedOpCampaignsIndexRouteImport.update({
    id: '/op/campaigns/',
    path: '/op/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpAttributesIndexRoute =
  AuthenticatedOpAttributesIndexRouteImport.update({
    id: '/op/attributes/',
    path: '/op/attributes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpAppsIndexRoute =
  AuthenticatedOpAppsIndexRouteImport.update({
    id: '/op/apps/',
    path: '/op/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonUsersIndexRoute =
  AuthenticatedMonUsersIndexRouteImport.update({
    id: '/mon/users/',
    path: '/mon/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonHelpCenterIndexRoute =
  AuthenticatedMonHelpCenterIndexRouteImport.update({
    id: '/mon/help-center/',
    path: '/mon/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonAnalyticsIndexRoute =
  AuthenticatedMonAnalyticsIndexRouteImport.update({
    id: '/mon/analytics/',
    path: '/mon/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonActivityLogsIndexRoute =
  AuthenticatedMonActivityLogsIndexRouteImport.update({
    id: '/mon/activity-logs/',
    path: '/mon/activity-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpOrdersIdRoute = AuthenticatedOpOrdersIdRouteImport.update({
  id: '/op/orders/$id',
  path: '/op/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpSettingsPersonalIndexRoute =
  AuthenticatedOpSettingsPersonalIndexRouteImport.update({
    id: '/personal/',
    path: '/personal/',
    getParentRoute: () => AuthenticatedOpSettingsRouteRoute,
  } as any)
const AuthenticatedOpPrintBulkIndexRoute =
  AuthenticatedOpPrintBulkIndexRouteImport.update({
    id: '/bulk/',
    path: '/bulk/',
    getParentRoute: () => AuthenticatedOpPrintRouteRoute,
  } as any)
const AuthenticatedMonSettingsTrackingIndexRoute =
  AuthenticatedMonSettingsTrackingIndexRouteImport.update({
    id: '/tracking/',
    path: '/tracking/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsSystemIndexRoute =
  AuthenticatedMonSettingsSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsStorefrontIndexRoute =
  AuthenticatedMonSettingsStorefrontIndexRouteImport.update({
    id: '/storefront/',
    path: '/storefront/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsStorageIndexRoute =
  AuthenticatedMonSettingsStorageIndexRouteImport.update({
    id: '/storage/',
    path: '/storage/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsOrderStatusesIndexRoute =
  AuthenticatedMonSettingsOrderStatusesIndexRouteImport.update({
    id: '/order-statuses/',
    path: '/order-statuses/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsGatewaysIndexRoute =
  AuthenticatedMonSettingsGatewaysIndexRouteImport.update({
    id: '/gateways/',
    path: '/gateways/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsCourierIndexRoute =
  AuthenticatedMonSettingsCourierIndexRouteImport.update({
    id: '/courier/',
    path: '/courier/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedOpPrintStickerIdRoute =
  AuthenticatedOpPrintStickerIdRouteImport.update({
    id: '/sticker/$id',
    path: '/sticker/$id',
    getParentRoute: () => AuthenticatedOpPrintRouteRoute,
  } as any)
const AuthenticatedOpPrintInvoiceIdRoute =
  AuthenticatedOpPrintInvoiceIdRouteImport.update({
    id: '/invoice/$id',
    path: '/invoice/$id',
    getParentRoute: () => AuthenticatedOpPrintRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/mon/settings': typeof AuthenticatedMonSettingsRouteRouteWithChildren
  '/op/print': typeof AuthenticatedOpPrintRouteRouteWithChildren
  '/op/settings': typeof AuthenticatedOpSettingsRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/mon/': typeof AuthenticatedMonIndexRoute
  '/op/': typeof AuthenticatedOpIndexRoute
  '/op/orders/$id': typeof AuthenticatedOpOrdersIdRoute
  '/mon/activity-logs/': typeof AuthenticatedMonActivityLogsIndexRoute
  '/mon/analytics/': typeof AuthenticatedMonAnalyticsIndexRoute
  '/mon/help-center/': typeof AuthenticatedMonHelpCenterIndexRoute
  '/mon/users/': typeof AuthenticatedMonUsersIndexRoute
  '/op/apps/': typeof AuthenticatedOpAppsIndexRoute
  '/op/attributes/': typeof AuthenticatedOpAttributesIndexRoute
  '/op/campaigns/': typeof AuthenticatedOpCampaignsIndexRoute
  '/op/categories/': typeof AuthenticatedOpCategoriesIndexRoute
  '/op/chats/': typeof AuthenticatedOpChatsIndexRoute
  '/op/combos/': typeof AuthenticatedOpCombosIndexRoute
  '/op/coupons/': typeof AuthenticatedOpCouponsIndexRoute
  '/op/customers/': typeof AuthenticatedOpCustomersIndexRoute
  '/op/help-center/': typeof AuthenticatedOpHelpCenterIndexRoute
  '/op/inventory/': typeof AuthenticatedOpInventoryIndexRoute
  '/op/media/': typeof AuthenticatedOpMediaIndexRoute
  '/op/orders/': typeof AuthenticatedOpOrdersIndexRoute
  '/op/payments/': typeof AuthenticatedOpPaymentsIndexRoute
  '/op/products/': typeof AuthenticatedOpProductsIndexRoute
  '/op/refunds/': typeof AuthenticatedOpRefundsIndexRoute
  '/op/shipments/': typeof AuthenticatedOpShipmentsIndexRoute
  '/op/tasks/': typeof AuthenticatedOpTasksIndexRoute
  '/op/transactions/': typeof AuthenticatedOpTransactionsIndexRoute
  '/op/print/invoice/$id': typeof AuthenticatedOpPrintInvoiceIdRoute
  '/op/print/sticker/$id': typeof AuthenticatedOpPrintStickerIdRoute
  '/mon/settings/courier/': typeof AuthenticatedMonSettingsCourierIndexRoute
  '/mon/settings/gateways/': typeof AuthenticatedMonSettingsGatewaysIndexRoute
  '/mon/settings/order-statuses/': typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  '/mon/settings/storage/': typeof AuthenticatedMonSettingsStorageIndexRoute
  '/mon/settings/storefront/': typeof AuthenticatedMonSettingsStorefrontIndexRoute
  '/mon/settings/system/': typeof AuthenticatedMonSettingsSystemIndexRoute
  '/mon/settings/tracking/': typeof AuthenticatedMonSettingsTrackingIndexRoute
  '/op/print/bulk/': typeof AuthenticatedOpPrintBulkIndexRoute
  '/op/settings/personal/': typeof AuthenticatedOpSettingsPersonalIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/mon/settings': typeof AuthenticatedMonSettingsRouteRouteWithChildren
  '/op/print': typeof AuthenticatedOpPrintRouteRouteWithChildren
  '/op/settings': typeof AuthenticatedOpSettingsRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/mon': typeof AuthenticatedMonIndexRoute
  '/op': typeof AuthenticatedOpIndexRoute
  '/op/orders/$id': typeof AuthenticatedOpOrdersIdRoute
  '/mon/activity-logs': typeof AuthenticatedMonActivityLogsIndexRoute
  '/mon/analytics': typeof AuthenticatedMonAnalyticsIndexRoute
  '/mon/help-center': typeof AuthenticatedMonHelpCenterIndexRoute
  '/mon/users': typeof AuthenticatedMonUsersIndexRoute
  '/op/apps': typeof AuthenticatedOpAppsIndexRoute
  '/op/attributes': typeof AuthenticatedOpAttributesIndexRoute
  '/op/campaigns': typeof AuthenticatedOpCampaignsIndexRoute
  '/op/categories': typeof AuthenticatedOpCategoriesIndexRoute
  '/op/chats': typeof AuthenticatedOpChatsIndexRoute
  '/op/combos': typeof AuthenticatedOpCombosIndexRoute
  '/op/coupons': typeof AuthenticatedOpCouponsIndexRoute
  '/op/customers': typeof AuthenticatedOpCustomersIndexRoute
  '/op/help-center': typeof AuthenticatedOpHelpCenterIndexRoute
  '/op/inventory': typeof AuthenticatedOpInventoryIndexRoute
  '/op/media': typeof AuthenticatedOpMediaIndexRoute
  '/op/orders': typeof AuthenticatedOpOrdersIndexRoute
  '/op/payments': typeof AuthenticatedOpPaymentsIndexRoute
  '/op/products': typeof AuthenticatedOpProductsIndexRoute
  '/op/refunds': typeof AuthenticatedOpRefundsIndexRoute
  '/op/shipments': typeof AuthenticatedOpShipmentsIndexRoute
  '/op/tasks': typeof AuthenticatedOpTasksIndexRoute
  '/op/transactions': typeof AuthenticatedOpTransactionsIndexRoute
  '/op/print/invoice/$id': typeof AuthenticatedOpPrintInvoiceIdRoute
  '/op/print/sticker/$id': typeof AuthenticatedOpPrintStickerIdRoute
  '/mon/settings/courier': typeof AuthenticatedMonSettingsCourierIndexRoute
  '/mon/settings/gateways': typeof AuthenticatedMonSettingsGatewaysIndexRoute
  '/mon/settings/order-statuses': typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  '/mon/settings/storage': typeof AuthenticatedMonSettingsStorageIndexRoute
  '/mon/settings/storefront': typeof AuthenticatedMonSettingsStorefrontIndexRoute
  '/mon/settings/system': typeof AuthenticatedMonSettingsSystemIndexRoute
  '/mon/settings/tracking': typeof AuthenticatedMonSettingsTrackingIndexRoute
  '/op/print/bulk': typeof AuthenticatedOpPrintBulkIndexRoute
  '/op/settings/personal': typeof AuthenticatedOpSettingsPersonalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/mon/settings': typeof AuthenticatedMonSettingsRouteRouteWithChildren
  '/_authenticated/op/print': typeof AuthenticatedOpPrintRouteRouteWithChildren
  '/_authenticated/op/settings': typeof AuthenticatedOpSettingsRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/mon/': typeof AuthenticatedMonIndexRoute
  '/_authenticated/op/': typeof AuthenticatedOpIndexRoute
  '/_authenticated/op/orders/$id': typeof AuthenticatedOpOrdersIdRoute
  '/_authenticated/mon/activity-logs/': typeof AuthenticatedMonActivityLogsIndexRoute
  '/_authenticated/mon/analytics/': typeof AuthenticatedMonAnalyticsIndexRoute
  '/_authenticated/mon/help-center/': typeof AuthenticatedMonHelpCenterIndexRoute
  '/_authenticated/mon/users/': typeof AuthenticatedMonUsersIndexRoute
  '/_authenticated/op/apps/': typeof AuthenticatedOpAppsIndexRoute
  '/_authenticated/op/attributes/': typeof AuthenticatedOpAttributesIndexRoute
  '/_authenticated/op/campaigns/': typeof AuthenticatedOpCampaignsIndexRoute
  '/_authenticated/op/categories/': typeof AuthenticatedOpCategoriesIndexRoute
  '/_authenticated/op/chats/': typeof AuthenticatedOpChatsIndexRoute
  '/_authenticated/op/combos/': typeof AuthenticatedOpCombosIndexRoute
  '/_authenticated/op/coupons/': typeof AuthenticatedOpCouponsIndexRoute
  '/_authenticated/op/customers/': typeof AuthenticatedOpCustomersIndexRoute
  '/_authenticated/op/help-center/': typeof AuthenticatedOpHelpCenterIndexRoute
  '/_authenticated/op/inventory/': typeof AuthenticatedOpInventoryIndexRoute
  '/_authenticated/op/media/': typeof AuthenticatedOpMediaIndexRoute
  '/_authenticated/op/orders/': typeof AuthenticatedOpOrdersIndexRoute
  '/_authenticated/op/payments/': typeof AuthenticatedOpPaymentsIndexRoute
  '/_authenticated/op/products/': typeof AuthenticatedOpProductsIndexRoute
  '/_authenticated/op/refunds/': typeof AuthenticatedOpRefundsIndexRoute
  '/_authenticated/op/shipments/': typeof AuthenticatedOpShipmentsIndexRoute
  '/_authenticated/op/tasks/': typeof AuthenticatedOpTasksIndexRoute
  '/_authenticated/op/transactions/': typeof AuthenticatedOpTransactionsIndexRoute
  '/_authenticated/op/print/invoice/$id': typeof AuthenticatedOpPrintInvoiceIdRoute
  '/_authenticated/op/print/sticker/$id': typeof AuthenticatedOpPrintStickerIdRoute
  '/_authenticated/mon/settings/courier/': typeof AuthenticatedMonSettingsCourierIndexRoute
  '/_authenticated/mon/settings/gateways/': typeof AuthenticatedMonSettingsGatewaysIndexRoute
  '/_authenticated/mon/settings/order-statuses/': typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  '/_authenticated/mon/settings/storage/': typeof AuthenticatedMonSettingsStorageIndexRoute
  '/_authenticated/mon/settings/storefront/': typeof AuthenticatedMonSettingsStorefrontIndexRoute
  '/_authenticated/mon/settings/system/': typeof AuthenticatedMonSettingsSystemIndexRoute
  '/_authenticated/mon/settings/tracking/': typeof AuthenticatedMonSettingsTrackingIndexRoute
  '/_authenticated/op/print/bulk/': typeof AuthenticatedOpPrintBulkIndexRoute
  '/_authenticated/op/settings/personal/': typeof AuthenticatedOpSettingsPersonalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/mon/settings'
    | '/op/print'
    | '/op/settings'
    | '/errors/$error'
    | '/mon/'
    | '/op/'
    | '/op/orders/$id'
    | '/mon/activity-logs/'
    | '/mon/analytics/'
    | '/mon/help-center/'
    | '/mon/users/'
    | '/op/apps/'
    | '/op/attributes/'
    | '/op/campaigns/'
    | '/op/categories/'
    | '/op/chats/'
    | '/op/combos/'
    | '/op/coupons/'
    | '/op/customers/'
    | '/op/help-center/'
    | '/op/inventory/'
    | '/op/media/'
    | '/op/orders/'
    | '/op/payments/'
    | '/op/products/'
    | '/op/refunds/'
    | '/op/shipments/'
    | '/op/tasks/'
    | '/op/transactions/'
    | '/op/print/invoice/$id'
    | '/op/print/sticker/$id'
    | '/mon/settings/courier/'
    | '/mon/settings/gateways/'
    | '/mon/settings/order-statuses/'
    | '/mon/settings/storage/'
    | '/mon/settings/storefront/'
    | '/mon/settings/system/'
    | '/mon/settings/tracking/'
    | '/op/print/bulk/'
    | '/op/settings/personal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/mon/settings'
    | '/op/print'
    | '/op/settings'
    | '/errors/$error'
    | '/mon'
    | '/op'
    | '/op/orders/$id'
    | '/mon/activity-logs'
    | '/mon/analytics'
    | '/mon/help-center'
    | '/mon/users'
    | '/op/apps'
    | '/op/attributes'
    | '/op/campaigns'
    | '/op/categories'
    | '/op/chats'
    | '/op/combos'
    | '/op/coupons'
    | '/op/customers'
    | '/op/help-center'
    | '/op/inventory'
    | '/op/media'
    | '/op/orders'
    | '/op/payments'
    | '/op/products'
    | '/op/refunds'
    | '/op/shipments'
    | '/op/tasks'
    | '/op/transactions'
    | '/op/print/invoice/$id'
    | '/op/print/sticker/$id'
    | '/mon/settings/courier'
    | '/mon/settings/gateways'
    | '/mon/settings/order-statuses'
    | '/mon/settings/storage'
    | '/mon/settings/storefront'
    | '/mon/settings/system'
    | '/mon/settings/tracking'
    | '/op/print/bulk'
    | '/op/settings/personal'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/mon/settings'
    | '/_authenticated/op/print'
    | '/_authenticated/op/settings'
    | '/_authenticated/errors/$error'
    | '/_authenticated/mon/'
    | '/_authenticated/op/'
    | '/_authenticated/op/orders/$id'
    | '/_authenticated/mon/activity-logs/'
    | '/_authenticated/mon/analytics/'
    | '/_authenticated/mon/help-center/'
    | '/_authenticated/mon/users/'
    | '/_authenticated/op/apps/'
    | '/_authenticated/op/attributes/'
    | '/_authenticated/op/campaigns/'
    | '/_authenticated/op/categories/'
    | '/_authenticated/op/chats/'
    | '/_authenticated/op/combos/'
    | '/_authenticated/op/coupons/'
    | '/_authenticated/op/customers/'
    | '/_authenticated/op/help-center/'
    | '/_authenticated/op/inventory/'
    | '/_authenticated/op/media/'
    | '/_authenticated/op/orders/'
    | '/_authenticated/op/payments/'
    | '/_authenticated/op/products/'
    | '/_authenticated/op/refunds/'
    | '/_authenticated/op/shipments/'
    | '/_authenticated/op/tasks/'
    | '/_authenticated/op/transactions/'
    | '/_authenticated/op/print/invoice/$id'
    | '/_authenticated/op/print/sticker/$id'
    | '/_authenticated/mon/settings/courier/'
    | '/_authenticated/mon/settings/gateways/'
    | '/_authenticated/mon/settings/order-statuses/'
    | '/_authenticated/mon/settings/storage/'
    | '/_authenticated/mon/settings/storefront/'
    | '/_authenticated/mon/settings/system/'
    | '/_authenticated/mon/settings/tracking/'
    | '/_authenticated/op/print/bulk/'
    | '/_authenticated/op/settings/personal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/op/': {
      id: '/_authenticated/op/'
      path: '/op'
      fullPath: '/op/'
      preLoaderRoute: typeof AuthenticatedOpIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/': {
      id: '/_authenticated/mon/'
      path: '/mon'
      fullPath: '/mon/'
      preLoaderRoute: typeof AuthenticatedMonIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/settings': {
      id: '/_authenticated/op/settings'
      path: '/op/settings'
      fullPath: '/op/settings'
      preLoaderRoute: typeof AuthenticatedOpSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/print': {
      id: '/_authenticated/op/print'
      path: '/op/print'
      fullPath: '/op/print'
      preLoaderRoute: typeof AuthenticatedOpPrintRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/settings': {
      id: '/_authenticated/mon/settings'
      path: '/mon/settings'
      fullPath: '/mon/settings'
      preLoaderRoute: typeof AuthenticatedMonSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/transactions/': {
      id: '/_authenticated/op/transactions/'
      path: '/op/transactions'
      fullPath: '/op/transactions/'
      preLoaderRoute: typeof AuthenticatedOpTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/tasks/': {
      id: '/_authenticated/op/tasks/'
      path: '/op/tasks'
      fullPath: '/op/tasks/'
      preLoaderRoute: typeof AuthenticatedOpTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/shipments/': {
      id: '/_authenticated/op/shipments/'
      path: '/op/shipments'
      fullPath: '/op/shipments/'
      preLoaderRoute: typeof AuthenticatedOpShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/refunds/': {
      id: '/_authenticated/op/refunds/'
      path: '/op/refunds'
      fullPath: '/op/refunds/'
      preLoaderRoute: typeof AuthenticatedOpRefundsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/products/': {
      id: '/_authenticated/op/products/'
      path: '/op/products'
      fullPath: '/op/products/'
      preLoaderRoute: typeof AuthenticatedOpProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/payments/': {
      id: '/_authenticated/op/payments/'
      path: '/op/payments'
      fullPath: '/op/payments/'
      preLoaderRoute: typeof AuthenticatedOpPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/orders/': {
      id: '/_authenticated/op/orders/'
      path: '/op/orders'
      fullPath: '/op/orders/'
      preLoaderRoute: typeof AuthenticatedOpOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/media/': {
      id: '/_authenticated/op/media/'
      path: '/op/media'
      fullPath: '/op/media/'
      preLoaderRoute: typeof AuthenticatedOpMediaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/inventory/': {
      id: '/_authenticated/op/inventory/'
      path: '/op/inventory'
      fullPath: '/op/inventory/'
      preLoaderRoute: typeof AuthenticatedOpInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/help-center/': {
      id: '/_authenticated/op/help-center/'
      path: '/op/help-center'
      fullPath: '/op/help-center/'
      preLoaderRoute: typeof AuthenticatedOpHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/customers/': {
      id: '/_authenticated/op/customers/'
      path: '/op/customers'
      fullPath: '/op/customers/'
      preLoaderRoute: typeof AuthenticatedOpCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/coupons/': {
      id: '/_authenticated/op/coupons/'
      path: '/op/coupons'
      fullPath: '/op/coupons/'
      preLoaderRoute: typeof AuthenticatedOpCouponsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/combos/': {
      id: '/_authenticated/op/combos/'
      path: '/op/combos'
      fullPath: '/op/combos/'
      preLoaderRoute: typeof AuthenticatedOpCombosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/chats/': {
      id: '/_authenticated/op/chats/'
      path: '/op/chats'
      fullPath: '/op/chats/'
      preLoaderRoute: typeof AuthenticatedOpChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/categories/': {
      id: '/_authenticated/op/categories/'
      path: '/op/categories'
      fullPath: '/op/categories/'
      preLoaderRoute: typeof AuthenticatedOpCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/campaigns/': {
      id: '/_authenticated/op/campaigns/'
      path: '/op/campaigns'
      fullPath: '/op/campaigns/'
      preLoaderRoute: typeof AuthenticatedOpCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/attributes/': {
      id: '/_authenticated/op/attributes/'
      path: '/op/attributes'
      fullPath: '/op/attributes/'
      preLoaderRoute: typeof AuthenticatedOpAttributesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/apps/': {
      id: '/_authenticated/op/apps/'
      path: '/op/apps'
      fullPath: '/op/apps/'
      preLoaderRoute: typeof AuthenticatedOpAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/users/': {
      id: '/_authenticated/mon/users/'
      path: '/mon/users'
      fullPath: '/mon/users/'
      preLoaderRoute: typeof AuthenticatedMonUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/help-center/': {
      id: '/_authenticated/mon/help-center/'
      path: '/mon/help-center'
      fullPath: '/mon/help-center/'
      preLoaderRoute: typeof AuthenticatedMonHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/analytics/': {
      id: '/_authenticated/mon/analytics/'
      path: '/mon/analytics'
      fullPath: '/mon/analytics/'
      preLoaderRoute: typeof AuthenticatedMonAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/activity-logs/': {
      id: '/_authenticated/mon/activity-logs/'
      path: '/mon/activity-logs'
      fullPath: '/mon/activity-logs/'
      preLoaderRoute: typeof AuthenticatedMonActivityLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/orders/$id': {
      id: '/_authenticated/op/orders/$id'
      path: '/op/orders/$id'
      fullPath: '/op/orders/$id'
      preLoaderRoute: typeof AuthenticatedOpOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/settings/personal/': {
      id: '/_authenticated/op/settings/personal/'
      path: '/personal'
      fullPath: '/op/settings/personal/'
      preLoaderRoute: typeof AuthenticatedOpSettingsPersonalIndexRouteImport
      parentRoute: typeof AuthenticatedOpSettingsRouteRoute
    }
    '/_authenticated/op/print/bulk/': {
      id: '/_authenticated/op/print/bulk/'
      path: '/bulk'
      fullPath: '/op/print/bulk/'
      preLoaderRoute: typeof AuthenticatedOpPrintBulkIndexRouteImport
      parentRoute: typeof AuthenticatedOpPrintRouteRoute
    }
    '/_authenticated/mon/settings/tracking/': {
      id: '/_authenticated/mon/settings/tracking/'
      path: '/tracking'
      fullPath: '/mon/settings/tracking/'
      preLoaderRoute: typeof AuthenticatedMonSettingsTrackingIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/system/': {
      id: '/_authenticated/mon/settings/system/'
      path: '/system'
      fullPath: '/mon/settings/system/'
      preLoaderRoute: typeof AuthenticatedMonSettingsSystemIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/storefront/': {
      id: '/_authenticated/mon/settings/storefront/'
      path: '/storefront'
      fullPath: '/mon/settings/storefront/'
      preLoaderRoute: typeof AuthenticatedMonSettingsStorefrontIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/storage/': {
      id: '/_authenticated/mon/settings/storage/'
      path: '/storage'
      fullPath: '/mon/settings/storage/'
      preLoaderRoute: typeof AuthenticatedMonSettingsStorageIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/order-statuses/': {
      id: '/_authenticated/mon/settings/order-statuses/'
      path: '/order-statuses'
      fullPath: '/mon/settings/order-statuses/'
      preLoaderRoute: typeof AuthenticatedMonSettingsOrderStatusesIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/gateways/': {
      id: '/_authenticated/mon/settings/gateways/'
      path: '/gateways'
      fullPath: '/mon/settings/gateways/'
      preLoaderRoute: typeof AuthenticatedMonSettingsGatewaysIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/courier/': {
      id: '/_authenticated/mon/settings/courier/'
      path: '/courier'
      fullPath: '/mon/settings/courier/'
      preLoaderRoute: typeof AuthenticatedMonSettingsCourierIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/op/print/sticker/$id': {
      id: '/_authenticated/op/print/sticker/$id'
      path: '/sticker/$id'
      fullPath: '/op/print/sticker/$id'
      preLoaderRoute: typeof AuthenticatedOpPrintStickerIdRouteImport
      parentRoute: typeof AuthenticatedOpPrintRouteRoute
    }
    '/_authenticated/op/print/invoice/$id': {
      id: '/_authenticated/op/print/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/op/print/invoice/$id'
      preLoaderRoute: typeof AuthenticatedOpPrintInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedOpPrintRouteRoute
    }
  }
}

interface AuthenticatedMonSettingsRouteRouteChildren {
  AuthenticatedMonSettingsCourierIndexRoute: typeof AuthenticatedMonSettingsCourierIndexRoute
  AuthenticatedMonSettingsGatewaysIndexRoute: typeof AuthenticatedMonSettingsGatewaysIndexRoute
  AuthenticatedMonSettingsOrderStatusesIndexRoute: typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  AuthenticatedMonSettingsStorageIndexRoute: typeof AuthenticatedMonSettingsStorageIndexRoute
  AuthenticatedMonSettingsStorefrontIndexRoute: typeof AuthenticatedMonSettingsStorefrontIndexRoute
  AuthenticatedMonSettingsSystemIndexRoute: typeof AuthenticatedMonSettingsSystemIndexRoute
  AuthenticatedMonSettingsTrackingIndexRoute: typeof AuthenticatedMonSettingsTrackingIndexRoute
}

const AuthenticatedMonSettingsRouteRouteChildren: AuthenticatedMonSettingsRouteRouteChildren =
  {
    AuthenticatedMonSettingsCourierIndexRoute:
      AuthenticatedMonSettingsCourierIndexRoute,
    AuthenticatedMonSettingsGatewaysIndexRoute:
      AuthenticatedMonSettingsGatewaysIndexRoute,
    AuthenticatedMonSettingsOrderStatusesIndexRoute:
      AuthenticatedMonSettingsOrderStatusesIndexRoute,
    AuthenticatedMonSettingsStorageIndexRoute:
      AuthenticatedMonSettingsStorageIndexRoute,
    AuthenticatedMonSettingsStorefrontIndexRoute:
      AuthenticatedMonSettingsStorefrontIndexRoute,
    AuthenticatedMonSettingsSystemIndexRoute:
      AuthenticatedMonSettingsSystemIndexRoute,
    AuthenticatedMonSettingsTrackingIndexRoute:
      AuthenticatedMonSettingsTrackingIndexRoute,
  }

const AuthenticatedMonSettingsRouteRouteWithChildren =
  AuthenticatedMonSettingsRouteRoute._addFileChildren(
    AuthenticatedMonSettingsRouteRouteChildren,
  )

interface AuthenticatedOpPrintRouteRouteChildren {
  AuthenticatedOpPrintInvoiceIdRoute: typeof AuthenticatedOpPrintInvoiceIdRoute
  AuthenticatedOpPrintStickerIdRoute: typeof AuthenticatedOpPrintStickerIdRoute
  AuthenticatedOpPrintBulkIndexRoute: typeof AuthenticatedOpPrintBulkIndexRoute
}

const AuthenticatedOpPrintRouteRouteChildren: AuthenticatedOpPrintRouteRouteChildren =
  {
    AuthenticatedOpPrintInvoiceIdRoute: AuthenticatedOpPrintInvoiceIdRoute,
    AuthenticatedOpPrintStickerIdRoute: AuthenticatedOpPrintStickerIdRoute,
    AuthenticatedOpPrintBulkIndexRoute: AuthenticatedOpPrintBulkIndexRoute,
  }

const AuthenticatedOpPrintRouteRouteWithChildren =
  AuthenticatedOpPrintRouteRoute._addFileChildren(
    AuthenticatedOpPrintRouteRouteChildren,
  )

interface AuthenticatedOpSettingsRouteRouteChildren {
  AuthenticatedOpSettingsPersonalIndexRoute: typeof AuthenticatedOpSettingsPersonalIndexRoute
}

const AuthenticatedOpSettingsRouteRouteChildren: AuthenticatedOpSettingsRouteRouteChildren =
  {
    AuthenticatedOpSettingsPersonalIndexRoute:
      AuthenticatedOpSettingsPersonalIndexRoute,
  }

const AuthenticatedOpSettingsRouteRouteWithChildren =
  AuthenticatedOpSettingsRouteRoute._addFileChildren(
    AuthenticatedOpSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMonSettingsRouteRoute: typeof AuthenticatedMonSettingsRouteRouteWithChildren
  AuthenticatedOpPrintRouteRoute: typeof AuthenticatedOpPrintRouteRouteWithChildren
  AuthenticatedOpSettingsRouteRoute: typeof AuthenticatedOpSettingsRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedMonIndexRoute: typeof AuthenticatedMonIndexRoute
  AuthenticatedOpIndexRoute: typeof AuthenticatedOpIndexRoute
  AuthenticatedOpOrdersIdRoute: typeof AuthenticatedOpOrdersIdRoute
  AuthenticatedMonActivityLogsIndexRoute: typeof AuthenticatedMonActivityLogsIndexRoute
  AuthenticatedMonAnalyticsIndexRoute: typeof AuthenticatedMonAnalyticsIndexRoute
  AuthenticatedMonHelpCenterIndexRoute: typeof AuthenticatedMonHelpCenterIndexRoute
  AuthenticatedMonUsersIndexRoute: typeof AuthenticatedMonUsersIndexRoute
  AuthenticatedOpAppsIndexRoute: typeof AuthenticatedOpAppsIndexRoute
  AuthenticatedOpAttributesIndexRoute: typeof AuthenticatedOpAttributesIndexRoute
  AuthenticatedOpCampaignsIndexRoute: typeof AuthenticatedOpCampaignsIndexRoute
  AuthenticatedOpCategoriesIndexRoute: typeof AuthenticatedOpCategoriesIndexRoute
  AuthenticatedOpChatsIndexRoute: typeof AuthenticatedOpChatsIndexRoute
  AuthenticatedOpCombosIndexRoute: typeof AuthenticatedOpCombosIndexRoute
  AuthenticatedOpCouponsIndexRoute: typeof AuthenticatedOpCouponsIndexRoute
  AuthenticatedOpCustomersIndexRoute: typeof AuthenticatedOpCustomersIndexRoute
  AuthenticatedOpHelpCenterIndexRoute: typeof AuthenticatedOpHelpCenterIndexRoute
  AuthenticatedOpInventoryIndexRoute: typeof AuthenticatedOpInventoryIndexRoute
  AuthenticatedOpMediaIndexRoute: typeof AuthenticatedOpMediaIndexRoute
  AuthenticatedOpOrdersIndexRoute: typeof AuthenticatedOpOrdersIndexRoute
  AuthenticatedOpPaymentsIndexRoute: typeof AuthenticatedOpPaymentsIndexRoute
  AuthenticatedOpProductsIndexRoute: typeof AuthenticatedOpProductsIndexRoute
  AuthenticatedOpRefundsIndexRoute: typeof AuthenticatedOpRefundsIndexRoute
  AuthenticatedOpShipmentsIndexRoute: typeof AuthenticatedOpShipmentsIndexRoute
  AuthenticatedOpTasksIndexRoute: typeof AuthenticatedOpTasksIndexRoute
  AuthenticatedOpTransactionsIndexRoute: typeof AuthenticatedOpTransactionsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMonSettingsRouteRoute:
    AuthenticatedMonSettingsRouteRouteWithChildren,
  AuthenticatedOpPrintRouteRoute: AuthenticatedOpPrintRouteRouteWithChildren,
  AuthenticatedOpSettingsRouteRoute:
    AuthenticatedOpSettingsRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedMonIndexRoute: AuthenticatedMonIndexRoute,
  AuthenticatedOpIndexRoute: AuthenticatedOpIndexRoute,
  AuthenticatedOpOrdersIdRoute: AuthenticatedOpOrdersIdRoute,
  AuthenticatedMonActivityLogsIndexRoute:
    AuthenticatedMonActivityLogsIndexRoute,
  AuthenticatedMonAnalyticsIndexRoute: AuthenticatedMonAnalyticsIndexRoute,
  AuthenticatedMonHelpCenterIndexRoute: AuthenticatedMonHelpCenterIndexRoute,
  AuthenticatedMonUsersIndexRoute: AuthenticatedMonUsersIndexRoute,
  AuthenticatedOpAppsIndexRoute: AuthenticatedOpAppsIndexRoute,
  AuthenticatedOpAttributesIndexRoute: AuthenticatedOpAttributesIndexRoute,
  AuthenticatedOpCampaignsIndexRoute: AuthenticatedOpCampaignsIndexRoute,
  AuthenticatedOpCategoriesIndexRoute: AuthenticatedOpCategoriesIndexRoute,
  AuthenticatedOpChatsIndexRoute: AuthenticatedOpChatsIndexRoute,
  AuthenticatedOpCombosIndexRoute: AuthenticatedOpCombosIndexRoute,
  AuthenticatedOpCouponsIndexRoute: AuthenticatedOpCouponsIndexRoute,
  AuthenticatedOpCustomersIndexRoute: AuthenticatedOpCustomersIndexRoute,
  AuthenticatedOpHelpCenterIndexRoute: AuthenticatedOpHelpCenterIndexRoute,
  AuthenticatedOpInventoryIndexRoute: AuthenticatedOpInventoryIndexRoute,
  AuthenticatedOpMediaIndexRoute: AuthenticatedOpMediaIndexRoute,
  AuthenticatedOpOrdersIndexRoute: AuthenticatedOpOrdersIndexRoute,
  AuthenticatedOpPaymentsIndexRoute: AuthenticatedOpPaymentsIndexRoute,
  AuthenticatedOpProductsIndexRoute: AuthenticatedOpProductsIndexRoute,
  AuthenticatedOpRefundsIndexRoute: AuthenticatedOpRefundsIndexRoute,
  AuthenticatedOpShipmentsIndexRoute: AuthenticatedOpShipmentsIndexRoute,
  AuthenticatedOpTasksIndexRoute: AuthenticatedOpTasksIndexRoute,
  AuthenticatedOpTransactionsIndexRoute: AuthenticatedOpTransactionsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
