/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedOpIndexRouteImport } from './routes/_authenticated/op/index'
import { Route as AuthenticatedMonIndexRouteImport } from './routes/_authenticated/mon/index'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedMonSettingsRouteRouteImport } from './routes/_authenticated/mon/settings/route'
import { Route as AuthenticatedOpTasksIndexRouteImport } from './routes/_authenticated/op/tasks/index'
import { Route as AuthenticatedOpProductsIndexRouteImport } from './routes/_authenticated/op/products/index'
import { Route as AuthenticatedOpPaymentsIndexRouteImport } from './routes/_authenticated/op/payments/index'
import { Route as AuthenticatedOpOrdersIndexRouteImport } from './routes/_authenticated/op/orders/index'
import { Route as AuthenticatedOpMediaIndexRouteImport } from './routes/_authenticated/op/media/index'
import { Route as AuthenticatedOpCustomersIndexRouteImport } from './routes/_authenticated/op/customers/index'
import { Route as AuthenticatedOpChatsIndexRouteImport } from './routes/_authenticated/op/chats/index'
import { Route as AuthenticatedOpCategoriesIndexRouteImport } from './routes/_authenticated/op/categories/index'
import { Route as AuthenticatedOpAttributesIndexRouteImport } from './routes/_authenticated/op/attributes/index'
import { Route as AuthenticatedOpAppsIndexRouteImport } from './routes/_authenticated/op/apps/index'
import { Route as AuthenticatedMonUsersIndexRouteImport } from './routes/_authenticated/mon/users/index'
import { Route as AuthenticatedMonShipmentsIndexRouteImport } from './routes/_authenticated/mon/shipments/index'
import { Route as AuthenticatedMonSettingsIndexRouteImport } from './routes/_authenticated/mon/settings/index'
import { Route as AuthenticatedMonRefundsIndexRouteImport } from './routes/_authenticated/mon/refunds/index'
import { Route as AuthenticatedMonInventoryIndexRouteImport } from './routes/_authenticated/mon/inventory/index'
import { Route as AuthenticatedMonHelpCenterIndexRouteImport } from './routes/_authenticated/mon/help-center/index'
import { Route as AuthenticatedMonCouponsIndexRouteImport } from './routes/_authenticated/mon/coupons/index'
import { Route as AuthenticatedMonSettingsNotificationsRouteImport } from './routes/_authenticated/mon/settings/notifications'
import { Route as AuthenticatedMonSettingsDisplayRouteImport } from './routes/_authenticated/mon/settings/display'
import { Route as AuthenticatedMonSettingsAppearanceRouteImport } from './routes/_authenticated/mon/settings/appearance'
import { Route as AuthenticatedMonSettingsAccountRouteImport } from './routes/_authenticated/mon/settings/account'
import { Route as AuthenticatedMonSettingsSystemIndexRouteImport } from './routes/_authenticated/mon/settings/system/index'
import { Route as AuthenticatedMonSettingsStorageIndexRouteImport } from './routes/_authenticated/mon/settings/storage/index'
import { Route as AuthenticatedMonSettingsPersonalIndexRouteImport } from './routes/_authenticated/mon/settings/personal/index'
import { Route as AuthenticatedMonSettingsOrderStatusesIndexRouteImport } from './routes/_authenticated/mon/settings/order-statuses/index'
import { Route as AuthenticatedMonSettingsGatewaysIndexRouteImport } from './routes/_authenticated/mon/settings/gateways/index'
import { Route as AuthenticatedMonSettingsCourierIndexRouteImport } from './routes/_authenticated/mon/settings/courier/index'
import { Route as AuthenticatedMonSettingsSystemStorageIndexRouteImport } from './routes/_authenticated/mon/settings/system/storage/index'
import { Route as AuthenticatedMonSettingsSystemOrderStatusesIndexRouteImport } from './routes/_authenticated/mon/settings/system/order-statuses/index'
import { Route as AuthenticatedMonSettingsSystemGatewaysIndexRouteImport } from './routes/_authenticated/mon/settings/system/gateways/index'
import { Route as AuthenticatedMonSettingsSystemCourierIndexRouteImport } from './routes/_authenticated/mon/settings/system/courier/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOpIndexRoute = AuthenticatedOpIndexRouteImport.update({
  id: '/op/',
  path: '/op/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonIndexRoute = AuthenticatedMonIndexRouteImport.update({
  id: '/mon/',
  path: '/mon/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonSettingsRouteRoute =
  AuthenticatedMonSettingsRouteRouteImport.update({
    id: '/mon/settings',
    path: '/mon/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpTasksIndexRoute =
  AuthenticatedOpTasksIndexRouteImport.update({
    id: '/op/tasks/',
    path: '/op/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpProductsIndexRoute =
  AuthenticatedOpProductsIndexRouteImport.update({
    id: '/op/products/',
    path: '/op/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpPaymentsIndexRoute =
  AuthenticatedOpPaymentsIndexRouteImport.update({
    id: '/op/payments/',
    path: '/op/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpOrdersIndexRoute =
  AuthenticatedOpOrdersIndexRouteImport.update({
    id: '/op/orders/',
    path: '/op/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpMediaIndexRoute =
  AuthenticatedOpMediaIndexRouteImport.update({
    id: '/op/media/',
    path: '/op/media/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCustomersIndexRoute =
  AuthenticatedOpCustomersIndexRouteImport.update({
    id: '/op/customers/',
    path: '/op/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpChatsIndexRoute =
  AuthenticatedOpChatsIndexRouteImport.update({
    id: '/op/chats/',
    path: '/op/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCategoriesIndexRoute =
  AuthenticatedOpCategoriesIndexRouteImport.update({
    id: '/op/categories/',
    path: '/op/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpAttributesIndexRoute =
  AuthenticatedOpAttributesIndexRouteImport.update({
    id: '/op/attributes/',
    path: '/op/attributes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpAppsIndexRoute =
  AuthenticatedOpAppsIndexRouteImport.update({
    id: '/op/apps/',
    path: '/op/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonUsersIndexRoute =
  AuthenticatedMonUsersIndexRouteImport.update({
    id: '/mon/users/',
    path: '/mon/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonShipmentsIndexRoute =
  AuthenticatedMonShipmentsIndexRouteImport.update({
    id: '/mon/shipments/',
    path: '/mon/shipments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonSettingsIndexRoute =
  AuthenticatedMonSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonRefundsIndexRoute =
  AuthenticatedMonRefundsIndexRouteImport.update({
    id: '/mon/refunds/',
    path: '/mon/refunds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonInventoryIndexRoute =
  AuthenticatedMonInventoryIndexRouteImport.update({
    id: '/mon/inventory/',
    path: '/mon/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonHelpCenterIndexRoute =
  AuthenticatedMonHelpCenterIndexRouteImport.update({
    id: '/mon/help-center/',
    path: '/mon/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonCouponsIndexRoute =
  AuthenticatedMonCouponsIndexRouteImport.update({
    id: '/mon/coupons/',
    path: '/mon/coupons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonSettingsNotificationsRoute =
  AuthenticatedMonSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsDisplayRoute =
  AuthenticatedMonSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsAppearanceRoute =
  AuthenticatedMonSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsAccountRoute =
  AuthenticatedMonSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsSystemIndexRoute =
  AuthenticatedMonSettingsSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsStorageIndexRoute =
  AuthenticatedMonSettingsStorageIndexRouteImport.update({
    id: '/storage/',
    path: '/storage/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsPersonalIndexRoute =
  AuthenticatedMonSettingsPersonalIndexRouteImport.update({
    id: '/personal/',
    path: '/personal/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsOrderStatusesIndexRoute =
  AuthenticatedMonSettingsOrderStatusesIndexRouteImport.update({
    id: '/order-statuses/',
    path: '/order-statuses/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsGatewaysIndexRoute =
  AuthenticatedMonSettingsGatewaysIndexRouteImport.update({
    id: '/gateways/',
    path: '/gateways/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsCourierIndexRoute =
  AuthenticatedMonSettingsCourierIndexRouteImport.update({
    id: '/courier/',
    path: '/courier/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsSystemStorageIndexRoute =
  AuthenticatedMonSettingsSystemStorageIndexRouteImport.update({
    id: '/system/storage/',
    path: '/system/storage/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsSystemOrderStatusesIndexRoute =
  AuthenticatedMonSettingsSystemOrderStatusesIndexRouteImport.update({
    id: '/system/order-statuses/',
    path: '/system/order-statuses/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsSystemGatewaysIndexRoute =
  AuthenticatedMonSettingsSystemGatewaysIndexRouteImport.update({
    id: '/system/gateways/',
    path: '/system/gateways/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsSystemCourierIndexRoute =
  AuthenticatedMonSettingsSystemCourierIndexRouteImport.update({
    id: '/system/courier/',
    path: '/system/courier/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/mon/settings': typeof AuthenticatedMonSettingsRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/mon/': typeof AuthenticatedMonIndexRoute
  '/op/': typeof AuthenticatedOpIndexRoute
  '/mon/settings/account': typeof AuthenticatedMonSettingsAccountRoute
  '/mon/settings/appearance': typeof AuthenticatedMonSettingsAppearanceRoute
  '/mon/settings/display': typeof AuthenticatedMonSettingsDisplayRoute
  '/mon/settings/notifications': typeof AuthenticatedMonSettingsNotificationsRoute
  '/mon/coupons/': typeof AuthenticatedMonCouponsIndexRoute
  '/mon/help-center/': typeof AuthenticatedMonHelpCenterIndexRoute
  '/mon/inventory/': typeof AuthenticatedMonInventoryIndexRoute
  '/mon/refunds/': typeof AuthenticatedMonRefundsIndexRoute
  '/mon/settings/': typeof AuthenticatedMonSettingsIndexRoute
  '/mon/shipments/': typeof AuthenticatedMonShipmentsIndexRoute
  '/mon/users/': typeof AuthenticatedMonUsersIndexRoute
  '/op/apps/': typeof AuthenticatedOpAppsIndexRoute
  '/op/attributes/': typeof AuthenticatedOpAttributesIndexRoute
  '/op/categories/': typeof AuthenticatedOpCategoriesIndexRoute
  '/op/chats/': typeof AuthenticatedOpChatsIndexRoute
  '/op/customers/': typeof AuthenticatedOpCustomersIndexRoute
  '/op/media/': typeof AuthenticatedOpMediaIndexRoute
  '/op/orders/': typeof AuthenticatedOpOrdersIndexRoute
  '/op/payments/': typeof AuthenticatedOpPaymentsIndexRoute
  '/op/products/': typeof AuthenticatedOpProductsIndexRoute
  '/op/tasks/': typeof AuthenticatedOpTasksIndexRoute
  '/mon/settings/courier/': typeof AuthenticatedMonSettingsCourierIndexRoute
  '/mon/settings/gateways/': typeof AuthenticatedMonSettingsGatewaysIndexRoute
  '/mon/settings/order-statuses/': typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  '/mon/settings/personal/': typeof AuthenticatedMonSettingsPersonalIndexRoute
  '/mon/settings/storage/': typeof AuthenticatedMonSettingsStorageIndexRoute
  '/mon/settings/system/': typeof AuthenticatedMonSettingsSystemIndexRoute
  '/mon/settings/system/courier/': typeof AuthenticatedMonSettingsSystemCourierIndexRoute
  '/mon/settings/system/gateways/': typeof AuthenticatedMonSettingsSystemGatewaysIndexRoute
  '/mon/settings/system/order-statuses/': typeof AuthenticatedMonSettingsSystemOrderStatusesIndexRoute
  '/mon/settings/system/storage/': typeof AuthenticatedMonSettingsSystemStorageIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/mon': typeof AuthenticatedMonIndexRoute
  '/op': typeof AuthenticatedOpIndexRoute
  '/mon/settings/account': typeof AuthenticatedMonSettingsAccountRoute
  '/mon/settings/appearance': typeof AuthenticatedMonSettingsAppearanceRoute
  '/mon/settings/display': typeof AuthenticatedMonSettingsDisplayRoute
  '/mon/settings/notifications': typeof AuthenticatedMonSettingsNotificationsRoute
  '/mon/coupons': typeof AuthenticatedMonCouponsIndexRoute
  '/mon/help-center': typeof AuthenticatedMonHelpCenterIndexRoute
  '/mon/inventory': typeof AuthenticatedMonInventoryIndexRoute
  '/mon/refunds': typeof AuthenticatedMonRefundsIndexRoute
  '/mon/settings': typeof AuthenticatedMonSettingsIndexRoute
  '/mon/shipments': typeof AuthenticatedMonShipmentsIndexRoute
  '/mon/users': typeof AuthenticatedMonUsersIndexRoute
  '/op/apps': typeof AuthenticatedOpAppsIndexRoute
  '/op/attributes': typeof AuthenticatedOpAttributesIndexRoute
  '/op/categories': typeof AuthenticatedOpCategoriesIndexRoute
  '/op/chats': typeof AuthenticatedOpChatsIndexRoute
  '/op/customers': typeof AuthenticatedOpCustomersIndexRoute
  '/op/media': typeof AuthenticatedOpMediaIndexRoute
  '/op/orders': typeof AuthenticatedOpOrdersIndexRoute
  '/op/payments': typeof AuthenticatedOpPaymentsIndexRoute
  '/op/products': typeof AuthenticatedOpProductsIndexRoute
  '/op/tasks': typeof AuthenticatedOpTasksIndexRoute
  '/mon/settings/courier': typeof AuthenticatedMonSettingsCourierIndexRoute
  '/mon/settings/gateways': typeof AuthenticatedMonSettingsGatewaysIndexRoute
  '/mon/settings/order-statuses': typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  '/mon/settings/personal': typeof AuthenticatedMonSettingsPersonalIndexRoute
  '/mon/settings/storage': typeof AuthenticatedMonSettingsStorageIndexRoute
  '/mon/settings/system': typeof AuthenticatedMonSettingsSystemIndexRoute
  '/mon/settings/system/courier': typeof AuthenticatedMonSettingsSystemCourierIndexRoute
  '/mon/settings/system/gateways': typeof AuthenticatedMonSettingsSystemGatewaysIndexRoute
  '/mon/settings/system/order-statuses': typeof AuthenticatedMonSettingsSystemOrderStatusesIndexRoute
  '/mon/settings/system/storage': typeof AuthenticatedMonSettingsSystemStorageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/mon/settings': typeof AuthenticatedMonSettingsRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/mon/': typeof AuthenticatedMonIndexRoute
  '/_authenticated/op/': typeof AuthenticatedOpIndexRoute
  '/_authenticated/mon/settings/account': typeof AuthenticatedMonSettingsAccountRoute
  '/_authenticated/mon/settings/appearance': typeof AuthenticatedMonSettingsAppearanceRoute
  '/_authenticated/mon/settings/display': typeof AuthenticatedMonSettingsDisplayRoute
  '/_authenticated/mon/settings/notifications': typeof AuthenticatedMonSettingsNotificationsRoute
  '/_authenticated/mon/coupons/': typeof AuthenticatedMonCouponsIndexRoute
  '/_authenticated/mon/help-center/': typeof AuthenticatedMonHelpCenterIndexRoute
  '/_authenticated/mon/inventory/': typeof AuthenticatedMonInventoryIndexRoute
  '/_authenticated/mon/refunds/': typeof AuthenticatedMonRefundsIndexRoute
  '/_authenticated/mon/settings/': typeof AuthenticatedMonSettingsIndexRoute
  '/_authenticated/mon/shipments/': typeof AuthenticatedMonShipmentsIndexRoute
  '/_authenticated/mon/users/': typeof AuthenticatedMonUsersIndexRoute
  '/_authenticated/op/apps/': typeof AuthenticatedOpAppsIndexRoute
  '/_authenticated/op/attributes/': typeof AuthenticatedOpAttributesIndexRoute
  '/_authenticated/op/categories/': typeof AuthenticatedOpCategoriesIndexRoute
  '/_authenticated/op/chats/': typeof AuthenticatedOpChatsIndexRoute
  '/_authenticated/op/customers/': typeof AuthenticatedOpCustomersIndexRoute
  '/_authenticated/op/media/': typeof AuthenticatedOpMediaIndexRoute
  '/_authenticated/op/orders/': typeof AuthenticatedOpOrdersIndexRoute
  '/_authenticated/op/payments/': typeof AuthenticatedOpPaymentsIndexRoute
  '/_authenticated/op/products/': typeof AuthenticatedOpProductsIndexRoute
  '/_authenticated/op/tasks/': typeof AuthenticatedOpTasksIndexRoute
  '/_authenticated/mon/settings/courier/': typeof AuthenticatedMonSettingsCourierIndexRoute
  '/_authenticated/mon/settings/gateways/': typeof AuthenticatedMonSettingsGatewaysIndexRoute
  '/_authenticated/mon/settings/order-statuses/': typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  '/_authenticated/mon/settings/personal/': typeof AuthenticatedMonSettingsPersonalIndexRoute
  '/_authenticated/mon/settings/storage/': typeof AuthenticatedMonSettingsStorageIndexRoute
  '/_authenticated/mon/settings/system/': typeof AuthenticatedMonSettingsSystemIndexRoute
  '/_authenticated/mon/settings/system/courier/': typeof AuthenticatedMonSettingsSystemCourierIndexRoute
  '/_authenticated/mon/settings/system/gateways/': typeof AuthenticatedMonSettingsSystemGatewaysIndexRoute
  '/_authenticated/mon/settings/system/order-statuses/': typeof AuthenticatedMonSettingsSystemOrderStatusesIndexRoute
  '/_authenticated/mon/settings/system/storage/': typeof AuthenticatedMonSettingsSystemStorageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/mon/settings'
    | '/errors/$error'
    | '/mon/'
    | '/op/'
    | '/mon/settings/account'
    | '/mon/settings/appearance'
    | '/mon/settings/display'
    | '/mon/settings/notifications'
    | '/mon/coupons/'
    | '/mon/help-center/'
    | '/mon/inventory/'
    | '/mon/refunds/'
    | '/mon/settings/'
    | '/mon/shipments/'
    | '/mon/users/'
    | '/op/apps/'
    | '/op/attributes/'
    | '/op/categories/'
    | '/op/chats/'
    | '/op/customers/'
    | '/op/media/'
    | '/op/orders/'
    | '/op/payments/'
    | '/op/products/'
    | '/op/tasks/'
    | '/mon/settings/courier/'
    | '/mon/settings/gateways/'
    | '/mon/settings/order-statuses/'
    | '/mon/settings/personal/'
    | '/mon/settings/storage/'
    | '/mon/settings/system/'
    | '/mon/settings/system/courier/'
    | '/mon/settings/system/gateways/'
    | '/mon/settings/system/order-statuses/'
    | '/mon/settings/system/storage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/errors/$error'
    | '/mon'
    | '/op'
    | '/mon/settings/account'
    | '/mon/settings/appearance'
    | '/mon/settings/display'
    | '/mon/settings/notifications'
    | '/mon/coupons'
    | '/mon/help-center'
    | '/mon/inventory'
    | '/mon/refunds'
    | '/mon/settings'
    | '/mon/shipments'
    | '/mon/users'
    | '/op/apps'
    | '/op/attributes'
    | '/op/categories'
    | '/op/chats'
    | '/op/customers'
    | '/op/media'
    | '/op/orders'
    | '/op/payments'
    | '/op/products'
    | '/op/tasks'
    | '/mon/settings/courier'
    | '/mon/settings/gateways'
    | '/mon/settings/order-statuses'
    | '/mon/settings/personal'
    | '/mon/settings/storage'
    | '/mon/settings/system'
    | '/mon/settings/system/courier'
    | '/mon/settings/system/gateways'
    | '/mon/settings/system/order-statuses'
    | '/mon/settings/system/storage'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/mon/settings'
    | '/_authenticated/errors/$error'
    | '/_authenticated/mon/'
    | '/_authenticated/op/'
    | '/_authenticated/mon/settings/account'
    | '/_authenticated/mon/settings/appearance'
    | '/_authenticated/mon/settings/display'
    | '/_authenticated/mon/settings/notifications'
    | '/_authenticated/mon/coupons/'
    | '/_authenticated/mon/help-center/'
    | '/_authenticated/mon/inventory/'
    | '/_authenticated/mon/refunds/'
    | '/_authenticated/mon/settings/'
    | '/_authenticated/mon/shipments/'
    | '/_authenticated/mon/users/'
    | '/_authenticated/op/apps/'
    | '/_authenticated/op/attributes/'
    | '/_authenticated/op/categories/'
    | '/_authenticated/op/chats/'
    | '/_authenticated/op/customers/'
    | '/_authenticated/op/media/'
    | '/_authenticated/op/orders/'
    | '/_authenticated/op/payments/'
    | '/_authenticated/op/products/'
    | '/_authenticated/op/tasks/'
    | '/_authenticated/mon/settings/courier/'
    | '/_authenticated/mon/settings/gateways/'
    | '/_authenticated/mon/settings/order-statuses/'
    | '/_authenticated/mon/settings/personal/'
    | '/_authenticated/mon/settings/storage/'
    | '/_authenticated/mon/settings/system/'
    | '/_authenticated/mon/settings/system/courier/'
    | '/_authenticated/mon/settings/system/gateways/'
    | '/_authenticated/mon/settings/system/order-statuses/'
    | '/_authenticated/mon/settings/system/storage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/op/': {
      id: '/_authenticated/op/'
      path: '/op'
      fullPath: '/op/'
      preLoaderRoute: typeof AuthenticatedOpIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/': {
      id: '/_authenticated/mon/'
      path: '/mon'
      fullPath: '/mon/'
      preLoaderRoute: typeof AuthenticatedMonIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/settings': {
      id: '/_authenticated/mon/settings'
      path: '/mon/settings'
      fullPath: '/mon/settings'
      preLoaderRoute: typeof AuthenticatedMonSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/tasks/': {
      id: '/_authenticated/op/tasks/'
      path: '/op/tasks'
      fullPath: '/op/tasks/'
      preLoaderRoute: typeof AuthenticatedOpTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/products/': {
      id: '/_authenticated/op/products/'
      path: '/op/products'
      fullPath: '/op/products/'
      preLoaderRoute: typeof AuthenticatedOpProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/payments/': {
      id: '/_authenticated/op/payments/'
      path: '/op/payments'
      fullPath: '/op/payments/'
      preLoaderRoute: typeof AuthenticatedOpPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/orders/': {
      id: '/_authenticated/op/orders/'
      path: '/op/orders'
      fullPath: '/op/orders/'
      preLoaderRoute: typeof AuthenticatedOpOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/media/': {
      id: '/_authenticated/op/media/'
      path: '/op/media'
      fullPath: '/op/media/'
      preLoaderRoute: typeof AuthenticatedOpMediaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/customers/': {
      id: '/_authenticated/op/customers/'
      path: '/op/customers'
      fullPath: '/op/customers/'
      preLoaderRoute: typeof AuthenticatedOpCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/chats/': {
      id: '/_authenticated/op/chats/'
      path: '/op/chats'
      fullPath: '/op/chats/'
      preLoaderRoute: typeof AuthenticatedOpChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/categories/': {
      id: '/_authenticated/op/categories/'
      path: '/op/categories'
      fullPath: '/op/categories/'
      preLoaderRoute: typeof AuthenticatedOpCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/attributes/': {
      id: '/_authenticated/op/attributes/'
      path: '/op/attributes'
      fullPath: '/op/attributes/'
      preLoaderRoute: typeof AuthenticatedOpAttributesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/apps/': {
      id: '/_authenticated/op/apps/'
      path: '/op/apps'
      fullPath: '/op/apps/'
      preLoaderRoute: typeof AuthenticatedOpAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/users/': {
      id: '/_authenticated/mon/users/'
      path: '/mon/users'
      fullPath: '/mon/users/'
      preLoaderRoute: typeof AuthenticatedMonUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/shipments/': {
      id: '/_authenticated/mon/shipments/'
      path: '/mon/shipments'
      fullPath: '/mon/shipments/'
      preLoaderRoute: typeof AuthenticatedMonShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/settings/': {
      id: '/_authenticated/mon/settings/'
      path: '/'
      fullPath: '/mon/settings/'
      preLoaderRoute: typeof AuthenticatedMonSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/refunds/': {
      id: '/_authenticated/mon/refunds/'
      path: '/mon/refunds'
      fullPath: '/mon/refunds/'
      preLoaderRoute: typeof AuthenticatedMonRefundsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/inventory/': {
      id: '/_authenticated/mon/inventory/'
      path: '/mon/inventory'
      fullPath: '/mon/inventory/'
      preLoaderRoute: typeof AuthenticatedMonInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/help-center/': {
      id: '/_authenticated/mon/help-center/'
      path: '/mon/help-center'
      fullPath: '/mon/help-center/'
      preLoaderRoute: typeof AuthenticatedMonHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/coupons/': {
      id: '/_authenticated/mon/coupons/'
      path: '/mon/coupons'
      fullPath: '/mon/coupons/'
      preLoaderRoute: typeof AuthenticatedMonCouponsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/settings/notifications': {
      id: '/_authenticated/mon/settings/notifications'
      path: '/notifications'
      fullPath: '/mon/settings/notifications'
      preLoaderRoute: typeof AuthenticatedMonSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/display': {
      id: '/_authenticated/mon/settings/display'
      path: '/display'
      fullPath: '/mon/settings/display'
      preLoaderRoute: typeof AuthenticatedMonSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/appearance': {
      id: '/_authenticated/mon/settings/appearance'
      path: '/appearance'
      fullPath: '/mon/settings/appearance'
      preLoaderRoute: typeof AuthenticatedMonSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/account': {
      id: '/_authenticated/mon/settings/account'
      path: '/account'
      fullPath: '/mon/settings/account'
      preLoaderRoute: typeof AuthenticatedMonSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/system/': {
      id: '/_authenticated/mon/settings/system/'
      path: '/system'
      fullPath: '/mon/settings/system/'
      preLoaderRoute: typeof AuthenticatedMonSettingsSystemIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/storage/': {
      id: '/_authenticated/mon/settings/storage/'
      path: '/storage'
      fullPath: '/mon/settings/storage/'
      preLoaderRoute: typeof AuthenticatedMonSettingsStorageIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/personal/': {
      id: '/_authenticated/mon/settings/personal/'
      path: '/personal'
      fullPath: '/mon/settings/personal/'
      preLoaderRoute: typeof AuthenticatedMonSettingsPersonalIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/order-statuses/': {
      id: '/_authenticated/mon/settings/order-statuses/'
      path: '/order-statuses'
      fullPath: '/mon/settings/order-statuses/'
      preLoaderRoute: typeof AuthenticatedMonSettingsOrderStatusesIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/gateways/': {
      id: '/_authenticated/mon/settings/gateways/'
      path: '/gateways'
      fullPath: '/mon/settings/gateways/'
      preLoaderRoute: typeof AuthenticatedMonSettingsGatewaysIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/courier/': {
      id: '/_authenticated/mon/settings/courier/'
      path: '/courier'
      fullPath: '/mon/settings/courier/'
      preLoaderRoute: typeof AuthenticatedMonSettingsCourierIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/system/storage/': {
      id: '/_authenticated/mon/settings/system/storage/'
      path: '/system/storage'
      fullPath: '/mon/settings/system/storage/'
      preLoaderRoute: typeof AuthenticatedMonSettingsSystemStorageIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/system/order-statuses/': {
      id: '/_authenticated/mon/settings/system/order-statuses/'
      path: '/system/order-statuses'
      fullPath: '/mon/settings/system/order-statuses/'
      preLoaderRoute: typeof AuthenticatedMonSettingsSystemOrderStatusesIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/system/gateways/': {
      id: '/_authenticated/mon/settings/system/gateways/'
      path: '/system/gateways'
      fullPath: '/mon/settings/system/gateways/'
      preLoaderRoute: typeof AuthenticatedMonSettingsSystemGatewaysIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/system/courier/': {
      id: '/_authenticated/mon/settings/system/courier/'
      path: '/system/courier'
      fullPath: '/mon/settings/system/courier/'
      preLoaderRoute: typeof AuthenticatedMonSettingsSystemCourierIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
  }
}

interface AuthenticatedMonSettingsRouteRouteChildren {
  AuthenticatedMonSettingsAccountRoute: typeof AuthenticatedMonSettingsAccountRoute
  AuthenticatedMonSettingsAppearanceRoute: typeof AuthenticatedMonSettingsAppearanceRoute
  AuthenticatedMonSettingsDisplayRoute: typeof AuthenticatedMonSettingsDisplayRoute
  AuthenticatedMonSettingsNotificationsRoute: typeof AuthenticatedMonSettingsNotificationsRoute
  AuthenticatedMonSettingsIndexRoute: typeof AuthenticatedMonSettingsIndexRoute
  AuthenticatedMonSettingsCourierIndexRoute: typeof AuthenticatedMonSettingsCourierIndexRoute
  AuthenticatedMonSettingsGatewaysIndexRoute: typeof AuthenticatedMonSettingsGatewaysIndexRoute
  AuthenticatedMonSettingsOrderStatusesIndexRoute: typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  AuthenticatedMonSettingsPersonalIndexRoute: typeof AuthenticatedMonSettingsPersonalIndexRoute
  AuthenticatedMonSettingsStorageIndexRoute: typeof AuthenticatedMonSettingsStorageIndexRoute
  AuthenticatedMonSettingsSystemIndexRoute: typeof AuthenticatedMonSettingsSystemIndexRoute
  AuthenticatedMonSettingsSystemCourierIndexRoute: typeof AuthenticatedMonSettingsSystemCourierIndexRoute
  AuthenticatedMonSettingsSystemGatewaysIndexRoute: typeof AuthenticatedMonSettingsSystemGatewaysIndexRoute
  AuthenticatedMonSettingsSystemOrderStatusesIndexRoute: typeof AuthenticatedMonSettingsSystemOrderStatusesIndexRoute
  AuthenticatedMonSettingsSystemStorageIndexRoute: typeof AuthenticatedMonSettingsSystemStorageIndexRoute
}

const AuthenticatedMonSettingsRouteRouteChildren: AuthenticatedMonSettingsRouteRouteChildren =
  {
    AuthenticatedMonSettingsAccountRoute: AuthenticatedMonSettingsAccountRoute,
    AuthenticatedMonSettingsAppearanceRoute:
      AuthenticatedMonSettingsAppearanceRoute,
    AuthenticatedMonSettingsDisplayRoute: AuthenticatedMonSettingsDisplayRoute,
    AuthenticatedMonSettingsNotificationsRoute:
      AuthenticatedMonSettingsNotificationsRoute,
    AuthenticatedMonSettingsIndexRoute: AuthenticatedMonSettingsIndexRoute,
    AuthenticatedMonSettingsCourierIndexRoute:
      AuthenticatedMonSettingsCourierIndexRoute,
    AuthenticatedMonSettingsGatewaysIndexRoute:
      AuthenticatedMonSettingsGatewaysIndexRoute,
    AuthenticatedMonSettingsOrderStatusesIndexRoute:
      AuthenticatedMonSettingsOrderStatusesIndexRoute,
    AuthenticatedMonSettingsPersonalIndexRoute:
      AuthenticatedMonSettingsPersonalIndexRoute,
    AuthenticatedMonSettingsStorageIndexRoute:
      AuthenticatedMonSettingsStorageIndexRoute,
    AuthenticatedMonSettingsSystemIndexRoute:
      AuthenticatedMonSettingsSystemIndexRoute,
    AuthenticatedMonSettingsSystemCourierIndexRoute:
      AuthenticatedMonSettingsSystemCourierIndexRoute,
    AuthenticatedMonSettingsSystemGatewaysIndexRoute:
      AuthenticatedMonSettingsSystemGatewaysIndexRoute,
    AuthenticatedMonSettingsSystemOrderStatusesIndexRoute:
      AuthenticatedMonSettingsSystemOrderStatusesIndexRoute,
    AuthenticatedMonSettingsSystemStorageIndexRoute:
      AuthenticatedMonSettingsSystemStorageIndexRoute,
  }

const AuthenticatedMonSettingsRouteRouteWithChildren =
  AuthenticatedMonSettingsRouteRoute._addFileChildren(
    AuthenticatedMonSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMonSettingsRouteRoute: typeof AuthenticatedMonSettingsRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedMonIndexRoute: typeof AuthenticatedMonIndexRoute
  AuthenticatedOpIndexRoute: typeof AuthenticatedOpIndexRoute
  AuthenticatedMonCouponsIndexRoute: typeof AuthenticatedMonCouponsIndexRoute
  AuthenticatedMonHelpCenterIndexRoute: typeof AuthenticatedMonHelpCenterIndexRoute
  AuthenticatedMonInventoryIndexRoute: typeof AuthenticatedMonInventoryIndexRoute
  AuthenticatedMonRefundsIndexRoute: typeof AuthenticatedMonRefundsIndexRoute
  AuthenticatedMonShipmentsIndexRoute: typeof AuthenticatedMonShipmentsIndexRoute
  AuthenticatedMonUsersIndexRoute: typeof AuthenticatedMonUsersIndexRoute
  AuthenticatedOpAppsIndexRoute: typeof AuthenticatedOpAppsIndexRoute
  AuthenticatedOpAttributesIndexRoute: typeof AuthenticatedOpAttributesIndexRoute
  AuthenticatedOpCategoriesIndexRoute: typeof AuthenticatedOpCategoriesIndexRoute
  AuthenticatedOpChatsIndexRoute: typeof AuthenticatedOpChatsIndexRoute
  AuthenticatedOpCustomersIndexRoute: typeof AuthenticatedOpCustomersIndexRoute
  AuthenticatedOpMediaIndexRoute: typeof AuthenticatedOpMediaIndexRoute
  AuthenticatedOpOrdersIndexRoute: typeof AuthenticatedOpOrdersIndexRoute
  AuthenticatedOpPaymentsIndexRoute: typeof AuthenticatedOpPaymentsIndexRoute
  AuthenticatedOpProductsIndexRoute: typeof AuthenticatedOpProductsIndexRoute
  AuthenticatedOpTasksIndexRoute: typeof AuthenticatedOpTasksIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMonSettingsRouteRoute:
    AuthenticatedMonSettingsRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedMonIndexRoute: AuthenticatedMonIndexRoute,
  AuthenticatedOpIndexRoute: AuthenticatedOpIndexRoute,
  AuthenticatedMonCouponsIndexRoute: AuthenticatedMonCouponsIndexRoute,
  AuthenticatedMonHelpCenterIndexRoute: AuthenticatedMonHelpCenterIndexRoute,
  AuthenticatedMonInventoryIndexRoute: AuthenticatedMonInventoryIndexRoute,
  AuthenticatedMonRefundsIndexRoute: AuthenticatedMonRefundsIndexRoute,
  AuthenticatedMonShipmentsIndexRoute: AuthenticatedMonShipmentsIndexRoute,
  AuthenticatedMonUsersIndexRoute: AuthenticatedMonUsersIndexRoute,
  AuthenticatedOpAppsIndexRoute: AuthenticatedOpAppsIndexRoute,
  AuthenticatedOpAttributesIndexRoute: AuthenticatedOpAttributesIndexRoute,
  AuthenticatedOpCategoriesIndexRoute: AuthenticatedOpCategoriesIndexRoute,
  AuthenticatedOpChatsIndexRoute: AuthenticatedOpChatsIndexRoute,
  AuthenticatedOpCustomersIndexRoute: AuthenticatedOpCustomersIndexRoute,
  AuthenticatedOpMediaIndexRoute: AuthenticatedOpMediaIndexRoute,
  AuthenticatedOpOrdersIndexRoute: AuthenticatedOpOrdersIndexRoute,
  AuthenticatedOpPaymentsIndexRoute: AuthenticatedOpPaymentsIndexRoute,
  AuthenticatedOpProductsIndexRoute: AuthenticatedOpProductsIndexRoute,
  AuthenticatedOpTasksIndexRoute: AuthenticatedOpTasksIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
