/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedOpIndexRouteImport } from './routes/_authenticated/op/index'
import { Route as AuthenticatedMonIndexRouteImport } from './routes/_authenticated/mon/index'
import { Route as AuthenticatedOpOverviewRouteImport } from './routes/_authenticated/op/overview'
import { Route as AuthenticatedMonOverviewRouteImport } from './routes/_authenticated/mon/overview'
import { Route as AuthenticatedMonBlockingSettingsRouteImport } from './routes/_authenticated/mon/blocking-settings'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedOpSettingsRouteRouteImport } from './routes/_authenticated/op/settings/route'
import { Route as AuthenticatedOpPrintRouteRouteImport } from './routes/_authenticated/op/print/route'
import { Route as AuthenticatedMonSettingsRouteRouteImport } from './routes/_authenticated/mon/settings/route'
import { Route as AuthenticatedOpTransactionsIndexRouteImport } from './routes/_authenticated/op/transactions/index'
import { Route as AuthenticatedOpTasksIndexRouteImport } from './routes/_authenticated/op/tasks/index'
import { Route as AuthenticatedOpTagsIndexRouteImport } from './routes/_authenticated/op/tags/index'
import { Route as AuthenticatedOpSuppliersIndexRouteImport } from './routes/_authenticated/op/suppliers/index'
import { Route as AuthenticatedOpSizeChartsIndexRouteImport } from './routes/_authenticated/op/size-charts/index'
import { Route as AuthenticatedOpShipmentsIndexRouteImport } from './routes/_authenticated/op/shipments/index'
import { Route as AuthenticatedOpReviewsIndexRouteImport } from './routes/_authenticated/op/reviews/index'
import { Route as AuthenticatedOpRefundsIndexRouteImport } from './routes/_authenticated/op/refunds/index'
import { Route as AuthenticatedOpPurchasesIndexRouteImport } from './routes/_authenticated/op/purchases/index'
import { Route as AuthenticatedOpProductsIndexRouteImport } from './routes/_authenticated/op/products/index'
import { Route as AuthenticatedOpPaymentsIndexRouteImport } from './routes/_authenticated/op/payments/index'
import { Route as AuthenticatedOpOrdersIndexRouteImport } from './routes/_authenticated/op/orders/index'
import { Route as AuthenticatedOpNotificationsIndexRouteImport } from './routes/_authenticated/op/notifications/index'
import { Route as AuthenticatedOpMediaIndexRouteImport } from './routes/_authenticated/op/media/index'
import { Route as AuthenticatedOpLandingPagesIndexRouteImport } from './routes/_authenticated/op/landing-pages/index'
import { Route as AuthenticatedOpInventoryIndexRouteImport } from './routes/_authenticated/op/inventory/index'
import { Route as AuthenticatedOpImportProductsIndexRouteImport } from './routes/_authenticated/op/import-products/index'
import { Route as AuthenticatedOpImportOrdersIndexRouteImport } from './routes/_authenticated/op/import-orders/index'
import { Route as AuthenticatedOpHelpCenterIndexRouteImport } from './routes/_authenticated/op/help-center/index'
import { Route as AuthenticatedOpExpensesIndexRouteImport } from './routes/_authenticated/op/expenses/index'
import { Route as AuthenticatedOpCustomersIndexRouteImport } from './routes/_authenticated/op/customers/index'
import { Route as AuthenticatedOpCouponsIndexRouteImport } from './routes/_authenticated/op/coupons/index'
import { Route as AuthenticatedOpCombosIndexRouteImport } from './routes/_authenticated/op/combos/index'
import { Route as AuthenticatedOpChatsIndexRouteImport } from './routes/_authenticated/op/chats/index'
import { Route as AuthenticatedOpCategoriesIndexRouteImport } from './routes/_authenticated/op/categories/index'
import { Route as AuthenticatedOpCampaignsIndexRouteImport } from './routes/_authenticated/op/campaigns/index'
import { Route as AuthenticatedOpBrandsIndexRouteImport } from './routes/_authenticated/op/brands/index'
import { Route as AuthenticatedOpBlockedIndexRouteImport } from './routes/_authenticated/op/blocked/index'
import { Route as AuthenticatedOpAttributesIndexRouteImport } from './routes/_authenticated/op/attributes/index'
import { Route as AuthenticatedOpAppsIndexRouteImport } from './routes/_authenticated/op/apps/index'
import { Route as AuthenticatedMonUsersIndexRouteImport } from './routes/_authenticated/mon/users/index'
import { Route as AuthenticatedMonPagesIndexRouteImport } from './routes/_authenticated/mon/pages/index'
import { Route as AuthenticatedMonHelpCenterIndexRouteImport } from './routes/_authenticated/mon/help-center/index'
import { Route as AuthenticatedMonAnalyticsIndexRouteImport } from './routes/_authenticated/mon/analytics/index'
import { Route as AuthenticatedMonActivityLogsIndexRouteImport } from './routes/_authenticated/mon/activity-logs/index'
import { Route as AuthenticatedOpOrdersCreateRouteImport } from './routes/_authenticated/op/orders/create'
import { Route as AuthenticatedOpOrdersIdRouteImport } from './routes/_authenticated/op/orders/$id'
import { Route as AuthenticatedOpInventoryValuationRouteImport } from './routes/_authenticated/op/inventory/valuation'
import { Route as AuthenticatedOpInventoryOverviewRouteImport } from './routes/_authenticated/op/inventory/overview'
import { Route as AuthenticatedOpCustomersIdRouteImport } from './routes/_authenticated/op/customers/$id'
import { Route as AuthenticatedMonUsersIdRouteImport } from './routes/_authenticated/mon/users/$id'
import { Route as AuthenticatedOpSettingsPersonalIndexRouteImport } from './routes/_authenticated/op/settings/personal/index'
import { Route as AuthenticatedOpPrintBulkIndexRouteImport } from './routes/_authenticated/op/print/bulk/index'
import { Route as AuthenticatedOpOrdersIncompleteLeadsIndexRouteImport } from './routes/_authenticated/op/orders/incomplete-leads/index'
import { Route as AuthenticatedMonSettingsTrackingIndexRouteImport } from './routes/_authenticated/mon/settings/tracking/index'
import { Route as AuthenticatedMonSettingsSystemIndexRouteImport } from './routes/_authenticated/mon/settings/system/index'
import { Route as AuthenticatedMonSettingsStorefrontIndexRouteImport } from './routes/_authenticated/mon/settings/storefront/index'
import { Route as AuthenticatedMonSettingsStorageIndexRouteImport } from './routes/_authenticated/mon/settings/storage/index'
import { Route as AuthenticatedMonSettingsShippingIndexRouteImport } from './routes/_authenticated/mon/settings/shipping/index'
import { Route as AuthenticatedMonSettingsOrderStatusesIndexRouteImport } from './routes/_authenticated/mon/settings/order-statuses/index'
import { Route as AuthenticatedMonSettingsMenuIndexRouteImport } from './routes/_authenticated/mon/settings/menu/index'
import { Route as AuthenticatedMonSettingsHomepageIndexRouteImport } from './routes/_authenticated/mon/settings/homepage/index'
import { Route as AuthenticatedMonSettingsGeneralIndexRouteImport } from './routes/_authenticated/mon/settings/general/index'
import { Route as AuthenticatedMonSettingsGatewaysIndexRouteImport } from './routes/_authenticated/mon/settings/gateways/index'
import { Route as AuthenticatedMonSettingsCourierIndexRouteImport } from './routes/_authenticated/mon/settings/courier/index'
import { Route as AuthenticatedMonSettingsBrandingIndexRouteImport } from './routes/_authenticated/mon/settings/branding/index'
import { Route as AuthenticatedOpPrintStickerIdRouteImport } from './routes/_authenticated/op/print/sticker/$id'
import { Route as AuthenticatedOpPrintInvoiceIdRouteImport } from './routes/_authenticated/op/print/invoice/$id'
import { Route as AuthenticatedOpOrdersIncompleteLeadsIdConvertRouteImport } from './routes/_authenticated/op/orders/incomplete-leads/$id/convert'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOpIndexRoute = AuthenticatedOpIndexRouteImport.update({
  id: '/op/',
  path: '/op/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonIndexRoute = AuthenticatedMonIndexRouteImport.update({
  id: '/mon/',
  path: '/mon/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpOverviewRoute = AuthenticatedOpOverviewRouteImport.update({
  id: '/op/overview',
  path: '/op/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonOverviewRoute =
  AuthenticatedMonOverviewRouteImport.update({
    id: '/mon/overview',
    path: '/mon/overview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonBlockingSettingsRoute =
  AuthenticatedMonBlockingSettingsRouteImport.update({
    id: '/mon/blocking-settings',
    path: '/mon/blocking-settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpSettingsRouteRoute =
  AuthenticatedOpSettingsRouteRouteImport.update({
    id: '/op/settings',
    path: '/op/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpPrintRouteRoute =
  AuthenticatedOpPrintRouteRouteImport.update({
    id: '/op/print',
    path: '/op/print',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonSettingsRouteRoute =
  AuthenticatedMonSettingsRouteRouteImport.update({
    id: '/mon/settings',
    path: '/mon/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpTransactionsIndexRoute =
  AuthenticatedOpTransactionsIndexRouteImport.update({
    id: '/op/transactions/',
    path: '/op/transactions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpTasksIndexRoute =
  AuthenticatedOpTasksIndexRouteImport.update({
    id: '/op/tasks/',
    path: '/op/tasks/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpTagsIndexRoute =
  AuthenticatedOpTagsIndexRouteImport.update({
    id: '/op/tags/',
    path: '/op/tags/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpSuppliersIndexRoute =
  AuthenticatedOpSuppliersIndexRouteImport.update({
    id: '/op/suppliers/',
    path: '/op/suppliers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpSizeChartsIndexRoute =
  AuthenticatedOpSizeChartsIndexRouteImport.update({
    id: '/op/size-charts/',
    path: '/op/size-charts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpShipmentsIndexRoute =
  AuthenticatedOpShipmentsIndexRouteImport.update({
    id: '/op/shipments/',
    path: '/op/shipments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpReviewsIndexRoute =
  AuthenticatedOpReviewsIndexRouteImport.update({
    id: '/op/reviews/',
    path: '/op/reviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpRefundsIndexRoute =
  AuthenticatedOpRefundsIndexRouteImport.update({
    id: '/op/refunds/',
    path: '/op/refunds/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpPurchasesIndexRoute =
  AuthenticatedOpPurchasesIndexRouteImport.update({
    id: '/op/purchases/',
    path: '/op/purchases/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpProductsIndexRoute =
  AuthenticatedOpProductsIndexRouteImport.update({
    id: '/op/products/',
    path: '/op/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpPaymentsIndexRoute =
  AuthenticatedOpPaymentsIndexRouteImport.update({
    id: '/op/payments/',
    path: '/op/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpOrdersIndexRoute =
  AuthenticatedOpOrdersIndexRouteImport.update({
    id: '/op/orders/',
    path: '/op/orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpNotificationsIndexRoute =
  AuthenticatedOpNotificationsIndexRouteImport.update({
    id: '/op/notifications/',
    path: '/op/notifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpMediaIndexRoute =
  AuthenticatedOpMediaIndexRouteImport.update({
    id: '/op/media/',
    path: '/op/media/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpLandingPagesIndexRoute =
  AuthenticatedOpLandingPagesIndexRouteImport.update({
    id: '/op/landing-pages/',
    path: '/op/landing-pages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpInventoryIndexRoute =
  AuthenticatedOpInventoryIndexRouteImport.update({
    id: '/op/inventory/',
    path: '/op/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpImportProductsIndexRoute =
  AuthenticatedOpImportProductsIndexRouteImport.update({
    id: '/op/import-products/',
    path: '/op/import-products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpImportOrdersIndexRoute =
  AuthenticatedOpImportOrdersIndexRouteImport.update({
    id: '/op/import-orders/',
    path: '/op/import-orders/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpHelpCenterIndexRoute =
  AuthenticatedOpHelpCenterIndexRouteImport.update({
    id: '/op/help-center/',
    path: '/op/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpExpensesIndexRoute =
  AuthenticatedOpExpensesIndexRouteImport.update({
    id: '/op/expenses/',
    path: '/op/expenses/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCustomersIndexRoute =
  AuthenticatedOpCustomersIndexRouteImport.update({
    id: '/op/customers/',
    path: '/op/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCouponsIndexRoute =
  AuthenticatedOpCouponsIndexRouteImport.update({
    id: '/op/coupons/',
    path: '/op/coupons/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCombosIndexRoute =
  AuthenticatedOpCombosIndexRouteImport.update({
    id: '/op/combos/',
    path: '/op/combos/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpChatsIndexRoute =
  AuthenticatedOpChatsIndexRouteImport.update({
    id: '/op/chats/',
    path: '/op/chats/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCategoriesIndexRoute =
  AuthenticatedOpCategoriesIndexRouteImport.update({
    id: '/op/categories/',
    path: '/op/categories/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCampaignsIndexRoute =
  AuthenticatedOpCampaignsIndexRouteImport.update({
    id: '/op/campaigns/',
    path: '/op/campaigns/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpBrandsIndexRoute =
  AuthenticatedOpBrandsIndexRouteImport.update({
    id: '/op/brands/',
    path: '/op/brands/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpBlockedIndexRoute =
  AuthenticatedOpBlockedIndexRouteImport.update({
    id: '/op/blocked/',
    path: '/op/blocked/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpAttributesIndexRoute =
  AuthenticatedOpAttributesIndexRouteImport.update({
    id: '/op/attributes/',
    path: '/op/attributes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpAppsIndexRoute =
  AuthenticatedOpAppsIndexRouteImport.update({
    id: '/op/apps/',
    path: '/op/apps/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonUsersIndexRoute =
  AuthenticatedMonUsersIndexRouteImport.update({
    id: '/mon/users/',
    path: '/mon/users/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonPagesIndexRoute =
  AuthenticatedMonPagesIndexRouteImport.update({
    id: '/mon/pages/',
    path: '/mon/pages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonHelpCenterIndexRoute =
  AuthenticatedMonHelpCenterIndexRouteImport.update({
    id: '/mon/help-center/',
    path: '/mon/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonAnalyticsIndexRoute =
  AuthenticatedMonAnalyticsIndexRouteImport.update({
    id: '/mon/analytics/',
    path: '/mon/analytics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonActivityLogsIndexRoute =
  AuthenticatedMonActivityLogsIndexRouteImport.update({
    id: '/mon/activity-logs/',
    path: '/mon/activity-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpOrdersCreateRoute =
  AuthenticatedOpOrdersCreateRouteImport.update({
    id: '/op/orders/create',
    path: '/op/orders/create',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpOrdersIdRoute = AuthenticatedOpOrdersIdRouteImport.update({
  id: '/op/orders/$id',
  path: '/op/orders/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpInventoryValuationRoute =
  AuthenticatedOpInventoryValuationRouteImport.update({
    id: '/op/inventory/valuation',
    path: '/op/inventory/valuation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpInventoryOverviewRoute =
  AuthenticatedOpInventoryOverviewRouteImport.update({
    id: '/op/inventory/overview',
    path: '/op/inventory/overview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpCustomersIdRoute =
  AuthenticatedOpCustomersIdRouteImport.update({
    id: '/op/customers/$id',
    path: '/op/customers/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonUsersIdRoute = AuthenticatedMonUsersIdRouteImport.update({
  id: '/mon/users/$id',
  path: '/mon/users/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpSettingsPersonalIndexRoute =
  AuthenticatedOpSettingsPersonalIndexRouteImport.update({
    id: '/personal/',
    path: '/personal/',
    getParentRoute: () => AuthenticatedOpSettingsRouteRoute,
  } as any)
const AuthenticatedOpPrintBulkIndexRoute =
  AuthenticatedOpPrintBulkIndexRouteImport.update({
    id: '/bulk/',
    path: '/bulk/',
    getParentRoute: () => AuthenticatedOpPrintRouteRoute,
  } as any)
const AuthenticatedOpOrdersIncompleteLeadsIndexRoute =
  AuthenticatedOpOrdersIncompleteLeadsIndexRouteImport.update({
    id: '/op/orders/incomplete-leads/',
    path: '/op/orders/incomplete-leads/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonSettingsTrackingIndexRoute =
  AuthenticatedMonSettingsTrackingIndexRouteImport.update({
    id: '/tracking/',
    path: '/tracking/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsSystemIndexRoute =
  AuthenticatedMonSettingsSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsStorefrontIndexRoute =
  AuthenticatedMonSettingsStorefrontIndexRouteImport.update({
    id: '/storefront/',
    path: '/storefront/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsStorageIndexRoute =
  AuthenticatedMonSettingsStorageIndexRouteImport.update({
    id: '/storage/',
    path: '/storage/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsShippingIndexRoute =
  AuthenticatedMonSettingsShippingIndexRouteImport.update({
    id: '/shipping/',
    path: '/shipping/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsOrderStatusesIndexRoute =
  AuthenticatedMonSettingsOrderStatusesIndexRouteImport.update({
    id: '/order-statuses/',
    path: '/order-statuses/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsMenuIndexRoute =
  AuthenticatedMonSettingsMenuIndexRouteImport.update({
    id: '/menu/',
    path: '/menu/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsHomepageIndexRoute =
  AuthenticatedMonSettingsHomepageIndexRouteImport.update({
    id: '/homepage/',
    path: '/homepage/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsGeneralIndexRoute =
  AuthenticatedMonSettingsGeneralIndexRouteImport.update({
    id: '/general/',
    path: '/general/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsGatewaysIndexRoute =
  AuthenticatedMonSettingsGatewaysIndexRouteImport.update({
    id: '/gateways/',
    path: '/gateways/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsCourierIndexRoute =
  AuthenticatedMonSettingsCourierIndexRouteImport.update({
    id: '/courier/',
    path: '/courier/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedMonSettingsBrandingIndexRoute =
  AuthenticatedMonSettingsBrandingIndexRouteImport.update({
    id: '/branding/',
    path: '/branding/',
    getParentRoute: () => AuthenticatedMonSettingsRouteRoute,
  } as any)
const AuthenticatedOpPrintStickerIdRoute =
  AuthenticatedOpPrintStickerIdRouteImport.update({
    id: '/sticker/$id',
    path: '/sticker/$id',
    getParentRoute: () => AuthenticatedOpPrintRouteRoute,
  } as any)
const AuthenticatedOpPrintInvoiceIdRoute =
  AuthenticatedOpPrintInvoiceIdRouteImport.update({
    id: '/invoice/$id',
    path: '/invoice/$id',
    getParentRoute: () => AuthenticatedOpPrintRouteRoute,
  } as any)
const AuthenticatedOpOrdersIncompleteLeadsIdConvertRoute =
  AuthenticatedOpOrdersIncompleteLeadsIdConvertRouteImport.update({
    id: '/op/orders/incomplete-leads/$id/convert',
    path: '/op/orders/incomplete-leads/$id/convert',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/mon/settings': typeof AuthenticatedMonSettingsRouteRouteWithChildren
  '/op/print': typeof AuthenticatedOpPrintRouteRouteWithChildren
  '/op/settings': typeof AuthenticatedOpSettingsRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/mon/blocking-settings': typeof AuthenticatedMonBlockingSettingsRoute
  '/mon/overview': typeof AuthenticatedMonOverviewRoute
  '/op/overview': typeof AuthenticatedOpOverviewRoute
  '/mon/': typeof AuthenticatedMonIndexRoute
  '/op/': typeof AuthenticatedOpIndexRoute
  '/mon/users/$id': typeof AuthenticatedMonUsersIdRoute
  '/op/customers/$id': typeof AuthenticatedOpCustomersIdRoute
  '/op/inventory/overview': typeof AuthenticatedOpInventoryOverviewRoute
  '/op/inventory/valuation': typeof AuthenticatedOpInventoryValuationRoute
  '/op/orders/$id': typeof AuthenticatedOpOrdersIdRoute
  '/op/orders/create': typeof AuthenticatedOpOrdersCreateRoute
  '/mon/activity-logs/': typeof AuthenticatedMonActivityLogsIndexRoute
  '/mon/analytics/': typeof AuthenticatedMonAnalyticsIndexRoute
  '/mon/help-center/': typeof AuthenticatedMonHelpCenterIndexRoute
  '/mon/pages/': typeof AuthenticatedMonPagesIndexRoute
  '/mon/users/': typeof AuthenticatedMonUsersIndexRoute
  '/op/apps/': typeof AuthenticatedOpAppsIndexRoute
  '/op/attributes/': typeof AuthenticatedOpAttributesIndexRoute
  '/op/blocked/': typeof AuthenticatedOpBlockedIndexRoute
  '/op/brands/': typeof AuthenticatedOpBrandsIndexRoute
  '/op/campaigns/': typeof AuthenticatedOpCampaignsIndexRoute
  '/op/categories/': typeof AuthenticatedOpCategoriesIndexRoute
  '/op/chats/': typeof AuthenticatedOpChatsIndexRoute
  '/op/combos/': typeof AuthenticatedOpCombosIndexRoute
  '/op/coupons/': typeof AuthenticatedOpCouponsIndexRoute
  '/op/customers/': typeof AuthenticatedOpCustomersIndexRoute
  '/op/expenses/': typeof AuthenticatedOpExpensesIndexRoute
  '/op/help-center/': typeof AuthenticatedOpHelpCenterIndexRoute
  '/op/import-orders/': typeof AuthenticatedOpImportOrdersIndexRoute
  '/op/import-products/': typeof AuthenticatedOpImportProductsIndexRoute
  '/op/inventory/': typeof AuthenticatedOpInventoryIndexRoute
  '/op/landing-pages/': typeof AuthenticatedOpLandingPagesIndexRoute
  '/op/media/': typeof AuthenticatedOpMediaIndexRoute
  '/op/notifications/': typeof AuthenticatedOpNotificationsIndexRoute
  '/op/orders/': typeof AuthenticatedOpOrdersIndexRoute
  '/op/payments/': typeof AuthenticatedOpPaymentsIndexRoute
  '/op/products/': typeof AuthenticatedOpProductsIndexRoute
  '/op/purchases/': typeof AuthenticatedOpPurchasesIndexRoute
  '/op/refunds/': typeof AuthenticatedOpRefundsIndexRoute
  '/op/reviews/': typeof AuthenticatedOpReviewsIndexRoute
  '/op/shipments/': typeof AuthenticatedOpShipmentsIndexRoute
  '/op/size-charts/': typeof AuthenticatedOpSizeChartsIndexRoute
  '/op/suppliers/': typeof AuthenticatedOpSuppliersIndexRoute
  '/op/tags/': typeof AuthenticatedOpTagsIndexRoute
  '/op/tasks/': typeof AuthenticatedOpTasksIndexRoute
  '/op/transactions/': typeof AuthenticatedOpTransactionsIndexRoute
  '/op/print/invoice/$id': typeof AuthenticatedOpPrintInvoiceIdRoute
  '/op/print/sticker/$id': typeof AuthenticatedOpPrintStickerIdRoute
  '/mon/settings/branding/': typeof AuthenticatedMonSettingsBrandingIndexRoute
  '/mon/settings/courier/': typeof AuthenticatedMonSettingsCourierIndexRoute
  '/mon/settings/gateways/': typeof AuthenticatedMonSettingsGatewaysIndexRoute
  '/mon/settings/general/': typeof AuthenticatedMonSettingsGeneralIndexRoute
  '/mon/settings/homepage/': typeof AuthenticatedMonSettingsHomepageIndexRoute
  '/mon/settings/menu/': typeof AuthenticatedMonSettingsMenuIndexRoute
  '/mon/settings/order-statuses/': typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  '/mon/settings/shipping/': typeof AuthenticatedMonSettingsShippingIndexRoute
  '/mon/settings/storage/': typeof AuthenticatedMonSettingsStorageIndexRoute
  '/mon/settings/storefront/': typeof AuthenticatedMonSettingsStorefrontIndexRoute
  '/mon/settings/system/': typeof AuthenticatedMonSettingsSystemIndexRoute
  '/mon/settings/tracking/': typeof AuthenticatedMonSettingsTrackingIndexRoute
  '/op/orders/incomplete-leads/': typeof AuthenticatedOpOrdersIncompleteLeadsIndexRoute
  '/op/print/bulk/': typeof AuthenticatedOpPrintBulkIndexRoute
  '/op/settings/personal/': typeof AuthenticatedOpSettingsPersonalIndexRoute
  '/op/orders/incomplete-leads/$id/convert': typeof AuthenticatedOpOrdersIncompleteLeadsIdConvertRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/mon/settings': typeof AuthenticatedMonSettingsRouteRouteWithChildren
  '/op/print': typeof AuthenticatedOpPrintRouteRouteWithChildren
  '/op/settings': typeof AuthenticatedOpSettingsRouteRouteWithChildren
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/mon/blocking-settings': typeof AuthenticatedMonBlockingSettingsRoute
  '/mon/overview': typeof AuthenticatedMonOverviewRoute
  '/op/overview': typeof AuthenticatedOpOverviewRoute
  '/mon': typeof AuthenticatedMonIndexRoute
  '/op': typeof AuthenticatedOpIndexRoute
  '/mon/users/$id': typeof AuthenticatedMonUsersIdRoute
  '/op/customers/$id': typeof AuthenticatedOpCustomersIdRoute
  '/op/inventory/overview': typeof AuthenticatedOpInventoryOverviewRoute
  '/op/inventory/valuation': typeof AuthenticatedOpInventoryValuationRoute
  '/op/orders/$id': typeof AuthenticatedOpOrdersIdRoute
  '/op/orders/create': typeof AuthenticatedOpOrdersCreateRoute
  '/mon/activity-logs': typeof AuthenticatedMonActivityLogsIndexRoute
  '/mon/analytics': typeof AuthenticatedMonAnalyticsIndexRoute
  '/mon/help-center': typeof AuthenticatedMonHelpCenterIndexRoute
  '/mon/pages': typeof AuthenticatedMonPagesIndexRoute
  '/mon/users': typeof AuthenticatedMonUsersIndexRoute
  '/op/apps': typeof AuthenticatedOpAppsIndexRoute
  '/op/attributes': typeof AuthenticatedOpAttributesIndexRoute
  '/op/blocked': typeof AuthenticatedOpBlockedIndexRoute
  '/op/brands': typeof AuthenticatedOpBrandsIndexRoute
  '/op/campaigns': typeof AuthenticatedOpCampaignsIndexRoute
  '/op/categories': typeof AuthenticatedOpCategoriesIndexRoute
  '/op/chats': typeof AuthenticatedOpChatsIndexRoute
  '/op/combos': typeof AuthenticatedOpCombosIndexRoute
  '/op/coupons': typeof AuthenticatedOpCouponsIndexRoute
  '/op/customers': typeof AuthenticatedOpCustomersIndexRoute
  '/op/expenses': typeof AuthenticatedOpExpensesIndexRoute
  '/op/help-center': typeof AuthenticatedOpHelpCenterIndexRoute
  '/op/import-orders': typeof AuthenticatedOpImportOrdersIndexRoute
  '/op/import-products': typeof AuthenticatedOpImportProductsIndexRoute
  '/op/inventory': typeof AuthenticatedOpInventoryIndexRoute
  '/op/landing-pages': typeof AuthenticatedOpLandingPagesIndexRoute
  '/op/media': typeof AuthenticatedOpMediaIndexRoute
  '/op/notifications': typeof AuthenticatedOpNotificationsIndexRoute
  '/op/orders': typeof AuthenticatedOpOrdersIndexRoute
  '/op/payments': typeof AuthenticatedOpPaymentsIndexRoute
  '/op/products': typeof AuthenticatedOpProductsIndexRoute
  '/op/purchases': typeof AuthenticatedOpPurchasesIndexRoute
  '/op/refunds': typeof AuthenticatedOpRefundsIndexRoute
  '/op/reviews': typeof AuthenticatedOpReviewsIndexRoute
  '/op/shipments': typeof AuthenticatedOpShipmentsIndexRoute
  '/op/size-charts': typeof AuthenticatedOpSizeChartsIndexRoute
  '/op/suppliers': typeof AuthenticatedOpSuppliersIndexRoute
  '/op/tags': typeof AuthenticatedOpTagsIndexRoute
  '/op/tasks': typeof AuthenticatedOpTasksIndexRoute
  '/op/transactions': typeof AuthenticatedOpTransactionsIndexRoute
  '/op/print/invoice/$id': typeof AuthenticatedOpPrintInvoiceIdRoute
  '/op/print/sticker/$id': typeof AuthenticatedOpPrintStickerIdRoute
  '/mon/settings/branding': typeof AuthenticatedMonSettingsBrandingIndexRoute
  '/mon/settings/courier': typeof AuthenticatedMonSettingsCourierIndexRoute
  '/mon/settings/gateways': typeof AuthenticatedMonSettingsGatewaysIndexRoute
  '/mon/settings/general': typeof AuthenticatedMonSettingsGeneralIndexRoute
  '/mon/settings/homepage': typeof AuthenticatedMonSettingsHomepageIndexRoute
  '/mon/settings/menu': typeof AuthenticatedMonSettingsMenuIndexRoute
  '/mon/settings/order-statuses': typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  '/mon/settings/shipping': typeof AuthenticatedMonSettingsShippingIndexRoute
  '/mon/settings/storage': typeof AuthenticatedMonSettingsStorageIndexRoute
  '/mon/settings/storefront': typeof AuthenticatedMonSettingsStorefrontIndexRoute
  '/mon/settings/system': typeof AuthenticatedMonSettingsSystemIndexRoute
  '/mon/settings/tracking': typeof AuthenticatedMonSettingsTrackingIndexRoute
  '/op/orders/incomplete-leads': typeof AuthenticatedOpOrdersIncompleteLeadsIndexRoute
  '/op/print/bulk': typeof AuthenticatedOpPrintBulkIndexRoute
  '/op/settings/personal': typeof AuthenticatedOpSettingsPersonalIndexRoute
  '/op/orders/incomplete-leads/$id/convert': typeof AuthenticatedOpOrdersIncompleteLeadsIdConvertRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/mon/settings': typeof AuthenticatedMonSettingsRouteRouteWithChildren
  '/_authenticated/op/print': typeof AuthenticatedOpPrintRouteRouteWithChildren
  '/_authenticated/op/settings': typeof AuthenticatedOpSettingsRouteRouteWithChildren
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/mon/blocking-settings': typeof AuthenticatedMonBlockingSettingsRoute
  '/_authenticated/mon/overview': typeof AuthenticatedMonOverviewRoute
  '/_authenticated/op/overview': typeof AuthenticatedOpOverviewRoute
  '/_authenticated/mon/': typeof AuthenticatedMonIndexRoute
  '/_authenticated/op/': typeof AuthenticatedOpIndexRoute
  '/_authenticated/mon/users/$id': typeof AuthenticatedMonUsersIdRoute
  '/_authenticated/op/customers/$id': typeof AuthenticatedOpCustomersIdRoute
  '/_authenticated/op/inventory/overview': typeof AuthenticatedOpInventoryOverviewRoute
  '/_authenticated/op/inventory/valuation': typeof AuthenticatedOpInventoryValuationRoute
  '/_authenticated/op/orders/$id': typeof AuthenticatedOpOrdersIdRoute
  '/_authenticated/op/orders/create': typeof AuthenticatedOpOrdersCreateRoute
  '/_authenticated/mon/activity-logs/': typeof AuthenticatedMonActivityLogsIndexRoute
  '/_authenticated/mon/analytics/': typeof AuthenticatedMonAnalyticsIndexRoute
  '/_authenticated/mon/help-center/': typeof AuthenticatedMonHelpCenterIndexRoute
  '/_authenticated/mon/pages/': typeof AuthenticatedMonPagesIndexRoute
  '/_authenticated/mon/users/': typeof AuthenticatedMonUsersIndexRoute
  '/_authenticated/op/apps/': typeof AuthenticatedOpAppsIndexRoute
  '/_authenticated/op/attributes/': typeof AuthenticatedOpAttributesIndexRoute
  '/_authenticated/op/blocked/': typeof AuthenticatedOpBlockedIndexRoute
  '/_authenticated/op/brands/': typeof AuthenticatedOpBrandsIndexRoute
  '/_authenticated/op/campaigns/': typeof AuthenticatedOpCampaignsIndexRoute
  '/_authenticated/op/categories/': typeof AuthenticatedOpCategoriesIndexRoute
  '/_authenticated/op/chats/': typeof AuthenticatedOpChatsIndexRoute
  '/_authenticated/op/combos/': typeof AuthenticatedOpCombosIndexRoute
  '/_authenticated/op/coupons/': typeof AuthenticatedOpCouponsIndexRoute
  '/_authenticated/op/customers/': typeof AuthenticatedOpCustomersIndexRoute
  '/_authenticated/op/expenses/': typeof AuthenticatedOpExpensesIndexRoute
  '/_authenticated/op/help-center/': typeof AuthenticatedOpHelpCenterIndexRoute
  '/_authenticated/op/import-orders/': typeof AuthenticatedOpImportOrdersIndexRoute
  '/_authenticated/op/import-products/': typeof AuthenticatedOpImportProductsIndexRoute
  '/_authenticated/op/inventory/': typeof AuthenticatedOpInventoryIndexRoute
  '/_authenticated/op/landing-pages/': typeof AuthenticatedOpLandingPagesIndexRoute
  '/_authenticated/op/media/': typeof AuthenticatedOpMediaIndexRoute
  '/_authenticated/op/notifications/': typeof AuthenticatedOpNotificationsIndexRoute
  '/_authenticated/op/orders/': typeof AuthenticatedOpOrdersIndexRoute
  '/_authenticated/op/payments/': typeof AuthenticatedOpPaymentsIndexRoute
  '/_authenticated/op/products/': typeof AuthenticatedOpProductsIndexRoute
  '/_authenticated/op/purchases/': typeof AuthenticatedOpPurchasesIndexRoute
  '/_authenticated/op/refunds/': typeof AuthenticatedOpRefundsIndexRoute
  '/_authenticated/op/reviews/': typeof AuthenticatedOpReviewsIndexRoute
  '/_authenticated/op/shipments/': typeof AuthenticatedOpShipmentsIndexRoute
  '/_authenticated/op/size-charts/': typeof AuthenticatedOpSizeChartsIndexRoute
  '/_authenticated/op/suppliers/': typeof AuthenticatedOpSuppliersIndexRoute
  '/_authenticated/op/tags/': typeof AuthenticatedOpTagsIndexRoute
  '/_authenticated/op/tasks/': typeof AuthenticatedOpTasksIndexRoute
  '/_authenticated/op/transactions/': typeof AuthenticatedOpTransactionsIndexRoute
  '/_authenticated/op/print/invoice/$id': typeof AuthenticatedOpPrintInvoiceIdRoute
  '/_authenticated/op/print/sticker/$id': typeof AuthenticatedOpPrintStickerIdRoute
  '/_authenticated/mon/settings/branding/': typeof AuthenticatedMonSettingsBrandingIndexRoute
  '/_authenticated/mon/settings/courier/': typeof AuthenticatedMonSettingsCourierIndexRoute
  '/_authenticated/mon/settings/gateways/': typeof AuthenticatedMonSettingsGatewaysIndexRoute
  '/_authenticated/mon/settings/general/': typeof AuthenticatedMonSettingsGeneralIndexRoute
  '/_authenticated/mon/settings/homepage/': typeof AuthenticatedMonSettingsHomepageIndexRoute
  '/_authenticated/mon/settings/menu/': typeof AuthenticatedMonSettingsMenuIndexRoute
  '/_authenticated/mon/settings/order-statuses/': typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  '/_authenticated/mon/settings/shipping/': typeof AuthenticatedMonSettingsShippingIndexRoute
  '/_authenticated/mon/settings/storage/': typeof AuthenticatedMonSettingsStorageIndexRoute
  '/_authenticated/mon/settings/storefront/': typeof AuthenticatedMonSettingsStorefrontIndexRoute
  '/_authenticated/mon/settings/system/': typeof AuthenticatedMonSettingsSystemIndexRoute
  '/_authenticated/mon/settings/tracking/': typeof AuthenticatedMonSettingsTrackingIndexRoute
  '/_authenticated/op/orders/incomplete-leads/': typeof AuthenticatedOpOrdersIncompleteLeadsIndexRoute
  '/_authenticated/op/print/bulk/': typeof AuthenticatedOpPrintBulkIndexRoute
  '/_authenticated/op/settings/personal/': typeof AuthenticatedOpSettingsPersonalIndexRoute
  '/_authenticated/op/orders/incomplete-leads/$id/convert': typeof AuthenticatedOpOrdersIncompleteLeadsIdConvertRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/mon/settings'
    | '/op/print'
    | '/op/settings'
    | '/errors/$error'
    | '/mon/blocking-settings'
    | '/mon/overview'
    | '/op/overview'
    | '/mon/'
    | '/op/'
    | '/mon/users/$id'
    | '/op/customers/$id'
    | '/op/inventory/overview'
    | '/op/inventory/valuation'
    | '/op/orders/$id'
    | '/op/orders/create'
    | '/mon/activity-logs/'
    | '/mon/analytics/'
    | '/mon/help-center/'
    | '/mon/pages/'
    | '/mon/users/'
    | '/op/apps/'
    | '/op/attributes/'
    | '/op/blocked/'
    | '/op/brands/'
    | '/op/campaigns/'
    | '/op/categories/'
    | '/op/chats/'
    | '/op/combos/'
    | '/op/coupons/'
    | '/op/customers/'
    | '/op/expenses/'
    | '/op/help-center/'
    | '/op/import-orders/'
    | '/op/import-products/'
    | '/op/inventory/'
    | '/op/landing-pages/'
    | '/op/media/'
    | '/op/notifications/'
    | '/op/orders/'
    | '/op/payments/'
    | '/op/products/'
    | '/op/purchases/'
    | '/op/refunds/'
    | '/op/reviews/'
    | '/op/shipments/'
    | '/op/size-charts/'
    | '/op/suppliers/'
    | '/op/tags/'
    | '/op/tasks/'
    | '/op/transactions/'
    | '/op/print/invoice/$id'
    | '/op/print/sticker/$id'
    | '/mon/settings/branding/'
    | '/mon/settings/courier/'
    | '/mon/settings/gateways/'
    | '/mon/settings/general/'
    | '/mon/settings/homepage/'
    | '/mon/settings/menu/'
    | '/mon/settings/order-statuses/'
    | '/mon/settings/shipping/'
    | '/mon/settings/storage/'
    | '/mon/settings/storefront/'
    | '/mon/settings/system/'
    | '/mon/settings/tracking/'
    | '/op/orders/incomplete-leads/'
    | '/op/print/bulk/'
    | '/op/settings/personal/'
    | '/op/orders/incomplete-leads/$id/convert'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/mon/settings'
    | '/op/print'
    | '/op/settings'
    | '/errors/$error'
    | '/mon/blocking-settings'
    | '/mon/overview'
    | '/op/overview'
    | '/mon'
    | '/op'
    | '/mon/users/$id'
    | '/op/customers/$id'
    | '/op/inventory/overview'
    | '/op/inventory/valuation'
    | '/op/orders/$id'
    | '/op/orders/create'
    | '/mon/activity-logs'
    | '/mon/analytics'
    | '/mon/help-center'
    | '/mon/pages'
    | '/mon/users'
    | '/op/apps'
    | '/op/attributes'
    | '/op/blocked'
    | '/op/brands'
    | '/op/campaigns'
    | '/op/categories'
    | '/op/chats'
    | '/op/combos'
    | '/op/coupons'
    | '/op/customers'
    | '/op/expenses'
    | '/op/help-center'
    | '/op/import-orders'
    | '/op/import-products'
    | '/op/inventory'
    | '/op/landing-pages'
    | '/op/media'
    | '/op/notifications'
    | '/op/orders'
    | '/op/payments'
    | '/op/products'
    | '/op/purchases'
    | '/op/refunds'
    | '/op/reviews'
    | '/op/shipments'
    | '/op/size-charts'
    | '/op/suppliers'
    | '/op/tags'
    | '/op/tasks'
    | '/op/transactions'
    | '/op/print/invoice/$id'
    | '/op/print/sticker/$id'
    | '/mon/settings/branding'
    | '/mon/settings/courier'
    | '/mon/settings/gateways'
    | '/mon/settings/general'
    | '/mon/settings/homepage'
    | '/mon/settings/menu'
    | '/mon/settings/order-statuses'
    | '/mon/settings/shipping'
    | '/mon/settings/storage'
    | '/mon/settings/storefront'
    | '/mon/settings/system'
    | '/mon/settings/tracking'
    | '/op/orders/incomplete-leads'
    | '/op/print/bulk'
    | '/op/settings/personal'
    | '/op/orders/incomplete-leads/$id/convert'
  id:
    | '__root__'
    | '/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/mon/settings'
    | '/_authenticated/op/print'
    | '/_authenticated/op/settings'
    | '/_authenticated/errors/$error'
    | '/_authenticated/mon/blocking-settings'
    | '/_authenticated/mon/overview'
    | '/_authenticated/op/overview'
    | '/_authenticated/mon/'
    | '/_authenticated/op/'
    | '/_authenticated/mon/users/$id'
    | '/_authenticated/op/customers/$id'
    | '/_authenticated/op/inventory/overview'
    | '/_authenticated/op/inventory/valuation'
    | '/_authenticated/op/orders/$id'
    | '/_authenticated/op/orders/create'
    | '/_authenticated/mon/activity-logs/'
    | '/_authenticated/mon/analytics/'
    | '/_authenticated/mon/help-center/'
    | '/_authenticated/mon/pages/'
    | '/_authenticated/mon/users/'
    | '/_authenticated/op/apps/'
    | '/_authenticated/op/attributes/'
    | '/_authenticated/op/blocked/'
    | '/_authenticated/op/brands/'
    | '/_authenticated/op/campaigns/'
    | '/_authenticated/op/categories/'
    | '/_authenticated/op/chats/'
    | '/_authenticated/op/combos/'
    | '/_authenticated/op/coupons/'
    | '/_authenticated/op/customers/'
    | '/_authenticated/op/expenses/'
    | '/_authenticated/op/help-center/'
    | '/_authenticated/op/import-orders/'
    | '/_authenticated/op/import-products/'
    | '/_authenticated/op/inventory/'
    | '/_authenticated/op/landing-pages/'
    | '/_authenticated/op/media/'
    | '/_authenticated/op/notifications/'
    | '/_authenticated/op/orders/'
    | '/_authenticated/op/payments/'
    | '/_authenticated/op/products/'
    | '/_authenticated/op/purchases/'
    | '/_authenticated/op/refunds/'
    | '/_authenticated/op/reviews/'
    | '/_authenticated/op/shipments/'
    | '/_authenticated/op/size-charts/'
    | '/_authenticated/op/suppliers/'
    | '/_authenticated/op/tags/'
    | '/_authenticated/op/tasks/'
    | '/_authenticated/op/transactions/'
    | '/_authenticated/op/print/invoice/$id'
    | '/_authenticated/op/print/sticker/$id'
    | '/_authenticated/mon/settings/branding/'
    | '/_authenticated/mon/settings/courier/'
    | '/_authenticated/mon/settings/gateways/'
    | '/_authenticated/mon/settings/general/'
    | '/_authenticated/mon/settings/homepage/'
    | '/_authenticated/mon/settings/menu/'
    | '/_authenticated/mon/settings/order-statuses/'
    | '/_authenticated/mon/settings/shipping/'
    | '/_authenticated/mon/settings/storage/'
    | '/_authenticated/mon/settings/storefront/'
    | '/_authenticated/mon/settings/system/'
    | '/_authenticated/mon/settings/tracking/'
    | '/_authenticated/op/orders/incomplete-leads/'
    | '/_authenticated/op/print/bulk/'
    | '/_authenticated/op/settings/personal/'
    | '/_authenticated/op/orders/incomplete-leads/$id/convert'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/op/': {
      id: '/_authenticated/op/'
      path: '/op'
      fullPath: '/op/'
      preLoaderRoute: typeof AuthenticatedOpIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/': {
      id: '/_authenticated/mon/'
      path: '/mon'
      fullPath: '/mon/'
      preLoaderRoute: typeof AuthenticatedMonIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/overview': {
      id: '/_authenticated/op/overview'
      path: '/op/overview'
      fullPath: '/op/overview'
      preLoaderRoute: typeof AuthenticatedOpOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/overview': {
      id: '/_authenticated/mon/overview'
      path: '/mon/overview'
      fullPath: '/mon/overview'
      preLoaderRoute: typeof AuthenticatedMonOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/blocking-settings': {
      id: '/_authenticated/mon/blocking-settings'
      path: '/mon/blocking-settings'
      fullPath: '/mon/blocking-settings'
      preLoaderRoute: typeof AuthenticatedMonBlockingSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/settings': {
      id: '/_authenticated/op/settings'
      path: '/op/settings'
      fullPath: '/op/settings'
      preLoaderRoute: typeof AuthenticatedOpSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/print': {
      id: '/_authenticated/op/print'
      path: '/op/print'
      fullPath: '/op/print'
      preLoaderRoute: typeof AuthenticatedOpPrintRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/settings': {
      id: '/_authenticated/mon/settings'
      path: '/mon/settings'
      fullPath: '/mon/settings'
      preLoaderRoute: typeof AuthenticatedMonSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/transactions/': {
      id: '/_authenticated/op/transactions/'
      path: '/op/transactions'
      fullPath: '/op/transactions/'
      preLoaderRoute: typeof AuthenticatedOpTransactionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/tasks/': {
      id: '/_authenticated/op/tasks/'
      path: '/op/tasks'
      fullPath: '/op/tasks/'
      preLoaderRoute: typeof AuthenticatedOpTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/tags/': {
      id: '/_authenticated/op/tags/'
      path: '/op/tags'
      fullPath: '/op/tags/'
      preLoaderRoute: typeof AuthenticatedOpTagsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/suppliers/': {
      id: '/_authenticated/op/suppliers/'
      path: '/op/suppliers'
      fullPath: '/op/suppliers/'
      preLoaderRoute: typeof AuthenticatedOpSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/size-charts/': {
      id: '/_authenticated/op/size-charts/'
      path: '/op/size-charts'
      fullPath: '/op/size-charts/'
      preLoaderRoute: typeof AuthenticatedOpSizeChartsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/shipments/': {
      id: '/_authenticated/op/shipments/'
      path: '/op/shipments'
      fullPath: '/op/shipments/'
      preLoaderRoute: typeof AuthenticatedOpShipmentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/reviews/': {
      id: '/_authenticated/op/reviews/'
      path: '/op/reviews'
      fullPath: '/op/reviews/'
      preLoaderRoute: typeof AuthenticatedOpReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/refunds/': {
      id: '/_authenticated/op/refunds/'
      path: '/op/refunds'
      fullPath: '/op/refunds/'
      preLoaderRoute: typeof AuthenticatedOpRefundsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/purchases/': {
      id: '/_authenticated/op/purchases/'
      path: '/op/purchases'
      fullPath: '/op/purchases/'
      preLoaderRoute: typeof AuthenticatedOpPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/products/': {
      id: '/_authenticated/op/products/'
      path: '/op/products'
      fullPath: '/op/products/'
      preLoaderRoute: typeof AuthenticatedOpProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/payments/': {
      id: '/_authenticated/op/payments/'
      path: '/op/payments'
      fullPath: '/op/payments/'
      preLoaderRoute: typeof AuthenticatedOpPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/orders/': {
      id: '/_authenticated/op/orders/'
      path: '/op/orders'
      fullPath: '/op/orders/'
      preLoaderRoute: typeof AuthenticatedOpOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/notifications/': {
      id: '/_authenticated/op/notifications/'
      path: '/op/notifications'
      fullPath: '/op/notifications/'
      preLoaderRoute: typeof AuthenticatedOpNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/media/': {
      id: '/_authenticated/op/media/'
      path: '/op/media'
      fullPath: '/op/media/'
      preLoaderRoute: typeof AuthenticatedOpMediaIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/landing-pages/': {
      id: '/_authenticated/op/landing-pages/'
      path: '/op/landing-pages'
      fullPath: '/op/landing-pages/'
      preLoaderRoute: typeof AuthenticatedOpLandingPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/inventory/': {
      id: '/_authenticated/op/inventory/'
      path: '/op/inventory'
      fullPath: '/op/inventory/'
      preLoaderRoute: typeof AuthenticatedOpInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/import-products/': {
      id: '/_authenticated/op/import-products/'
      path: '/op/import-products'
      fullPath: '/op/import-products/'
      preLoaderRoute: typeof AuthenticatedOpImportProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/import-orders/': {
      id: '/_authenticated/op/import-orders/'
      path: '/op/import-orders'
      fullPath: '/op/import-orders/'
      preLoaderRoute: typeof AuthenticatedOpImportOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/help-center/': {
      id: '/_authenticated/op/help-center/'
      path: '/op/help-center'
      fullPath: '/op/help-center/'
      preLoaderRoute: typeof AuthenticatedOpHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/expenses/': {
      id: '/_authenticated/op/expenses/'
      path: '/op/expenses'
      fullPath: '/op/expenses/'
      preLoaderRoute: typeof AuthenticatedOpExpensesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/customers/': {
      id: '/_authenticated/op/customers/'
      path: '/op/customers'
      fullPath: '/op/customers/'
      preLoaderRoute: typeof AuthenticatedOpCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/coupons/': {
      id: '/_authenticated/op/coupons/'
      path: '/op/coupons'
      fullPath: '/op/coupons/'
      preLoaderRoute: typeof AuthenticatedOpCouponsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/combos/': {
      id: '/_authenticated/op/combos/'
      path: '/op/combos'
      fullPath: '/op/combos/'
      preLoaderRoute: typeof AuthenticatedOpCombosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/chats/': {
      id: '/_authenticated/op/chats/'
      path: '/op/chats'
      fullPath: '/op/chats/'
      preLoaderRoute: typeof AuthenticatedOpChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/categories/': {
      id: '/_authenticated/op/categories/'
      path: '/op/categories'
      fullPath: '/op/categories/'
      preLoaderRoute: typeof AuthenticatedOpCategoriesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/campaigns/': {
      id: '/_authenticated/op/campaigns/'
      path: '/op/campaigns'
      fullPath: '/op/campaigns/'
      preLoaderRoute: typeof AuthenticatedOpCampaignsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/brands/': {
      id: '/_authenticated/op/brands/'
      path: '/op/brands'
      fullPath: '/op/brands/'
      preLoaderRoute: typeof AuthenticatedOpBrandsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/blocked/': {
      id: '/_authenticated/op/blocked/'
      path: '/op/blocked'
      fullPath: '/op/blocked/'
      preLoaderRoute: typeof AuthenticatedOpBlockedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/attributes/': {
      id: '/_authenticated/op/attributes/'
      path: '/op/attributes'
      fullPath: '/op/attributes/'
      preLoaderRoute: typeof AuthenticatedOpAttributesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/apps/': {
      id: '/_authenticated/op/apps/'
      path: '/op/apps'
      fullPath: '/op/apps/'
      preLoaderRoute: typeof AuthenticatedOpAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/users/': {
      id: '/_authenticated/mon/users/'
      path: '/mon/users'
      fullPath: '/mon/users/'
      preLoaderRoute: typeof AuthenticatedMonUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/pages/': {
      id: '/_authenticated/mon/pages/'
      path: '/mon/pages'
      fullPath: '/mon/pages/'
      preLoaderRoute: typeof AuthenticatedMonPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/help-center/': {
      id: '/_authenticated/mon/help-center/'
      path: '/mon/help-center'
      fullPath: '/mon/help-center/'
      preLoaderRoute: typeof AuthenticatedMonHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/analytics/': {
      id: '/_authenticated/mon/analytics/'
      path: '/mon/analytics'
      fullPath: '/mon/analytics/'
      preLoaderRoute: typeof AuthenticatedMonAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/activity-logs/': {
      id: '/_authenticated/mon/activity-logs/'
      path: '/mon/activity-logs'
      fullPath: '/mon/activity-logs/'
      preLoaderRoute: typeof AuthenticatedMonActivityLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/orders/create': {
      id: '/_authenticated/op/orders/create'
      path: '/op/orders/create'
      fullPath: '/op/orders/create'
      preLoaderRoute: typeof AuthenticatedOpOrdersCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/orders/$id': {
      id: '/_authenticated/op/orders/$id'
      path: '/op/orders/$id'
      fullPath: '/op/orders/$id'
      preLoaderRoute: typeof AuthenticatedOpOrdersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/inventory/valuation': {
      id: '/_authenticated/op/inventory/valuation'
      path: '/op/inventory/valuation'
      fullPath: '/op/inventory/valuation'
      preLoaderRoute: typeof AuthenticatedOpInventoryValuationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/inventory/overview': {
      id: '/_authenticated/op/inventory/overview'
      path: '/op/inventory/overview'
      fullPath: '/op/inventory/overview'
      preLoaderRoute: typeof AuthenticatedOpInventoryOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/customers/$id': {
      id: '/_authenticated/op/customers/$id'
      path: '/op/customers/$id'
      fullPath: '/op/customers/$id'
      preLoaderRoute: typeof AuthenticatedOpCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/users/$id': {
      id: '/_authenticated/mon/users/$id'
      path: '/mon/users/$id'
      fullPath: '/mon/users/$id'
      preLoaderRoute: typeof AuthenticatedMonUsersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/op/settings/personal/': {
      id: '/_authenticated/op/settings/personal/'
      path: '/personal'
      fullPath: '/op/settings/personal/'
      preLoaderRoute: typeof AuthenticatedOpSettingsPersonalIndexRouteImport
      parentRoute: typeof AuthenticatedOpSettingsRouteRoute
    }
    '/_authenticated/op/print/bulk/': {
      id: '/_authenticated/op/print/bulk/'
      path: '/bulk'
      fullPath: '/op/print/bulk/'
      preLoaderRoute: typeof AuthenticatedOpPrintBulkIndexRouteImport
      parentRoute: typeof AuthenticatedOpPrintRouteRoute
    }
    '/_authenticated/op/orders/incomplete-leads/': {
      id: '/_authenticated/op/orders/incomplete-leads/'
      path: '/op/orders/incomplete-leads'
      fullPath: '/op/orders/incomplete-leads/'
      preLoaderRoute: typeof AuthenticatedOpOrdersIncompleteLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon/settings/tracking/': {
      id: '/_authenticated/mon/settings/tracking/'
      path: '/tracking'
      fullPath: '/mon/settings/tracking/'
      preLoaderRoute: typeof AuthenticatedMonSettingsTrackingIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/system/': {
      id: '/_authenticated/mon/settings/system/'
      path: '/system'
      fullPath: '/mon/settings/system/'
      preLoaderRoute: typeof AuthenticatedMonSettingsSystemIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/storefront/': {
      id: '/_authenticated/mon/settings/storefront/'
      path: '/storefront'
      fullPath: '/mon/settings/storefront/'
      preLoaderRoute: typeof AuthenticatedMonSettingsStorefrontIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/storage/': {
      id: '/_authenticated/mon/settings/storage/'
      path: '/storage'
      fullPath: '/mon/settings/storage/'
      preLoaderRoute: typeof AuthenticatedMonSettingsStorageIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/shipping/': {
      id: '/_authenticated/mon/settings/shipping/'
      path: '/shipping'
      fullPath: '/mon/settings/shipping/'
      preLoaderRoute: typeof AuthenticatedMonSettingsShippingIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/order-statuses/': {
      id: '/_authenticated/mon/settings/order-statuses/'
      path: '/order-statuses'
      fullPath: '/mon/settings/order-statuses/'
      preLoaderRoute: typeof AuthenticatedMonSettingsOrderStatusesIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/menu/': {
      id: '/_authenticated/mon/settings/menu/'
      path: '/menu'
      fullPath: '/mon/settings/menu/'
      preLoaderRoute: typeof AuthenticatedMonSettingsMenuIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/homepage/': {
      id: '/_authenticated/mon/settings/homepage/'
      path: '/homepage'
      fullPath: '/mon/settings/homepage/'
      preLoaderRoute: typeof AuthenticatedMonSettingsHomepageIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/general/': {
      id: '/_authenticated/mon/settings/general/'
      path: '/general'
      fullPath: '/mon/settings/general/'
      preLoaderRoute: typeof AuthenticatedMonSettingsGeneralIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/gateways/': {
      id: '/_authenticated/mon/settings/gateways/'
      path: '/gateways'
      fullPath: '/mon/settings/gateways/'
      preLoaderRoute: typeof AuthenticatedMonSettingsGatewaysIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/courier/': {
      id: '/_authenticated/mon/settings/courier/'
      path: '/courier'
      fullPath: '/mon/settings/courier/'
      preLoaderRoute: typeof AuthenticatedMonSettingsCourierIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/mon/settings/branding/': {
      id: '/_authenticated/mon/settings/branding/'
      path: '/branding'
      fullPath: '/mon/settings/branding/'
      preLoaderRoute: typeof AuthenticatedMonSettingsBrandingIndexRouteImport
      parentRoute: typeof AuthenticatedMonSettingsRouteRoute
    }
    '/_authenticated/op/print/sticker/$id': {
      id: '/_authenticated/op/print/sticker/$id'
      path: '/sticker/$id'
      fullPath: '/op/print/sticker/$id'
      preLoaderRoute: typeof AuthenticatedOpPrintStickerIdRouteImport
      parentRoute: typeof AuthenticatedOpPrintRouteRoute
    }
    '/_authenticated/op/print/invoice/$id': {
      id: '/_authenticated/op/print/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/op/print/invoice/$id'
      preLoaderRoute: typeof AuthenticatedOpPrintInvoiceIdRouteImport
      parentRoute: typeof AuthenticatedOpPrintRouteRoute
    }
    '/_authenticated/op/orders/incomplete-leads/$id/convert': {
      id: '/_authenticated/op/orders/incomplete-leads/$id/convert'
      path: '/op/orders/incomplete-leads/$id/convert'
      fullPath: '/op/orders/incomplete-leads/$id/convert'
      preLoaderRoute: typeof AuthenticatedOpOrdersIncompleteLeadsIdConvertRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedMonSettingsRouteRouteChildren {
  AuthenticatedMonSettingsBrandingIndexRoute: typeof AuthenticatedMonSettingsBrandingIndexRoute
  AuthenticatedMonSettingsCourierIndexRoute: typeof AuthenticatedMonSettingsCourierIndexRoute
  AuthenticatedMonSettingsGatewaysIndexRoute: typeof AuthenticatedMonSettingsGatewaysIndexRoute
  AuthenticatedMonSettingsGeneralIndexRoute: typeof AuthenticatedMonSettingsGeneralIndexRoute
  AuthenticatedMonSettingsHomepageIndexRoute: typeof AuthenticatedMonSettingsHomepageIndexRoute
  AuthenticatedMonSettingsMenuIndexRoute: typeof AuthenticatedMonSettingsMenuIndexRoute
  AuthenticatedMonSettingsOrderStatusesIndexRoute: typeof AuthenticatedMonSettingsOrderStatusesIndexRoute
  AuthenticatedMonSettingsShippingIndexRoute: typeof AuthenticatedMonSettingsShippingIndexRoute
  AuthenticatedMonSettingsStorageIndexRoute: typeof AuthenticatedMonSettingsStorageIndexRoute
  AuthenticatedMonSettingsStorefrontIndexRoute: typeof AuthenticatedMonSettingsStorefrontIndexRoute
  AuthenticatedMonSettingsSystemIndexRoute: typeof AuthenticatedMonSettingsSystemIndexRoute
  AuthenticatedMonSettingsTrackingIndexRoute: typeof AuthenticatedMonSettingsTrackingIndexRoute
}

const AuthenticatedMonSettingsRouteRouteChildren: AuthenticatedMonSettingsRouteRouteChildren =
  {
    AuthenticatedMonSettingsBrandingIndexRoute:
      AuthenticatedMonSettingsBrandingIndexRoute,
    AuthenticatedMonSettingsCourierIndexRoute:
      AuthenticatedMonSettingsCourierIndexRoute,
    AuthenticatedMonSettingsGatewaysIndexRoute:
      AuthenticatedMonSettingsGatewaysIndexRoute,
    AuthenticatedMonSettingsGeneralIndexRoute:
      AuthenticatedMonSettingsGeneralIndexRoute,
    AuthenticatedMonSettingsHomepageIndexRoute:
      AuthenticatedMonSettingsHomepageIndexRoute,
    AuthenticatedMonSettingsMenuIndexRoute:
      AuthenticatedMonSettingsMenuIndexRoute,
    AuthenticatedMonSettingsOrderStatusesIndexRoute:
      AuthenticatedMonSettingsOrderStatusesIndexRoute,
    AuthenticatedMonSettingsShippingIndexRoute:
      AuthenticatedMonSettingsShippingIndexRoute,
    AuthenticatedMonSettingsStorageIndexRoute:
      AuthenticatedMonSettingsStorageIndexRoute,
    AuthenticatedMonSettingsStorefrontIndexRoute:
      AuthenticatedMonSettingsStorefrontIndexRoute,
    AuthenticatedMonSettingsSystemIndexRoute:
      AuthenticatedMonSettingsSystemIndexRoute,
    AuthenticatedMonSettingsTrackingIndexRoute:
      AuthenticatedMonSettingsTrackingIndexRoute,
  }

const AuthenticatedMonSettingsRouteRouteWithChildren =
  AuthenticatedMonSettingsRouteRoute._addFileChildren(
    AuthenticatedMonSettingsRouteRouteChildren,
  )

interface AuthenticatedOpPrintRouteRouteChildren {
  AuthenticatedOpPrintInvoiceIdRoute: typeof AuthenticatedOpPrintInvoiceIdRoute
  AuthenticatedOpPrintStickerIdRoute: typeof AuthenticatedOpPrintStickerIdRoute
  AuthenticatedOpPrintBulkIndexRoute: typeof AuthenticatedOpPrintBulkIndexRoute
}

const AuthenticatedOpPrintRouteRouteChildren: AuthenticatedOpPrintRouteRouteChildren =
  {
    AuthenticatedOpPrintInvoiceIdRoute: AuthenticatedOpPrintInvoiceIdRoute,
    AuthenticatedOpPrintStickerIdRoute: AuthenticatedOpPrintStickerIdRoute,
    AuthenticatedOpPrintBulkIndexRoute: AuthenticatedOpPrintBulkIndexRoute,
  }

const AuthenticatedOpPrintRouteRouteWithChildren =
  AuthenticatedOpPrintRouteRoute._addFileChildren(
    AuthenticatedOpPrintRouteRouteChildren,
  )

interface AuthenticatedOpSettingsRouteRouteChildren {
  AuthenticatedOpSettingsPersonalIndexRoute: typeof AuthenticatedOpSettingsPersonalIndexRoute
}

const AuthenticatedOpSettingsRouteRouteChildren: AuthenticatedOpSettingsRouteRouteChildren =
  {
    AuthenticatedOpSettingsPersonalIndexRoute:
      AuthenticatedOpSettingsPersonalIndexRoute,
  }

const AuthenticatedOpSettingsRouteRouteWithChildren =
  AuthenticatedOpSettingsRouteRoute._addFileChildren(
    AuthenticatedOpSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedMonSettingsRouteRoute: typeof AuthenticatedMonSettingsRouteRouteWithChildren
  AuthenticatedOpPrintRouteRoute: typeof AuthenticatedOpPrintRouteRouteWithChildren
  AuthenticatedOpSettingsRouteRoute: typeof AuthenticatedOpSettingsRouteRouteWithChildren
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedMonBlockingSettingsRoute: typeof AuthenticatedMonBlockingSettingsRoute
  AuthenticatedMonOverviewRoute: typeof AuthenticatedMonOverviewRoute
  AuthenticatedOpOverviewRoute: typeof AuthenticatedOpOverviewRoute
  AuthenticatedMonIndexRoute: typeof AuthenticatedMonIndexRoute
  AuthenticatedOpIndexRoute: typeof AuthenticatedOpIndexRoute
  AuthenticatedMonUsersIdRoute: typeof AuthenticatedMonUsersIdRoute
  AuthenticatedOpCustomersIdRoute: typeof AuthenticatedOpCustomersIdRoute
  AuthenticatedOpInventoryOverviewRoute: typeof AuthenticatedOpInventoryOverviewRoute
  AuthenticatedOpInventoryValuationRoute: typeof AuthenticatedOpInventoryValuationRoute
  AuthenticatedOpOrdersIdRoute: typeof AuthenticatedOpOrdersIdRoute
  AuthenticatedOpOrdersCreateRoute: typeof AuthenticatedOpOrdersCreateRoute
  AuthenticatedMonActivityLogsIndexRoute: typeof AuthenticatedMonActivityLogsIndexRoute
  AuthenticatedMonAnalyticsIndexRoute: typeof AuthenticatedMonAnalyticsIndexRoute
  AuthenticatedMonHelpCenterIndexRoute: typeof AuthenticatedMonHelpCenterIndexRoute
  AuthenticatedMonPagesIndexRoute: typeof AuthenticatedMonPagesIndexRoute
  AuthenticatedMonUsersIndexRoute: typeof AuthenticatedMonUsersIndexRoute
  AuthenticatedOpAppsIndexRoute: typeof AuthenticatedOpAppsIndexRoute
  AuthenticatedOpAttributesIndexRoute: typeof AuthenticatedOpAttributesIndexRoute
  AuthenticatedOpBlockedIndexRoute: typeof AuthenticatedOpBlockedIndexRoute
  AuthenticatedOpBrandsIndexRoute: typeof AuthenticatedOpBrandsIndexRoute
  AuthenticatedOpCampaignsIndexRoute: typeof AuthenticatedOpCampaignsIndexRoute
  AuthenticatedOpCategoriesIndexRoute: typeof AuthenticatedOpCategoriesIndexRoute
  AuthenticatedOpChatsIndexRoute: typeof AuthenticatedOpChatsIndexRoute
  AuthenticatedOpCombosIndexRoute: typeof AuthenticatedOpCombosIndexRoute
  AuthenticatedOpCouponsIndexRoute: typeof AuthenticatedOpCouponsIndexRoute
  AuthenticatedOpCustomersIndexRoute: typeof AuthenticatedOpCustomersIndexRoute
  AuthenticatedOpExpensesIndexRoute: typeof AuthenticatedOpExpensesIndexRoute
  AuthenticatedOpHelpCenterIndexRoute: typeof AuthenticatedOpHelpCenterIndexRoute
  AuthenticatedOpImportOrdersIndexRoute: typeof AuthenticatedOpImportOrdersIndexRoute
  AuthenticatedOpImportProductsIndexRoute: typeof AuthenticatedOpImportProductsIndexRoute
  AuthenticatedOpInventoryIndexRoute: typeof AuthenticatedOpInventoryIndexRoute
  AuthenticatedOpLandingPagesIndexRoute: typeof AuthenticatedOpLandingPagesIndexRoute
  AuthenticatedOpMediaIndexRoute: typeof AuthenticatedOpMediaIndexRoute
  AuthenticatedOpNotificationsIndexRoute: typeof AuthenticatedOpNotificationsIndexRoute
  AuthenticatedOpOrdersIndexRoute: typeof AuthenticatedOpOrdersIndexRoute
  AuthenticatedOpPaymentsIndexRoute: typeof AuthenticatedOpPaymentsIndexRoute
  AuthenticatedOpProductsIndexRoute: typeof AuthenticatedOpProductsIndexRoute
  AuthenticatedOpPurchasesIndexRoute: typeof AuthenticatedOpPurchasesIndexRoute
  AuthenticatedOpRefundsIndexRoute: typeof AuthenticatedOpRefundsIndexRoute
  AuthenticatedOpReviewsIndexRoute: typeof AuthenticatedOpReviewsIndexRoute
  AuthenticatedOpShipmentsIndexRoute: typeof AuthenticatedOpShipmentsIndexRoute
  AuthenticatedOpSizeChartsIndexRoute: typeof AuthenticatedOpSizeChartsIndexRoute
  AuthenticatedOpSuppliersIndexRoute: typeof AuthenticatedOpSuppliersIndexRoute
  AuthenticatedOpTagsIndexRoute: typeof AuthenticatedOpTagsIndexRoute
  AuthenticatedOpTasksIndexRoute: typeof AuthenticatedOpTasksIndexRoute
  AuthenticatedOpTransactionsIndexRoute: typeof AuthenticatedOpTransactionsIndexRoute
  AuthenticatedOpOrdersIncompleteLeadsIndexRoute: typeof AuthenticatedOpOrdersIncompleteLeadsIndexRoute
  AuthenticatedOpOrdersIncompleteLeadsIdConvertRoute: typeof AuthenticatedOpOrdersIncompleteLeadsIdConvertRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedMonSettingsRouteRoute:
    AuthenticatedMonSettingsRouteRouteWithChildren,
  AuthenticatedOpPrintRouteRoute: AuthenticatedOpPrintRouteRouteWithChildren,
  AuthenticatedOpSettingsRouteRoute:
    AuthenticatedOpSettingsRouteRouteWithChildren,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedMonBlockingSettingsRoute: AuthenticatedMonBlockingSettingsRoute,
  AuthenticatedMonOverviewRoute: AuthenticatedMonOverviewRoute,
  AuthenticatedOpOverviewRoute: AuthenticatedOpOverviewRoute,
  AuthenticatedMonIndexRoute: AuthenticatedMonIndexRoute,
  AuthenticatedOpIndexRoute: AuthenticatedOpIndexRoute,
  AuthenticatedMonUsersIdRoute: AuthenticatedMonUsersIdRoute,
  AuthenticatedOpCustomersIdRoute: AuthenticatedOpCustomersIdRoute,
  AuthenticatedOpInventoryOverviewRoute: AuthenticatedOpInventoryOverviewRoute,
  AuthenticatedOpInventoryValuationRoute:
    AuthenticatedOpInventoryValuationRoute,
  AuthenticatedOpOrdersIdRoute: AuthenticatedOpOrdersIdRoute,
  AuthenticatedOpOrdersCreateRoute: AuthenticatedOpOrdersCreateRoute,
  AuthenticatedMonActivityLogsIndexRoute:
    AuthenticatedMonActivityLogsIndexRoute,
  AuthenticatedMonAnalyticsIndexRoute: AuthenticatedMonAnalyticsIndexRoute,
  AuthenticatedMonHelpCenterIndexRoute: AuthenticatedMonHelpCenterIndexRoute,
  AuthenticatedMonPagesIndexRoute: AuthenticatedMonPagesIndexRoute,
  AuthenticatedMonUsersIndexRoute: AuthenticatedMonUsersIndexRoute,
  AuthenticatedOpAppsIndexRoute: AuthenticatedOpAppsIndexRoute,
  AuthenticatedOpAttributesIndexRoute: AuthenticatedOpAttributesIndexRoute,
  AuthenticatedOpBlockedIndexRoute: AuthenticatedOpBlockedIndexRoute,
  AuthenticatedOpBrandsIndexRoute: AuthenticatedOpBrandsIndexRoute,
  AuthenticatedOpCampaignsIndexRoute: AuthenticatedOpCampaignsIndexRoute,
  AuthenticatedOpCategoriesIndexRoute: AuthenticatedOpCategoriesIndexRoute,
  AuthenticatedOpChatsIndexRoute: AuthenticatedOpChatsIndexRoute,
  AuthenticatedOpCombosIndexRoute: AuthenticatedOpCombosIndexRoute,
  AuthenticatedOpCouponsIndexRoute: AuthenticatedOpCouponsIndexRoute,
  AuthenticatedOpCustomersIndexRoute: AuthenticatedOpCustomersIndexRoute,
  AuthenticatedOpExpensesIndexRoute: AuthenticatedOpExpensesIndexRoute,
  AuthenticatedOpHelpCenterIndexRoute: AuthenticatedOpHelpCenterIndexRoute,
  AuthenticatedOpImportOrdersIndexRoute: AuthenticatedOpImportOrdersIndexRoute,
  AuthenticatedOpImportProductsIndexRoute:
    AuthenticatedOpImportProductsIndexRoute,
  AuthenticatedOpInventoryIndexRoute: AuthenticatedOpInventoryIndexRoute,
  AuthenticatedOpLandingPagesIndexRoute: AuthenticatedOpLandingPagesIndexRoute,
  AuthenticatedOpMediaIndexRoute: AuthenticatedOpMediaIndexRoute,
  AuthenticatedOpNotificationsIndexRoute:
    AuthenticatedOpNotificationsIndexRoute,
  AuthenticatedOpOrdersIndexRoute: AuthenticatedOpOrdersIndexRoute,
  AuthenticatedOpPaymentsIndexRoute: AuthenticatedOpPaymentsIndexRoute,
  AuthenticatedOpProductsIndexRoute: AuthenticatedOpProductsIndexRoute,
  AuthenticatedOpPurchasesIndexRoute: AuthenticatedOpPurchasesIndexRoute,
  AuthenticatedOpRefundsIndexRoute: AuthenticatedOpRefundsIndexRoute,
  AuthenticatedOpReviewsIndexRoute: AuthenticatedOpReviewsIndexRoute,
  AuthenticatedOpShipmentsIndexRoute: AuthenticatedOpShipmentsIndexRoute,
  AuthenticatedOpSizeChartsIndexRoute: AuthenticatedOpSizeChartsIndexRoute,
  AuthenticatedOpSuppliersIndexRoute: AuthenticatedOpSuppliersIndexRoute,
  AuthenticatedOpTagsIndexRoute: AuthenticatedOpTagsIndexRoute,
  AuthenticatedOpTasksIndexRoute: AuthenticatedOpTasksIndexRoute,
  AuthenticatedOpTransactionsIndexRoute: AuthenticatedOpTransactionsIndexRoute,
  AuthenticatedOpOrdersIncompleteLeadsIndexRoute:
    AuthenticatedOpOrdersIncompleteLeadsIndexRoute,
  AuthenticatedOpOrdersIncompleteLeadsIdConvertRoute:
    AuthenticatedOpOrdersIncompleteLeadsIdConvertRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
