import {
  Injectable,
  OnModuleInit,
  OnModuleDestroy,
  Logger,
} from '@nestjs/common';
import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import * as fs from 'fs';
import * as path from 'path';
import * as bcrypt from 'bcryptjs';

interface ParsedField {
  columnName: string;
  columnDef: string;
  isId: boolean;
}

interface ParsedModel {
  name: string;
  tableName: string;
  scalarFields: ParsedField[];
  relationFieldNames: string[];
  indexes: string[];
  idFields: string[]; // column names for PRIMARY KEY
  compositeId: boolean; // whether PK is composite (from @@id)
  compositeIdCols: string[]; // column names from @@id
}

const SCALAR_TYPES = new Set([
  'String',
  'Boolean',
  'Int',
  'BigInt',
  'Float',
  'Decimal',
  'DateTime',
  'Json',
  'Bytes',
]);

function isScalarType(t: string): boolean {
  return SCALAR_TYPES.has(t);
}

function buildColumnDef(
  fieldName: string,
  fieldType: string,
  rawLine: string,
): string | null {
  const isOptional = rawLine.includes('?');
  const hasDefault = rawLine.includes('@default');
  const defaultStr = extractDefault(rawLine);
  const dbType = mapPrismaType(fieldType, rawLine);

  let def = `"${fieldName}" ${dbType}`;

  if (!isOptional && fieldName !== 'id') {
    def += ' NOT NULL';
  }

  if (defaultStr) {
    def += ` DEFAULT ${defaultStr}`;
  }

  if (fieldName === 'id') {
    def += ' NOT NULL'; // id is always NOT NULL
  }

  return def;
}

function mapPrismaType(prismaType: string, rawLine: string): string {
  // Check for @db overrides first
  const dbDecimal = rawLine.match(/@db\.Decimal\((\d+),\s*(\d+)\)/);
  if (dbDecimal) return `DECIMAL(${dbDecimal[1]},${dbDecimal[2]})`;

  const dbVarChar = rawLine.match(/@db\.VarChar\((\d+)\)/);
  if (dbVarChar) return `VARCHAR(${dbVarChar[1]})`;

  if (rawLine.includes('@db.Text')) return 'TEXT';
  if (rawLine.includes('@db.BigInt')) return 'BIGINT';
  if (rawLine.includes('@db.Boolean')) return 'BOOLEAN';
  if (rawLine.includes('@db.JsonB') || rawLine.includes('@db.Json'))
    return 'JSONB';
  if (rawLine.includes('@db.Timestamp')) return 'TIMESTAMP(3)';
  if (rawLine.includes('@db.Date')) return 'DATE';
  if (rawLine.includes('@db.Time')) return 'TIME';
  if (rawLine.includes('@db.Float')) return 'REAL';
  if (rawLine.includes('@db.Double')) return 'DOUBLE PRECISION';
  if (rawLine.includes('@db.Bytes')) return 'BYTEA';
  if (rawLine.includes('@db.Oid')) return 'OID';
  if (rawLine.includes('@db.Uuid')) return 'UUID';
  if (rawLine.includes('@db.Inet')) return 'INET';
  if (rawLine.includes('@db.Citext')) return 'CITEXT';

  const typeMap: Record<string, string> = {
    String: 'TEXT',
    Boolean: 'BOOLEAN',
    Int: 'INTEGER',
    BigInt: 'BIGINT',
    Float: 'DOUBLE PRECISION',
    Decimal: 'DECIMAL(65,30)',
    DateTime: 'TIMESTAMP(3)',
    Json: 'JSONB',
    Bytes: 'BYTEA',
  };

  return typeMap[prismaType] || 'TEXT'; // fallback: enums and unknown → TEXT
}

function extractDefault(rawLine: string): string | null {
  if (!rawLine.includes('@default')) return null;

  // uuid()
  if (
    rawLine.includes('@default(uuid())') ||
    rawLine.includes('@default(uuid())')
  ) {
    return 'gen_random_uuid()';
  }

  // now()
  if (
    rawLine.includes('@default(now())') ||
    rawLine.includes('@default(now()')
  ) {
    return 'CURRENT_TIMESTAMP';
  }

  // @default(cuid())
  if (rawLine.includes('@default(cuid())')) {
    return null; // cuid is generated by Prisma, not PG
  }

  // @default(auto()) for autoincrement
  if (rawLine.includes('@default(auto())')) {
    return null;
  }

  // Try to extract the default value — support string, number, boolean, array, object
  const defaultMatch = rawLine.match(/@default\((.+?)\)/);
  if (!defaultMatch) return null;

  const val = defaultMatch[1].trim();

  // String literal: "value"
  if (val.startsWith('"') && val.endsWith('"')) {
    return `'${val.slice(1, -1)}'`;
  }

  // Number or boolean
  if (/^-?\d+(\.\d+)?$/.test(val) || val === 'true' || val === 'false') {
    return val;
  }

  // Empty array/object
  if (val === '[]') return "'[]'";
  if (val === '{}') return "'{}'";

  // Bare identifier (enum value or function name): @default(draft)
  if (/^[a-zA-Z_]\w*$/.test(val)) {
    return `'${val}'`;
  }

  // Something else — return as-is (might be a pg-specific function or expression)
  return val;
}

@Injectable()
export class PrismaService
  extends PrismaClient
  implements OnModuleInit, OnModuleDestroy
{
  private readonly logger = new Logger(PrismaService.name);
  private readonly nativePool: Pool;

  constructor() {
    const connectionString = process.env.DATABASE_URL;
    if (!connectionString) {
      throw new Error('DATABASE_URL environment variable is not set');
    }
    const pool = new Pool({ connectionString });
    const adapter = new PrismaPg(pool);

    super({
      adapter,
      log:
        process.env.NODE_ENV === 'development'
          ? [
              { level: 'query', emit: 'event' },
              { level: 'warn', emit: 'event' },
              { level: 'error', emit: 'stdout' },
            ]
          : [
              { level: 'warn', emit: 'event' },
              { level: 'error', emit: 'stdout' },
            ],
    });
    this.nativePool = pool;
  }

  private async runRaw<T = void>(sql: string): Promise<T> {
    const client = await this.nativePool.connect();
    try {
      const res = await client.query(sql);
      return res.rows as T;
    } finally {
      client.release();
    }
  }

  async onModuleInit() {
    const prisma = this as any;
    if (process.env.NODE_ENV === 'development') {
      prisma.$on('query', (e: any) => {
        if (e.duration > 1000) {
          this.logger.warn(`Slow query (${e.duration}ms): ${e.query}`);
        }
      });
    }
    prisma.$on('warn', (e: any) => {
      this.logger.warn(`Prisma warning: ${e.message || e.target}`);
    });
    await this.$connect();
    await this.dropStaleColumns();
    await this.ensureSchemaColumns();
    await this.logDatabaseColumns();
    await this.validateSchemaCompleteness();
    await this.seedAdminUser();
    await this.seedSystemSettings();
  }

  async onModuleDestroy() {
    await this.$disconnect();
  }

  private async logDatabaseColumns(): Promise<void> {
    try {
      const res = await this.$queryRawUnsafe<any[]>(`
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name = 'Product'
      `);
      const cols = res.map((r) => r.column_name).join(', ');
      this.logger.log(`[SCHEMA CHECK] Database "Product" columns: ${cols}`);
    } catch (e: any) {
      this.logger.warn(`Failed to inspect Product columns: ${e.message}`);
    }
  }

  /* ──────────────────────────────────────────────────────────────────
   *  FULLY AUTOMATIC SCHEMA HEALING
   *
   *  Reads prisma/schema.prisma at startup, auto-discovers every
   *  model, field, index, and constraint — then generates CREATE TABLE
   *  IF NOT EXISTS / ALTER TABLE ADD COLUMN IF NOT EXISTS / CREATE
   *  INDEX IF NOT EXISTS for whatever is missing from the live DB.
   *
   *  When devs add a new model to schema.prisma, the next startup
   *  creates it automatically.  No manual code changes needed here.
   * ────────────────────────────────────────────────────────────────── */

  private async autoHealSchema(): Promise<void> {
    const schemaPath = path.join(process.cwd(), 'prisma', 'schema.prisma');
    if (!fs.existsSync(schemaPath)) {
      this.logger.warn(
        `Schema file not found at ${schemaPath} — auto-heal skipped`,
      );
      return;
    }

    const content = fs.readFileSync(schemaPath, 'utf-8');
    const models = this.parsePrismaModels(content);
    if (models.length === 0) {
      this.logger.warn('No models parsed from schema — auto-heal skipped');
      return;
    }

    // Get existing tables
    let existingTables = new Set<string>();
    try {
      const rows = await this.runRaw<{ table_name: string }[]>(
        `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'`,
      );
      existingTables = new Set(rows.map((r) => r.table_name));
    } catch {
      this.logger.warn(
        'Could not query existing tables — auto-heal may be incomplete',
      );
    }

    // Get existing columns per table
    const existingCols = new Map<string, Set<string>>();
    try {
      const colRows = await this.runRaw<
        { table_name: string; column_name: string }[]
      >(
        `SELECT table_name, column_name FROM information_schema.columns WHERE table_schema = 'public'`,
      );
      for (const r of colRows) {
        if (!existingCols.has(r.table_name))
          existingCols.set(r.table_name, new Set());
        existingCols.get(r.table_name)!.add(r.column_name);
      }
    } catch {
      this.logger.warn(
        'Could not query existing columns — auto-heal may be incomplete',
      );
    }

    const createdTables: string[] = [];
    const addedColumns: string[] = [];
    const createdIndexes: string[] = [];
    let tableCount = 0;
    let colCount = 0;
    let idxCount = 0;

    for (const model of models) {
      const tbl = model.tableName;
      tableCount++;

      if (!existingTables.has(tbl)) {
        // Table missing — create it with all columns
        const createSQL = this.generateCreateTableSQL(model);
        try {
          await this.runRaw(createSQL);
          createdTables.push(tbl);
        } catch (err: any) {
          this.logger.warn(
            `Auto-heal: CREATE TABLE "${tbl}" failed: ${err.message}`,
          );
        }

        // Create indexes for new table
        for (const idx of model.indexes) {
          try {
            await this.runRaw(idx);
            createdIndexes.push(idx);
            idxCount++;
          } catch {
            /* ignore — index may already exist from CREATE TABLE */
          }
        }
      } else {
        // Table exists — check for missing columns
        const cols = existingCols.get(tbl) || new Set();
        for (const field of model.scalarFields) {
          if (cols.has(field.columnName)) continue;
          const alterSQL = `ALTER TABLE "${tbl}" ADD COLUMN IF NOT EXISTS ${field.columnDef}`;
          try {
            await this.runRaw(alterSQL);
            addedColumns.push(`${tbl}.${field.columnName}`);
            colCount++;
          } catch (err: any) {
            this.logger.warn(
              `Auto-heal: ALTER "${tbl}"."${field.columnName}" failed: ${err.message}`,
            );
          }
        }

        // Create missing indexes
        for (const idx of model.indexes) {
          try {
            await this.runRaw(idx);
            createdIndexes.push(idx);
            idxCount++;
          } catch {
            /* ignore — already exists */
          }
        }
      }
    }

    if (createdTables.length > 0) {
      this.logger.log(
        `Auto-heal: created ${createdTables.length} table(s): ${createdTables.join(', ')}`,
      );
    }
    if (addedColumns.length > 0) {
      this.logger.log(
        `Auto-heal: added ${addedColumns.length} column(s): ${addedColumns.join(', ')}`,
      );
    }
    if (createdIndexes.length > 0) {
      this.logger.log(`Auto-heal: created ${idxCount} index(es)`);
    }
    if (
      createdTables.length === 0 &&
      addedColumns.length === 0 &&
      idxCount === 0
    ) {
      this.logger.log(`Auto-heal: all ${tableCount} models up to date ✓`);
    }
  }

  private parsePrismaModels(content: string): ParsedModel[] {
    const models: ParsedModel[] = [];
    const lines = content.split('\n');
    const modelNames = new Set<string>();
    // First pass: collect all model names (for relation detection)
    const modelRegex = /^model\s+(\w+)\s*\{/;
    for (const line of lines) {
      const m = line.match(modelRegex);
      if (m) modelNames.add(m[1]);
    }

    let currentModel: ParsedModel | null = null;
    let inModel = false;

    for (const line of lines) {
      const trimmed = line.trim();

      // Skip empty lines, comments, and block-level attributes (we handle them separately)
      if (trimmed === '' || trimmed.startsWith('//')) continue;

      // Detect model start
      const modelStart = trimmed.match(/^model\s+(\w+)\s*\{$/);
      if (modelStart) {
        currentModel = {
          name: modelStart[1],
          tableName: modelStart[1],
          scalarFields: [],
          relationFieldNames: [],
          indexes: [],
          idFields: [],
          compositeId: false,
          compositeIdCols: [],
        };
        inModel = true;
        continue;
      }

      // Detect model end
      if (inModel && trimmed === '}') {
        if (currentModel) models.push(currentModel);
        currentModel = null;
        inModel = false;
        continue;
      }

      if (!inModel || !currentModel) continue;

      // @@map("name")
      const mapMatch = trimmed.match(/^@@map\("(.+?)"\)/);
      if (mapMatch) {
        currentModel.tableName = mapMatch[1];
        continue;
      }

      // @@index([...]) or @@unique([...])
      const indexMatch = trimmed.match(/^@@(?:index|unique)\((.+)\)$/);
      if (indexMatch) {
        // We'll generate the index SQL later
        continue;
      }

      // @@id([...]) — composite primary key, skip (handled by @id on fields)
      if (trimmed.startsWith('@@')) continue;

      // Must be a field definition — check if it's a relation (type capitalized and matches a model name)
      // Format: fieldName FieldType [modifiers]
      const fieldParts = trimmed.split(/\s+/);
      if (fieldParts.length < 2) continue; // not a valid field line

      const fieldName = fieldParts[0];
      const fieldType = fieldParts[1];

      const baseType = fieldType.replace(/\[\]$/, '');
      const isRelation = trimmed.includes('@relation') || (modelNames.has(baseType) && !isScalarType(baseType));

      if (isRelation) {
        currentModel.relationFieldNames.push(fieldName);
        continue;
      }

      // Check for @map("col_name") on this field
      let columnName = fieldName;
      const mapColMatch = trimmed.match(/@map\("(.+?)"\)/);
      if (mapColMatch) columnName = mapColMatch[1];

      // Build column definition
      const colDef = buildColumnDef(fieldName, fieldType, trimmed);
      if (!colDef) continue;

      // Track @id fields
      const isId = trimmed.includes('@id');
      if (isId) {
        currentModel.idFields.push(columnName);
      }

      currentModel.scalarFields.push({ columnName, columnDef: colDef, isId });

      // If field is @unique, generate a unique index
      if (trimmed.includes('@unique') && !trimmed.includes('@@unique')) {
        const idxName = `${currentModel.tableName}_${columnName}_key`;
        const idxSQL = `CREATE UNIQUE INDEX IF NOT EXISTS "${idxName}" ON "${currentModel.tableName}"("${columnName}")`;
        currentModel.indexes.push(idxSQL);
      }

      // If field has @@index or is part of @@unique, those will need to be handled separately
      // For now, @@unique and @@index from separate lines are handled by the block-level parser below
    }

    // Second pass: handle block-level @@index and @@unique directives
    // These generate separate SQL statements
    inModel = false;
    currentModel = null;
    for (let i = 0; i < lines.length; i++) {
      const trimmed = lines[i].trim();
      if (trimmed.match(/^model\s+(\w+)\s*\{$/)) {
        const nameMatch = trimmed.match(/^model\s+(\w+)\s*\{$/);
        currentModel = models.find((m) => m.name === nameMatch![1]) || null;
        inModel = true;
        continue;
      }
      if (inModel && trimmed === '}') {
        currentModel = null;
        inModel = false;
        continue;
      }
      if (!inModel || !currentModel) continue;

      // Handle @@id([a, b]) — composite primary key
      const idCompMatch = trimmed.match(/^@@id\(\[([^\]]+)\]\)/);
      if (idCompMatch) {
        currentModel.compositeId = true;
        currentModel.compositeIdCols = idCompMatch[1]
          .split(',')
          .map((c) => c.trim());
        continue;
      }

      // Handle @@unique([a, b]) — multi-column unique constraint
      const uniqueMatch = trimmed.match(/^@@unique\(\[([^\]]+)\]\)/);
      if (uniqueMatch) {
        const cols = uniqueMatch[1]
          .split(',')
          .map((c) => `"${c.trim()}"`)
          .join(', ');
        const idxName = `${currentModel.tableName}_${cols.replace(/"/g, '').replace(/, /g, '_')}_key`;
        const idxSQL = `CREATE UNIQUE INDEX IF NOT EXISTS "${idxName}" ON "${currentModel.tableName}"(${cols})`;
        // Avoid duplicates
        if (!currentModel.indexes.includes(idxSQL))
          currentModel.indexes.push(idxSQL);
        continue;
      }

      // Handle @@index([a]) or @@index([a, b])
      const indexMatch2 = trimmed.match(/^@@index\(\[([^\]]+)\]\)/);
      if (indexMatch2) {
        const cols = indexMatch2[1]
          .split(',')
          .map((c) => `"${c.trim()}"`)
          .join(', ');
        const idxName = `${currentModel.tableName}_${cols.replace(/"/g, '').replace(/, /g, '_')}_idx`;
        const idxSQL = `CREATE INDEX IF NOT EXISTS "${idxName}" ON "${currentModel.tableName}"(${cols})`;
        if (!currentModel.indexes.includes(idxSQL))
          currentModel.indexes.push(idxSQL);
        continue;
      }
    }

    return models;
  }

  private generateCreateTableSQL(model: ParsedModel): string {
    const colLines = model.scalarFields.map((f) => `  ${f.columnDef}`);
    // Build PRIMARY KEY clause
    let pkCols: string[];
    if (model.compositeId) {
      pkCols = model.compositeIdCols;
    } else if (model.idFields.length > 0) {
      pkCols = model.idFields;
    } else {
      pkCols = []; // no PK — skip
    }
    if (pkCols.length > 0) {
      const pkColStr = pkCols.map((c) => `"${c}"`).join(', ');
      colLines.push(
        `  CONSTRAINT "${model.tableName}_pkey" PRIMARY KEY (${pkColStr})`,
      );
    }
    return `CREATE TABLE IF NOT EXISTS "${model.tableName}" (\n${colLines.join(',\n')}\n)`;
  }
  /**
   * Idempotent schema-drift repair.
   *
   * Prisma Migrate can fall out of sync with the real database when:
   * - Columns were added via `prisma db push` and never captured in a migration
   * - A migration was interrupted or rolled back
   * - The database was restored from a backup predating a migration
   *
   * This method runs on every startup via raw SQL (bypassing Prisma's typed
   * client entirely) so the app ALWAYS starts in a consistent state, regardless
   * of migration history.  All statements are IF NOT EXISTS — completely safe
   * to run multiple times.
   */
  private async ensureSchemaColumns(): Promise<void> {
    // Step A: Auto-heal from schema.prisma — catches ALL models/columns/indexes dynamically
    await this.autoHealSchema();

    // Foreign key constraints — each in its own DO block
    const fkFixes: string[] = [
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Product_brandId_fkey') THEN
          ALTER TABLE "Product" ADD CONSTRAINT "Product_brandId_fkey"
            FOREIGN KEY ("brandId") REFERENCES "Brand"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Product_warehouseId_fkey') THEN
          ALTER TABLE "Product" ADD CONSTRAINT "Product_warehouseId_fkey"
            FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ProductVariant_warehouseId_fkey') THEN
          ALTER TABLE "ProductVariant" ADD CONSTRAINT "ProductVariant_warehouseId_fkey"
            FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Product_sizeChartId_fkey') THEN
          ALTER TABLE "Product" ADD CONSTRAINT "Product_sizeChartId_fkey"
            FOREIGN KEY ("sizeChartId") REFERENCES "SizeChart"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'OrderItem_costingLotId_fkey') THEN
          ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_costingLotId_fkey"
            FOREIGN KEY ("costingLotId") REFERENCES "CostingLot"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'OpeningBalance_accountId_fkey') THEN
          ALTER TABLE "OpeningBalance" ADD CONSTRAINT "OpeningBalance_accountId_fkey"
            FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'OpeningBalance_periodId_fkey') THEN
          ALTER TABLE "OpeningBalance" ADD CONSTRAINT "OpeningBalance_periodId_fkey"
            FOREIGN KEY ("periodId") REFERENCES "FinancialPeriod"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'JournalEntry_periodId_fkey') THEN
          ALTER TABLE "JournalEntry" ADD CONSTRAINT "JournalEntry_periodId_fkey"
            FOREIGN KEY ("periodId") REFERENCES "FinancialPeriod"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'JournalEntryLine_entryId_fkey') THEN
          ALTER TABLE "JournalEntryLine" ADD CONSTRAINT "JournalEntryLine_entryId_fkey"
            FOREIGN KEY ("entryId") REFERENCES "JournalEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'JournalEntryLine_accountId_fkey') THEN
          ALTER TABLE "JournalEntryLine" ADD CONSTRAINT "JournalEntryLine_accountId_fkey"
            FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'expense_categories_accountId_fkey') THEN
          ALTER TABLE "expense_categories" ADD CONSTRAINT "expense_categories_accountId_fkey"
            FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Expense_categoryId_fkey') THEN
          ALTER TABLE "Expense" ADD CONSTRAINT "Expense_categoryId_fkey"
            FOREIGN KEY ("categoryId") REFERENCES "expense_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Expense_paymentAccountId_fkey') THEN
          ALTER TABLE "Expense" ADD CONSTRAINT "Expense_paymentAccountId_fkey"
            FOREIGN KEY ("paymentAccountId") REFERENCES "Account"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Expense_journalEntryId_fkey') THEN
          ALTER TABLE "Expense" ADD CONSTRAINT "Expense_journalEntryId_fkey"
            FOREIGN KEY ("journalEntryId") REFERENCES "JournalEntry"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Purchase_supplierId_fkey') THEN
          ALTER TABLE "Purchase" ADD CONSTRAINT "Purchase_supplierId_fkey"
            FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PurchaseItem_purchaseId_fkey') THEN
          ALTER TABLE "PurchaseItem" ADD CONSTRAINT "PurchaseItem_purchaseId_fkey"
            FOREIGN KEY ("purchaseId") REFERENCES "Purchase"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'SupplierPayment_supplierId_fkey') THEN
          ALTER TABLE "SupplierPayment" ADD CONSTRAINT "SupplierPayment_supplierId_fkey"
            FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'SupplierPaymentInvoice_paymentId_fkey') THEN
          ALTER TABLE "SupplierPaymentInvoice" ADD CONSTRAINT "SupplierPaymentInvoice_paymentId_fkey"
            FOREIGN KEY ("paymentId") REFERENCES "SupplierPayment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CouponUsage_couponId_fkey') THEN
          ALTER TABLE "CouponUsage" ADD CONSTRAINT "CouponUsage_couponId_fkey"
            FOREIGN KEY ("couponId") REFERENCES "Coupon"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CouponUsage_orderId_fkey') THEN
          ALTER TABLE "CouponUsage" ADD CONSTRAINT "CouponUsage_orderId_fkey"
            FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
    ];

    for (const sql of fkFixes) {
      try {
        await this.runRaw(sql);
      } catch (err: any) {
        this.logger.warn(`Schema drift FK fix skipped: ${err.message}`);
      }
    }

    this.logger.log('Schema drift check: all required columns verified ✓');
  }

  private async dropStaleColumns(): Promise<void> {
    try {
      const schemaPath = path.join(process.cwd(), 'prisma', 'schema.prisma');
      if (!fs.existsSync(schemaPath)) return;

      const content = fs.readFileSync(schemaPath, 'utf-8');
      const models = this.parsePrismaModels(content);
      if (models.length === 0) return;

      for (const model of models) {
        if (model.relationFieldNames.length === 0) continue;

        const rows = await this.runRaw<{ column_name: string }[]>(
          `SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name = '${model.tableName}'`,
        );
        const existing = new Set(rows.map((r) => r.column_name));

        for (const relName of model.relationFieldNames) {
          if (!existing.has(relName)) continue;
          if (model.scalarFields.some((f) => f.columnName === relName)) continue;

          try {
            await this.runRaw(`ALTER TABLE "${model.tableName}" DROP COLUMN IF EXISTS "${relName}"`);
            this.logger.log(`Dropped stale relation column "${model.tableName}"."${relName}"`);
          } catch { /* ignore */ }
        }
      }
    } catch (err: any) {
      this.logger.warn(`Stale column cleanup skipped: ${err.message}`);
    }
  }

  private async validateSchemaCompleteness(): Promise<void> {
    try {
      const rows = await this.runRaw<{ table_name: string }[]>(
        `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'`,
      );
      const existing = new Set(rows.map((r) => r.table_name));

      const allModels = [
        'Account',
        'Address',
        'Attribute',
        'AttributeValue',
        'BinLocation',
        'BlockedIp',
        'BlockedPhone',
        'BlockSettings',
        'Brand',
        'Category',
        'CmsPage',
        'Combo',
        'ComboItem',
        'CostingLot',
        'Coupon',
        'CouponUsage',
        'CourierCredentials',
        'CourierDispatchLog',
        'Department',
        'Designation',
        'EmailCampaign',
        'EmailTemplate',
        'Employee',
        'Expense',
        'expense_categories',
        'FinancialPeriod',
        'GoodsReceiptNote',
        'GoodsReceiptNoteItem',
        'InventoryLog',
        'JournalEntry',
        'JournalEntryLine',
        'LandingPage',
        'LicenseActivation',
        'Media',
        'MediaAttachment',
        'NotificationLog',
        'NotificationSetting',
        'OpeningBalance',
        'Order',
        'OrderCounter',
        'OrderItem',
        'OrderStatus',
        'Payment',
        'PaymentGateway',
        'PaymentOption',
        'Payslip',
        'PayslipItem',
        'Product',
        'ProductCategory',
        'ProductPaymentOption',
        'ProductTag',
        'ProductVariant',
        'ProductVariantAttributeValue',
        'Purchase',
        'PurchaseItem',
        'Referral',
        'ReferralLead',
        'ReferralReward',
        'Refund',
        'RefreshToken',
        'Review',
        'SalaryStructure',
        'Shipment',
        'ShippingOption',
        'ShippingZoneGroup',
        'SizeChart',
        'Supplier',
        'SupplierPayment',
        'SupplierPaymentInvoice',
        'SystemSetting',
        'Tag',
        'Task',
        'UserProfile',
        'UserSettings',
        'VerificationToken',
        'Warehouse',
      ];

      const missing: string[] = [];
      for (const model of allModels) {
        if (!existing.has(model)) {
          missing.push(model);
        }
      }

      if (missing.length > 0) {
        this.logger.warn(
          `Schema validation: ${missing.length} table(s) MISSING — ${missing.join(', ')}`,
        );
        this.logger.warn(
          'Run `npx prisma migrate deploy` to apply all pending migrations.',
        );
      } else {
        this.logger.log(
          `Schema validation: all ${allModels.length} tables present ✓`,
        );
      }
    } catch (err: any) {
      this.logger.warn(`Schema validation skipped: ${err.message}`);
    }
  }

  private async seedAdminUser(): Promise<void> {
    try {
      const email = process.env.ADMIN_EMAIL || process.env.ADMIN_USER || 'admin@ecomate.com';
      const plainPassword = process.env.ADMIN_PASSWORD || process.env.ADMIN_PASS || 'Admin@123';
      const adminPassword = await bcrypt.hash(plainPassword, 12);

      await this.userProfile.upsert({
        where: { email },
        update: {
          password: adminPassword,
        },
        create: {
          firstName: 'Super',
          lastName: 'Admin',
          username: 'superadmin',
          email,
          phoneNumber: '+8801700000000',
          password: adminPassword,
          role: 'superadmin',
          status: 'active',
        },
      });
      this.logger.log(`[License/Seed] Admin user synced/seeded: ${email}`);
    } catch (err: any) {
      this.logger.warn(`Failed to auto-seed admin user: ${err.message}`);
    }
  }

  private async seedSystemSettings(): Promise<void> {
    try {
      await this.systemSetting.upsert({
        where: { key: 'accounting_enabled' },
        update: {},
        create: { key: 'accounting_enabled', value: 'true' },
      });
    } catch (err: any) {
      this.logger.warn(
        `Failed to seed accounting_enabled setting: ${err.message}`,
      );
    }
  }
}
