import { Injectable, OnModuleInit, OnModuleDestroy, Logger } from '@nestjs/common';
import { PrismaClient } from '@prisma/client';
import { Pool } from 'pg';
import { PrismaPg } from '@prisma/adapter-pg';
import * as fs from 'fs';
import * as path from 'path';

interface ParsedField {
  columnName: string;
  columnDef: string;
  isId: boolean;
}

interface ParsedModel {
  name: string;
  tableName: string;
  scalarFields: ParsedField[];
  indexes: string[];
  idFields: string[];       // column names for PRIMARY KEY
  compositeId: boolean;     // whether PK is composite (from @@id)
  compositeIdCols: string[];// column names from @@id
}

const SCALAR_TYPES = new Set([
  'String', 'Boolean', 'Int', 'BigInt', 'Float', 'Decimal', 'DateTime', 'Json', 'Bytes',
]);

function isScalarType(t: string): boolean {
  return SCALAR_TYPES.has(t);
}

function buildColumnDef(fieldName: string, fieldType: string, rawLine: string): string | null {
  const isOptional = rawLine.includes('?');
  const hasDefault = rawLine.includes('@default');
  const defaultStr = extractDefault(rawLine);
  const dbType = mapPrismaType(fieldType, rawLine);

  let def = `"${fieldName}" ${dbType}`;

  if (!isOptional && fieldName !== 'id') {
    def += ' NOT NULL';
  }

  if (defaultStr) {
    def += ` DEFAULT ${defaultStr}`;
  }

  if (fieldName === 'id') {
    def += ' NOT NULL'; // id is always NOT NULL
  }

  return def;
}

function mapPrismaType(prismaType: string, rawLine: string): string {
  // Check for @db overrides first
  const dbDecimal = rawLine.match(/@db\.Decimal\((\d+),\s*(\d+)\)/);
  if (dbDecimal) return `DECIMAL(${dbDecimal[1]},${dbDecimal[2]})`;

  const dbVarChar = rawLine.match(/@db\.VarChar\((\d+)\)/);
  if (dbVarChar) return `VARCHAR(${dbVarChar[1]})`;

  if (rawLine.includes('@db.Text')) return 'TEXT';
  if (rawLine.includes('@db.BigInt')) return 'BIGINT';
  if (rawLine.includes('@db.Boolean')) return 'BOOLEAN';
  if (rawLine.includes('@db.JsonB') || rawLine.includes('@db.Json')) return 'JSONB';
  if (rawLine.includes('@db.Timestamp')) return 'TIMESTAMP(3)';
  if (rawLine.includes('@db.Date')) return 'DATE';
  if (rawLine.includes('@db.Time')) return 'TIME';
  if (rawLine.includes('@db.Float')) return 'REAL';
  if (rawLine.includes('@db.Double')) return 'DOUBLE PRECISION';
  if (rawLine.includes('@db.Bytes')) return 'BYTEA';
  if (rawLine.includes('@db.Oid')) return 'OID';
  if (rawLine.includes('@db.Uuid')) return 'UUID';
  if (rawLine.includes('@db.Inet')) return 'INET';
  if (rawLine.includes('@db.Citext')) return 'CITEXT';

  const typeMap: Record<string, string> = {
    'String': 'TEXT',
    'Boolean': 'BOOLEAN',
    'Int': 'INTEGER',
    'BigInt': 'BIGINT',
    'Float': 'DOUBLE PRECISION',
    'Decimal': 'DECIMAL(65,30)',
    'DateTime': 'TIMESTAMP(3)',
    'Json': 'JSONB',
    'Bytes': 'BYTEA',
  };

  return typeMap[prismaType] || 'TEXT'; // fallback: enums and unknown → TEXT
}

function extractDefault(rawLine: string): string | null {
  if (!rawLine.includes('@default')) return null;

  // uuid()
  if (rawLine.includes('@default(uuid())') || rawLine.includes("@default(uuid())")) {
    return 'gen_random_uuid()';
  }

  // now()
  if (rawLine.includes('@default(now())') || rawLine.includes('@default(now()')) {
    return 'CURRENT_TIMESTAMP';
  }

  // @default(cuid())
  if (rawLine.includes('@default(cuid())')) {
    return null; // cuid is generated by Prisma, not PG
  }

  // @default(auto()) for autoincrement
  if (rawLine.includes('@default(auto())')) {
    return null;
  }

  // Try to extract the default value — support string, number, boolean, array, object
  const defaultMatch = rawLine.match(/@default\((.+?)\)/);
  if (!defaultMatch) return null;

  let val = defaultMatch[1].trim();

  // String literal: "value"
  if (val.startsWith('"') && val.endsWith('"')) {
    return `'${val.slice(1, -1)}'`;
  }

  // Number or boolean
  if (/^-?\d+(\.\d+)?$/.test(val) || val === 'true' || val === 'false') {
    return val;
  }

  // Empty array/object
  if (val === '[]') return "'[]'";
  if (val === '{}') return "'{}'";

  // Bare identifier (enum value or function name): @default(draft)
  if (/^[a-zA-Z_]\w*$/.test(val)) {
    return `'${val}'`;
  }

  // Something else — return as-is (might be a pg-specific function or expression)
  return val;
}

@Injectable()
export class PrismaService
  extends PrismaClient
  implements OnModuleInit, OnModuleDestroy
{
  private readonly logger = new Logger(PrismaService.name);
  private readonly nativePool: Pool;

  constructor() {
    const connectionString = process.env.DATABASE_URL;
    const pool = new Pool({ connectionString });
    const adapter = new PrismaPg(pool);

    super({
      adapter,
      log: process.env.NODE_ENV === 'development'
        ? [{ level: 'query', emit: 'event' }, { level: 'warn', emit: 'event' }, { level: 'error', emit: 'stdout' }]
        : [{ level: 'warn', emit: 'event' }, { level: 'error', emit: 'stdout' }],
    });
    this.nativePool = pool;
  }

  private async runRaw<T = void>(sql: string): Promise<T> {
    const client = await this.nativePool.connect();
    try {
      const res = await client.query(sql);
      return res.rows as T;
    } finally {
      client.release();
    }
  }

  async onModuleInit() {
    const client = this as any;
    if (process.env.NODE_ENV === 'development') {
      client.$on('query', (e: any) => {
        if (e.duration > 1000) {
          this.logger.warn(`Slow query (${e.duration}ms): ${e.query}`);
        }
      });
    }
    client.$on('warn', (e: any) => {
      this.logger.warn(`Prisma warning: ${e.message || e.target}`);
    });
    await this.$connect();
    await this.ensureSchemaColumns();
    await this.logDatabaseColumns();
    await this.validateSchemaCompleteness();
    await this.seedAdminUser();
    await this.seedSystemSettings();
  }

  async onModuleDestroy() {
    await this.$disconnect();
  }

  private async logDatabaseColumns(): Promise<void> {
    try {
      const res = await this.$queryRawUnsafe<any[]>(`
        SELECT column_name 
        FROM information_schema.columns 
        WHERE table_name = 'Product'
      `);
      const cols = res.map(r => r.column_name).join(', ');
      this.logger.log(`[SCHEMA CHECK] Database "Product" columns: ${cols}`);
    } catch (e: any) {
      this.logger.warn(`Failed to inspect Product columns: ${e.message}`);
    }
  }

  /* ──────────────────────────────────────────────────────────────────
   *  FULLY AUTOMATIC SCALA HEALING
   *
   *  Reads prisma/schema.prisma at startup, auto-discovers every
   *  model, field, index, and constraint — then generates CREATE TABLE
   *  IF NOT EXISTS / ALTER TABLE ADD COLUMN IF NOT EXISTS / CREATE
   *  INDEX IF NOT EXISTS for whatever is missing from the live DB.
   *
   *  When devs add a new model to schema.prisma, the next startup
   *  creates it automatically.  No manual code changes needed here.
   * ────────────────────────────────────────────────────────────────── */

  private async autoHealSchema(): Promise<void> {
    const schemaPath = path.join(process.cwd(), 'prisma', 'schema.prisma');
    if (!fs.existsSync(schemaPath)) {
      this.logger.warn(`Schema file not found at ${schemaPath} — auto-heal skipped`);
      return;
    }

    const content = fs.readFileSync(schemaPath, 'utf-8');
    const models = this.parsePrismaModels(content);
    if (models.length === 0) {
      this.logger.warn('No models parsed from schema — auto-heal skipped');
      return;
    }

    // Get existing tables
    let existingTables = new Set<string>();
    try {
      const rows = await this.runRaw<{ table_name: string }[]>(
        `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'`
      );
      existingTables = new Set(rows.map(r => r.table_name));
    } catch {
      this.logger.warn('Could not query existing tables — auto-heal may be incomplete');
    }

    // Get existing columns per table
    let existingCols = new Map<string, Set<string>>();
    try {
      const colRows = await this.runRaw<{ table_name: string; column_name: string }[]>(
        `SELECT table_name, column_name FROM information_schema.columns WHERE table_schema = 'public'`
      );
      for (const r of colRows) {
        if (!existingCols.has(r.table_name)) existingCols.set(r.table_name, new Set());
        existingCols.get(r.table_name)!.add(r.column_name);
      }
    } catch {
      this.logger.warn('Could not query existing columns — auto-heal may be incomplete');
    }

    const createdTables: string[] = [];
    const addedColumns: string[] = [];
    const createdIndexes: string[] = [];
    let tableCount = 0;
    let colCount = 0;
    let idxCount = 0;

    for (const model of models) {
      const tbl = model.tableName;
      tableCount++;

      if (!existingTables.has(tbl)) {
        // Table missing — create it with all columns
        const createSQL = this.generateCreateTableSQL(model);
        try {
          await this.runRaw(createSQL);
          createdTables.push(tbl);
        } catch (err: any) {
          this.logger.warn(`Auto-heal: CREATE TABLE "${tbl}" failed: ${err.message}`);
        }

        // Create indexes for new table
        for (const idx of model.indexes) {
          try {
            await this.runRaw(idx);
            createdIndexes.push(idx);
            idxCount++;
          } catch { /* ignore — index may already exist from CREATE TABLE */ }
        }
      } else {
        // Table exists — check for missing columns
        const cols = existingCols.get(tbl) || new Set();
        for (const field of model.scalarFields) {
          if (cols.has(field.columnName)) continue;
          const alterSQL = `ALTER TABLE "${tbl}" ADD COLUMN IF NOT EXISTS ${field.columnDef}`;
          try {
            await this.runRaw(alterSQL);
            addedColumns.push(`${tbl}.${field.columnName}`);
            colCount++;
          } catch (err: any) {
            this.logger.warn(`Auto-heal: ALTER "${tbl}"."${field.columnName}" failed: ${err.message}`);
          }
        }

        // Create missing indexes
        for (const idx of model.indexes) {
          try {
            await this.runRaw(idx);
            createdIndexes.push(idx);
            idxCount++;
          } catch { /* ignore — already exists */ }
        }
      }
    }

    if (createdTables.length > 0) {
      this.logger.log(`Auto-heal: created ${createdTables.length} table(s): ${createdTables.join(', ')}`);
    }
    if (addedColumns.length > 0) {
      this.logger.log(`Auto-heal: added ${addedColumns.length} column(s): ${addedColumns.join(', ')}`);
    }
    if (createdIndexes.length > 0) {
      this.logger.log(`Auto-heal: created ${idxCount} index(es)`);
    }
    if (createdTables.length === 0 && addedColumns.length === 0 && idxCount === 0) {
      this.logger.log(`Auto-heal: all ${tableCount} models up to date ✓`);
    }
  }

  private parsePrismaModels(content: string): ParsedModel[] {
    const models: ParsedModel[] = [];
    const lines = content.split('\n');
    const modelNames = new Set<string>();
    // First pass: collect all model names (for relation detection)
    const modelRegex = /^model\s+(\w+)\s*\{/;
    for (const line of lines) {
      const m = line.match(modelRegex);
      if (m) modelNames.add(m[1]);
    }

    let currentModel: ParsedModel | null = null;
    let inModel = false;

    for (let line of lines) {
      const trimmed = line.trim();

      // Skip empty lines, comments, and block-level attributes (we handle them separately)
      if (trimmed === '' || trimmed.startsWith('//')) continue;

      // Detect model start
      const modelStart = trimmed.match(/^model\s+(\w+)\s*\{$/);
      if (modelStart) {
        currentModel = {
          name: modelStart[1],
          tableName: modelStart[1],
          scalarFields: [],
          indexes: [],
          idFields: [],
          compositeId: false,
          compositeIdCols: [],
        };
        inModel = true;
        continue;
      }

      // Detect model end
      if (inModel && trimmed === '}') {
        if (currentModel) models.push(currentModel);
        currentModel = null;
        inModel = false;
        continue;
      }

      if (!inModel || !currentModel) continue;

      // @@map("name")
      const mapMatch = trimmed.match(/^@@map\("(.+?)"\)/);
      if (mapMatch) {
        currentModel.tableName = mapMatch[1];
        continue;
      }

      // @@index([...]) or @@unique([...])
      const indexMatch = trimmed.match(/^@@(?:index|unique)\((.+)\)$/);
      if (indexMatch) {
        // We'll generate the index SQL later
        continue;
      }

      // @@id([...]) — composite primary key, skip (handled by @id on fields)
      if (trimmed.startsWith('@@')) continue;

      // Must be a field definition — check if it's a relation (type capitalized and matches a model name)
      // Format: fieldName FieldType [modifiers]
      const fieldParts = trimmed.split(/\s+/);
      if (fieldParts.length < 2) continue; // not a valid field line

      const fieldName = fieldParts[0];
      const fieldType = fieldParts[1];

      // Check if this is a relation by looking at the full line for @relation
      const isRelation = trimmed.includes('@relation');
      // Also: if the type is a known model name and there's no scalar-type annotation, it's a relation
      const isModelRef = modelNames.has(fieldType) && !isScalarType(fieldType);

      if (isRelation || isModelRef) continue;

      // Check for @map("col_name") on this field
      let columnName = fieldName;
      const mapColMatch = trimmed.match(/@map\("(.+?)"\)/);
      if (mapColMatch) columnName = mapColMatch[1];

      // Build column definition
      const colDef = buildColumnDef(fieldName, fieldType, trimmed);
      if (!colDef) continue;

      // Track @id fields
      const isId = trimmed.includes('@id');
      if (isId) {
        currentModel.idFields.push(columnName);
      }

      currentModel.scalarFields.push({ columnName, columnDef: colDef, isId });

      // If field is @unique, generate a unique index
      if (trimmed.includes('@unique') && !trimmed.includes('@@unique')) {
        const idxName = `${currentModel.tableName}_${columnName}_key`;
        const idxSQL = `CREATE UNIQUE INDEX IF NOT EXISTS "${idxName}" ON "${currentModel.tableName}"("${columnName}")`;
        currentModel.indexes.push(idxSQL);
      }

      // If field has @@index or is part of @@unique, those will need to be handled separately
      // For now, @@unique and @@index from separate lines are handled by the block-level parser below
    }

    // Second pass: handle block-level @@index and @@unique directives
    // These generate separate SQL statements
    inModel = false;
    currentModel = null;
    for (let i = 0; i < lines.length; i++) {
      const trimmed = lines[i].trim();
      if (trimmed.match(/^model\s+(\w+)\s*\{$/)) {
        const nameMatch = trimmed.match(/^model\s+(\w+)\s*\{$/);
        currentModel = models.find(m => m.name === nameMatch![1]) || null;
        inModel = true;
        continue;
      }
      if (inModel && trimmed === '}') {
        currentModel = null;
        inModel = false;
        continue;
      }
      if (!inModel || !currentModel) continue;

      // Handle @@id([a, b]) — composite primary key
      const idCompMatch = trimmed.match(/^@@id\(\[([^\]]+)\]\)/);
      if (idCompMatch) {
        currentModel.compositeId = true;
        currentModel.compositeIdCols = idCompMatch[1].split(',').map(c => c.trim());
        continue;
      }

      // Handle @@unique([a, b]) — multi-column unique constraint
      const uniqueMatch = trimmed.match(/^@@unique\(\[([^\]]+)\]\)/);
      if (uniqueMatch) {
        const cols = uniqueMatch[1].split(',').map(c => `"${c.trim()}"`).join(', ');
        const idxName = `${currentModel.tableName}_${cols.replace(/"/g, '').replace(/, /g, '_')}_key`;
        const idxSQL = `CREATE UNIQUE INDEX IF NOT EXISTS "${idxName}" ON "${currentModel.tableName}"(${cols})`;
        // Avoid duplicates
        if (!currentModel.indexes.includes(idxSQL)) currentModel.indexes.push(idxSQL);
        continue;
      }

      // Handle @@index([a]) or @@index([a, b])
      const indexMatch2 = trimmed.match(/^@@index\(\[([^\]]+)\]\)/);
      if (indexMatch2) {
        const cols = indexMatch2[1].split(',').map(c => `"${c.trim()}"`).join(', ');
        const idxName = `${currentModel.tableName}_${cols.replace(/"/g, '').replace(/, /g, '_')}_idx`;
        const idxSQL = `CREATE INDEX IF NOT EXISTS "${idxName}" ON "${currentModel.tableName}"(${cols})`;
        if (!currentModel.indexes.includes(idxSQL)) currentModel.indexes.push(idxSQL);
        continue;
      }
    }

    return models;
  }

  private generateCreateTableSQL(model: ParsedModel): string {
    const colLines = model.scalarFields.map(f => `  ${f.columnDef}`);
    // Build PRIMARY KEY clause
    let pkCols: string[];
    if (model.compositeId) {
      pkCols = model.compositeIdCols;
    } else if (model.idFields.length > 0) {
      pkCols = model.idFields;
    } else {
      pkCols = []; // no PK — skip
    }
    if (pkCols.length > 0) {
      const pkColStr = pkCols.map(c => `"${c}"`).join(', ');
      colLines.push(`  CONSTRAINT "${model.tableName}_pkey" PRIMARY KEY (${pkColStr})`);
    }
    return `CREATE TABLE IF NOT EXISTS "${model.tableName}" (\n${colLines.join(',\n')}\n)`;
  }
  /**
   * Idempotent schema-drift repair.
   *
   * Prisma Migrate can fall out of sync with the real database when:
   * - Columns were added via `prisma db push` and never captured in a migration
   * - A migration was interrupted or rolled back
   * - The database was restored from a backup predating a migration
   *
   * This method runs on every startup via raw SQL (bypassing Prisma's typed
   * client entirely) so the app ALWAYS starts in a consistent state, regardless
   * of migration history.  All statements are IF NOT EXISTS — completely safe
   * to run multiple times.
   */
  private async ensureSchemaColumns(): Promise<void> {
    // Step A: Auto-heal from schema.prisma — catches ALL models/columns/indexes dynamically
    await this.autoHealSchema();

    // Step 0: Create tables that may not exist yet (idempotent via IF NOT EXISTS).
    // Must run BEFORE the column/FK fixes below because those reference these tables.
    const tableFixes: string[] = [
      `CREATE TABLE IF NOT EXISTS "Warehouse" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "slug" TEXT NOT NULL,
        "address" TEXT,
        "city" TEXT,
        "country" TEXT NOT NULL DEFAULT 'Bangladesh',
        "phone" TEXT,
        "email" TEXT,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Warehouse_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Warehouse_slug_key" ON "Warehouse"("slug")`,
      `CREATE INDEX IF NOT EXISTS "Warehouse_isActive_idx" ON "Warehouse"("isActive")`,
      `CREATE TABLE IF NOT EXISTS "BinLocation" (
        "id" TEXT NOT NULL,
        "warehouseId" TEXT NOT NULL,
        "code" TEXT NOT NULL,
        "zone" TEXT,
        "rack" TEXT,
        "shelf" TEXT,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "BinLocation_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "BinLocation_warehouseId_idx" ON "BinLocation"("warehouseId")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "BinLocation_warehouseId_code_key" ON "BinLocation"("warehouseId", "code")`,

      `CREATE TABLE IF NOT EXISTS "Supplier" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "slug" TEXT NOT NULL,
        "contactPerson" TEXT,
        "email" TEXT,
        "phone" TEXT,
        "address" TEXT,
        "city" TEXT,
        "country" TEXT NOT NULL DEFAULT 'Bangladesh',
        "taxId" TEXT,
        "paymentTerms" TEXT,
        "notes" TEXT,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "totalPurchases" DECIMAL(14,2) NOT NULL DEFAULT 0,
        "totalPaid" DECIMAL(14,2) NOT NULL DEFAULT 0,
        "balance" DECIMAL(14,2) NOT NULL DEFAULT 0,
        CONSTRAINT "Supplier_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Supplier_slug_key" ON "Supplier"("slug")`,
      `CREATE INDEX IF NOT EXISTS "Supplier_isActive_idx" ON "Supplier"("isActive")`,

      `CREATE TABLE IF NOT EXISTS "CouponUsage" (
        "id" TEXT NOT NULL,
        "couponId" TEXT NOT NULL,
        "orderId" TEXT NOT NULL,
        "userId" TEXT,
        "discount" DECIMAL(10,2) NOT NULL,
        "usedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "CouponUsage_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "CouponUsage_couponId_idx" ON "CouponUsage"("couponId")`,
      `CREATE INDEX IF NOT EXISTS "CouponUsage_orderId_idx" ON "CouponUsage"("orderId")`,
      `CREATE INDEX IF NOT EXISTS "CouponUsage_userId_idx" ON "CouponUsage"("userId")`,

      `CREATE TABLE IF NOT EXISTS "CostingLot" (
        "id" TEXT NOT NULL,
        "purchaseId" TEXT,
        "grnId" TEXT,
        "productId" TEXT NOT NULL,
        "variantId" TEXT,
        "lotNumber" TEXT NOT NULL,
        "unitCost" DECIMAL(12,2) NOT NULL,
        "totalCost" DECIMAL(14,2) NOT NULL,
        "quantity" INTEGER NOT NULL,
        "remainingQty" INTEGER NOT NULL,
        "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "CostingLot_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "CostingLot_lotNumber_key" ON "CostingLot"("lotNumber")`,

      `CREATE TABLE IF NOT EXISTS "GoodsReceiptNote" (
        "id" TEXT NOT NULL,
        "grnNumber" TEXT NOT NULL,
        "purchaseId" TEXT NOT NULL,
        "receivedBy" TEXT,
        "status" TEXT NOT NULL DEFAULT 'draft',
        "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "notes" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "GoodsReceiptNote_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "GoodsReceiptNote_grnNumber_key" ON "GoodsReceiptNote"("grnNumber")`,

      `CREATE TABLE IF NOT EXISTS "GoodsReceiptNoteItem" (
        "id" TEXT NOT NULL,
        "grnId" TEXT NOT NULL,
        "purchaseItemId" TEXT,
        "productId" TEXT NOT NULL,
        "variantId" TEXT,
        "expectedQty" INTEGER NOT NULL,
        "receivedQty" INTEGER NOT NULL,
        "acceptedQty" INTEGER NOT NULL,
        "rejectedQty" INTEGER NOT NULL DEFAULT 0,
        "unitCost" DECIMAL(12,2) NOT NULL,
        "totalCost" DECIMAL(14,2) NOT NULL,
        CONSTRAINT "GoodsReceiptNoteItem_pkey" PRIMARY KEY ("id")
      )`,

      `CREATE TABLE IF NOT EXISTS "SupplierPayment" (
        "id" TEXT NOT NULL,
        "supplierId" TEXT NOT NULL,
        "amount" DECIMAL(14,2) NOT NULL,
        "paidAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "paymentMethod" TEXT,
        "reference" TEXT,
        "notes" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "SupplierPayment_pkey" PRIMARY KEY ("id")
      )`,

      `CREATE TABLE IF NOT EXISTS "SupplierPaymentInvoice" (
        "id" TEXT NOT NULL,
        "paymentId" TEXT NOT NULL,
        "invoiceNo" TEXT NOT NULL,
        CONSTRAINT "SupplierPaymentInvoice_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "SupplierPaymentInvoice_invoiceNo_key" ON "SupplierPaymentInvoice"("invoiceNo")`,

      `CREATE TABLE IF NOT EXISTS "Purchase" (
        "id" TEXT NOT NULL,
        "supplierId" TEXT NOT NULL,
        "referenceNo" TEXT NOT NULL,
        "orderDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "expectedDate" TIMESTAMP(3),
        "status" TEXT NOT NULL DEFAULT 'draft',
        "subtotal" DECIMAL(12,2) NOT NULL,
        "taxAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
        "discount" DECIMAL(12,2) NOT NULL DEFAULT 0,
        "total" DECIMAL(12,2) NOT NULL,
        "paidAmount" DECIMAL(12,2) NOT NULL DEFAULT 0,
        "notes" TEXT,
        "createdBy" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Purchase_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Purchase_referenceNo_key" ON "Purchase"("referenceNo")`,
      `CREATE INDEX IF NOT EXISTS "Purchase_supplierId_idx" ON "Purchase"("supplierId")`,
      `CREATE INDEX IF NOT EXISTS "Purchase_status_idx" ON "Purchase"("status")`,
      `CREATE INDEX IF NOT EXISTS "Purchase_createdAt_idx" ON "Purchase"("createdAt")`,

      `CREATE TABLE IF NOT EXISTS "PurchaseItem" (
        "id" TEXT NOT NULL,
        "purchaseId" TEXT NOT NULL,
        "productId" TEXT,
        "variantId" TEXT,
        "description" TEXT,
        "quantity" INTEGER NOT NULL,
        "unitPrice" DECIMAL(10,2) NOT NULL,
        "totalPrice" DECIMAL(12,2) NOT NULL,
        "totalBill" DECIMAL(14,2) NOT NULL,
        "receivedQty" INTEGER NOT NULL DEFAULT 0,
        CONSTRAINT "PurchaseItem_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "PurchaseItem_purchaseId_idx" ON "PurchaseItem"("purchaseId")`,
      `CREATE INDEX IF NOT EXISTS "PurchaseItem_productId_idx" ON "PurchaseItem"("productId")`,

      `CREATE TABLE IF NOT EXISTS "Expense" (
        "id" TEXT NOT NULL,
        "description" TEXT NOT NULL,
        "categoryId" TEXT NOT NULL,
        "amount" DECIMAL(10,2) NOT NULL,
        "taxAmount" DECIMAL(10,2) NOT NULL DEFAULT 0,
        "expenseDate" TIMESTAMP(3) NOT NULL,
        "paymentMethod" TEXT,
        "paymentAccountId" TEXT,
        "journalEntryId" TEXT,
        "referenceNo" TEXT,
        "notes" TEXT,
        "receiptUrl" TEXT,
        "createdBy" TEXT,
        "updatedBy" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Expense_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Expense_journalEntryId_key" ON "Expense"("journalEntryId")`,
      `CREATE INDEX IF NOT EXISTS "Expense_categoryId_idx" ON "Expense"("categoryId")`,
      `CREATE INDEX IF NOT EXISTS "Expense_paymentAccountId_idx" ON "Expense"("paymentAccountId")`,

      `CREATE TABLE IF NOT EXISTS "Account" (
        "id" TEXT NOT NULL,
        "code" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "type" TEXT NOT NULL,
        "parentId" TEXT,
        "description" TEXT,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "isGroup" BOOLEAN NOT NULL DEFAULT false,
        "createdBy" TEXT,
        "updatedBy" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Account_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Account_code_key" ON "Account"("code")`,
      `CREATE INDEX IF NOT EXISTS "Account_type_idx" ON "Account"("type")`,
      `CREATE INDEX IF NOT EXISTS "Account_parentId_idx" ON "Account"("parentId")`,

      `CREATE TABLE IF NOT EXISTS "FinancialPeriod" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "startDate" TIMESTAMP(3) NOT NULL,
        "endDate" TIMESTAMP(3) NOT NULL,
        "isClosed" BOOLEAN NOT NULL DEFAULT false,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "FinancialPeriod_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "FinancialPeriod_startDate_endDate_key" ON "FinancialPeriod"("startDate", "endDate")`,

      `CREATE TABLE IF NOT EXISTS "OpeningBalance" (
        "id" TEXT NOT NULL,
        "accountId" TEXT NOT NULL,
        "periodId" TEXT NOT NULL,
        "debit" DECIMAL(14,2) NOT NULL DEFAULT 0,
        "credit" DECIMAL(14,2) NOT NULL DEFAULT 0,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "OpeningBalance_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "OpeningBalance_accountId_periodId_key" ON "OpeningBalance"("accountId", "periodId")`,
      `CREATE INDEX IF NOT EXISTS "OpeningBalance_periodId_idx" ON "OpeningBalance"("periodId")`,

      `CREATE TABLE IF NOT EXISTS "JournalEntry" (
        "id" TEXT NOT NULL,
        "entryNo" TEXT NOT NULL,
        "periodId" TEXT NOT NULL,
        "entryDate" TIMESTAMP(3) NOT NULL,
        "description" TEXT NOT NULL,
        "totalDebit" DECIMAL(14,2) NOT NULL,
        "totalCredit" DECIMAL(14,2) NOT NULL,
        "isOpening" BOOLEAN NOT NULL DEFAULT false,
        "referenceNo" TEXT,
        "createdBy" TEXT,
        "updatedBy" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "JournalEntry_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "JournalEntry_entryNo_key" ON "JournalEntry"("entryNo")`,
      `CREATE INDEX IF NOT EXISTS "JournalEntry_periodId_idx" ON "JournalEntry"("periodId")`,
      `CREATE INDEX IF NOT EXISTS "JournalEntry_entryDate_idx" ON "JournalEntry"("entryDate")`,

      `CREATE TABLE IF NOT EXISTS "JournalEntryLine" (
        "id" TEXT NOT NULL,
        "entryId" TEXT NOT NULL,
        "accountId" TEXT NOT NULL,
        "debit" DECIMAL(14,2) NOT NULL DEFAULT 0,
        "credit" DECIMAL(14,2) NOT NULL DEFAULT 0,
        "description" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "JournalEntryLine_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "JournalEntryLine_entryId_idx" ON "JournalEntryLine"("entryId")`,
      `CREATE INDEX IF NOT EXISTS "JournalEntryLine_accountId_idx" ON "JournalEntryLine"("accountId")`,

      `CREATE TABLE IF NOT EXISTS "expense_categories" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "slug" TEXT NOT NULL,
        "description" TEXT,
        "icon" TEXT,
        "color" TEXT,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "sortOrder" INTEGER NOT NULL DEFAULT 0,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "accountId" TEXT,
        CONSTRAINT "expense_categories_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "expense_categories_slug_key" ON "expense_categories"("slug")`,
      `CREATE INDEX IF NOT EXISTS "expense_categories_accountId_idx" ON "expense_categories"("accountId")`,

      `CREATE TABLE IF NOT EXISTS "Brand" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "slug" TEXT NOT NULL,
        "logo" TEXT,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Brand_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Brand_slug_key" ON "Brand"("slug")`,

      `CREATE TABLE IF NOT EXISTS "BlockedIp" (
        "id" TEXT NOT NULL,
        "ip" TEXT NOT NULL,
        "blockType" TEXT NOT NULL DEFAULT 'order',
        "reason" TEXT,
        "blockedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "blockedBy" TEXT,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "whitelisted" BOOLEAN NOT NULL DEFAULT false,
        "autoBlocked" BOOLEAN NOT NULL DEFAULT false,
        "expiresAt" TIMESTAMP(3),
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "BlockedIp_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "BlockedIp_ip_key" ON "BlockedIp"("ip")`,

      `CREATE TABLE IF NOT EXISTS "BlockedPhone" (
        "id" TEXT NOT NULL,
        "phone" TEXT NOT NULL,
        "reason" TEXT,
        "blockedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "blockedBy" TEXT,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "whitelisted" BOOLEAN NOT NULL DEFAULT false,
        "autoBlocked" BOOLEAN NOT NULL DEFAULT false,
        "expiresAt" TIMESTAMP(3),
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "BlockedPhone_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "BlockedPhone_phone_key" ON "BlockedPhone"("phone")`,
      `CREATE INDEX IF NOT EXISTS "BlockedPhone_phone_idx" ON "BlockedPhone"("phone")`,
      `CREATE INDEX IF NOT EXISTS "BlockedPhone_isActive_idx" ON "BlockedPhone"("isActive")`,

      `CREATE TABLE IF NOT EXISTS "BlockSettings" (
        "id" TEXT NOT NULL DEFAULT 'singleton',
        "data" JSONB NOT NULL,
        CONSTRAINT "BlockSettings_pkey" PRIMARY KEY ("id")
      )`,

      `CREATE TABLE IF NOT EXISTS "LandingPage" (
        "id" TEXT NOT NULL,
        "title" TEXT NOT NULL,
        "slug" TEXT NOT NULL,
        "pageType" TEXT NOT NULL DEFAULT 'template',
        "templateId" TEXT,
        "sections" JSONB DEFAULT '[]',
        "customHtml" TEXT,
        "customCss" TEXT,
        "productIds" JSONB DEFAULT '[]',
        "comboIds" JSONB DEFAULT '[]',
        "trackingJson" JSONB DEFAULT '{}',
        "isActive" BOOLEAN NOT NULL DEFAULT false,
        "isDraft" BOOLEAN NOT NULL DEFAULT true,
        "publishedAt" TIMESTAMP(3),
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "LandingPage_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "LandingPage_slug_key" ON "LandingPage"("slug")`,

      `CREATE TABLE IF NOT EXISTS "LicenseActivation" (
        "id" TEXT NOT NULL,
        "licenseKey" TEXT NOT NULL,
        "keymateUrl" TEXT NOT NULL,
        "domain" TEXT,
        "apiKey" TEXT,
        "licenseInfo" JSONB,
        "status" TEXT NOT NULL DEFAULT 'pending',
        "errorMessage" TEXT,
        "activatedAt" TIMESTAMP(3),
        "expiresAt" TIMESTAMP(3),
        "lastCheckIn" TIMESTAMP(3),
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "LicenseActivation_pkey" PRIMARY KEY ("id")
      )`,

      `CREATE TABLE IF NOT EXISTS "EmailTemplate" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "subject" TEXT NOT NULL,
        "body" TEXT NOT NULL,
        "variables" JSONB DEFAULT '[]',
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "EmailTemplate_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "EmailTemplate_name_key" ON "EmailTemplate"("name")`,

      `CREATE TABLE IF NOT EXISTS "EmailCampaign" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "subject" TEXT NOT NULL,
        "templateId" TEXT,
        "content" TEXT,
        "recipients" JSONB DEFAULT '[]',
        "segmentFilter" JSONB DEFAULT '{}',
        "scheduledAt" TIMESTAMP(3),
        "sentAt" TIMESTAMP(3),
        "status" TEXT NOT NULL DEFAULT 'draft',
        "totalSent" INTEGER NOT NULL DEFAULT 0,
        "totalFailed" INTEGER NOT NULL DEFAULT 0,
        "createdBy" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "EmailCampaign_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "EmailCampaign_status_idx" ON "EmailCampaign"("status")`,
      `CREATE INDEX IF NOT EXISTS "EmailCampaign_createdAt_idx" ON "EmailCampaign"("createdAt")`,

      `CREATE TABLE IF NOT EXISTS "Department" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "slug" TEXT NOT NULL,
        "description" TEXT,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Department_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Department_name_key" ON "Department"("name")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Department_slug_key" ON "Department"("slug")`,

      `CREATE TABLE IF NOT EXISTS "Designation" (
        "id" TEXT NOT NULL,
        "name" TEXT NOT NULL,
        "slug" TEXT NOT NULL,
        "level" INTEGER NOT NULL DEFAULT 0,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Designation_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Designation_name_key" ON "Designation"("name")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Designation_slug_key" ON "Designation"("slug")`,

      `CREATE TABLE IF NOT EXISTS "Employee" (
        "id" TEXT NOT NULL,
        "userId" TEXT,
        "employeeId" TEXT NOT NULL,
        "firstName" TEXT NOT NULL,
        "lastName" TEXT NOT NULL,
        "email" TEXT NOT NULL,
        "phone" TEXT,
        "departmentId" TEXT,
        "designationId" TEXT,
        "employmentType" TEXT NOT NULL DEFAULT 'full_time',
        "status" TEXT NOT NULL DEFAULT 'active',
        "joiningDate" TIMESTAMP(3) NOT NULL,
        "exitDate" TIMESTAMP(3),
        "salary" DECIMAL(10,2),
        "bankAccountNo" TEXT,
        "bankName" TEXT,
        "address" TEXT,
        "city" TEXT,
        "emergencyContact" TEXT,
        "notes" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Employee_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Employee_employeeId_key" ON "Employee"("employeeId")`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Employee_email_key" ON "Employee"("email")`,
      `CREATE INDEX IF NOT EXISTS "Employee_departmentId_idx" ON "Employee"("departmentId")`,
      `CREATE INDEX IF NOT EXISTS "Employee_designationId_idx" ON "Employee"("designationId")`,
      `CREATE INDEX IF NOT EXISTS "Employee_status_idx" ON "Employee"("status")`,

      `CREATE TABLE IF NOT EXISTS "NotificationSetting" (
        "id" TEXT NOT NULL,
        "channel" TEXT NOT NULL,
        "type" TEXT NOT NULL,
        "enabled" BOOLEAN NOT NULL DEFAULT true,
        "config" JSONB DEFAULT '{}',
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "NotificationSetting_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "NotificationSetting_channel_type_key" ON "NotificationSetting"("channel", "type")`,

      `CREATE TABLE IF NOT EXISTS "NotificationLog" (
        "id" TEXT NOT NULL,
        "channel" TEXT NOT NULL,
        "eventType" TEXT NOT NULL,
        "recipient" TEXT NOT NULL,
        "subject" TEXT,
        "content" TEXT,
        "status" TEXT NOT NULL DEFAULT 'sent',
        "error" TEXT,
        "metadata" JSONB DEFAULT '{}',
        "sentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "NotificationLog_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "NotificationLog_channel_status_idx" ON "NotificationLog"("channel", "status")`,
      `CREATE INDEX IF NOT EXISTS "NotificationLog_recipient_idx" ON "NotificationLog"("recipient")`,
      `CREATE INDEX IF NOT EXISTS "NotificationLog_sentAt_idx" ON "NotificationLog"("sentAt")`,

      `CREATE TABLE IF NOT EXISTS "Payslip" (
        "id" TEXT NOT NULL,
        "employeeId" TEXT NOT NULL,
        "periodStart" TIMESTAMP(3) NOT NULL,
        "periodEnd" TIMESTAMP(3) NOT NULL,
        "totalEarnings" DECIMAL(10,2) NOT NULL,
        "totalDeductions" DECIMAL(10,2) NOT NULL DEFAULT 0,
        "netPay" DECIMAL(10,2) NOT NULL,
        "status" TEXT NOT NULL DEFAULT 'draft',
        "generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "paidAt" TIMESTAMP(3),
        "notes" TEXT,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Payslip_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "Payslip_employeeId_idx" ON "Payslip"("employeeId")`,
      `CREATE INDEX IF NOT EXISTS "Payslip_status_idx" ON "Payslip"("status")`,
      `CREATE INDEX IF NOT EXISTS "Payslip_periodStart_periodEnd_idx" ON "Payslip"("periodStart", "periodEnd")`,

      `CREATE TABLE IF NOT EXISTS "PayslipItem" (
        "id" TEXT NOT NULL,
        "payslipId" TEXT NOT NULL,
        "type" TEXT NOT NULL,
        "label" TEXT NOT NULL,
        "amount" DECIMAL(10,2) NOT NULL,
        CONSTRAINT "PayslipItem_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "PayslipItem_payslipId_idx" ON "PayslipItem"("payslipId")`,

      `CREATE TABLE IF NOT EXISTS "Referral" (
        "id" TEXT NOT NULL,
        "code" TEXT NOT NULL,
        "referrerId" TEXT NOT NULL,
        "totalReferrals" INTEGER NOT NULL DEFAULT 0,
        "totalReward" DECIMAL(10,2) NOT NULL DEFAULT 0,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "Referral_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE UNIQUE INDEX IF NOT EXISTS "Referral_code_key" ON "Referral"("code")`,
      `CREATE INDEX IF NOT EXISTS "Referral_referrerId_idx" ON "Referral"("referrerId")`,
      `CREATE INDEX IF NOT EXISTS "Referral_code_idx" ON "Referral"("code")`,

      `CREATE TABLE IF NOT EXISTS "ReferralLead" (
        "id" TEXT NOT NULL,
        "referralId" TEXT NOT NULL,
        "phone" TEXT NOT NULL,
        "name" TEXT,
        "status" TEXT NOT NULL DEFAULT 'pending',
        "orderId" TEXT,
        "rewardAmount" DECIMAL(10,2),
        "rewardGiven" BOOLEAN NOT NULL DEFAULT false,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ReferralLead_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "ReferralLead_referralId_idx" ON "ReferralLead"("referralId")`,
      `CREATE INDEX IF NOT EXISTS "ReferralLead_phone_idx" ON "ReferralLead"("phone")`,
      `CREATE INDEX IF NOT EXISTS "ReferralLead_status_idx" ON "ReferralLead"("status")`,

      `CREATE TABLE IF NOT EXISTS "ReferralReward" (
        "id" TEXT NOT NULL,
        "referralId" TEXT NOT NULL,
        "type" TEXT NOT NULL DEFAULT 'coupon',
        "amount" DECIMAL(10,2) NOT NULL,
        "description" TEXT,
        "givenAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "ReferralReward_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "ReferralReward_referralId_idx" ON "ReferralReward"("referralId")`,

      `CREATE TABLE IF NOT EXISTS "reviews" (
        "id" TEXT NOT NULL,
        "productId" TEXT NOT NULL,
        "customerName" TEXT NOT NULL,
        "rating" INTEGER NOT NULL,
        "text" TEXT,
        "approved" BOOLEAN NOT NULL DEFAULT false,
        "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "reviews_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "reviews_productId_idx" ON "reviews"("productId")`,

      `CREATE TABLE IF NOT EXISTS "SalaryStructure" (
        "id" TEXT NOT NULL,
        "employeeId" TEXT NOT NULL,
        "basicSalary" DECIMAL(10,2) NOT NULL,
        "houseAllowance" DECIMAL(10,2) NOT NULL DEFAULT 0,
        "medicalAllowance" DECIMAL(10,2) NOT NULL DEFAULT 0,
        "transportAllowance" DECIMAL(10,2) NOT NULL DEFAULT 0,
        "otherAllowance" DECIMAL(10,2) NOT NULL DEFAULT 0,
        "taxDeduction" DECIMAL(10,2) NOT NULL DEFAULT 0,
        "insuranceDeduction" DECIMAL(10,2) NOT NULL DEFAULT 0,
        "otherDeduction" DECIMAL(10,2) NOT NULL DEFAULT 0,
        "totalEarnings" DECIMAL(10,2) NOT NULL,
        "totalDeductions" DECIMAL(10,2) NOT NULL DEFAULT 0,
        "netSalary" DECIMAL(10,2) NOT NULL,
        "effectiveFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "isActive" BOOLEAN NOT NULL DEFAULT true,
        "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "SalaryStructure_pkey" PRIMARY KEY ("id")
      )`,
      `CREATE INDEX IF NOT EXISTS "SalaryStructure_employeeId_idx" ON "SalaryStructure"("employeeId")`,

      `CREATE TABLE IF NOT EXISTS "SystemSetting" (
        "key" TEXT NOT NULL,
        "value" TEXT NOT NULL,
        "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT "SystemSetting_pkey" PRIMARY KEY ("key")
      )`,
    ];

    for (const sql of tableFixes) {
      try {
        await this.runRaw(sql);
      } catch (err: any) {
        this.logger.warn(`Schema drift table fix skipped: ${err.message}`);
      }
    }

    // Step 1: Add columns that may be missing (idempotent via IF NOT EXISTS).
    // Each ALTER TABLE runs in its own call because PostgreSQL does not
    // support multiple semicolon-separated statements in a single query().
    const columnFixes: [string, string][] = [
      // === Product Table ===
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "name" TEXT`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "slug" TEXT`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'simple'`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "description" TEXT`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "shortDesc" TEXT`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "basePrice" DECIMAL(10,2) NOT NULL DEFAULT 0`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "salePrice" DECIMAL(10,2)`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "sku" TEXT`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "stock" INTEGER NOT NULL DEFAULT 0`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "lowStockQty" INTEGER`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "categoryId" TEXT`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "tags" JSONB DEFAULT '[]'`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "images" JSONB DEFAULT '[]'`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "seoMeta" JSONB DEFAULT '{}'`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN NOT NULL DEFAULT false`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "manageStock" BOOLEAN NOT NULL DEFAULT false`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "brandId" TEXT`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "reservedStock" INTEGER NOT NULL DEFAULT 0`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "defaultBinLocationId" TEXT`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "warehouseId" TEXT`],
      ['Product',        `ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "sizeChartId" TEXT`],

      // === ProductVariant Table ===
      ['ProductVariant', `ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "productId" TEXT`],
      ['ProductVariant', `ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "sku" TEXT`],
      ['ProductVariant', `ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "price" DECIMAL(10,2)`],
      ['ProductVariant', `ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "salePrice" DECIMAL(10,2)`],
      ['ProductVariant', `ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "stock" INTEGER NOT NULL DEFAULT 0`],
      ['ProductVariant', `ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "image" TEXT`],
      ['ProductVariant', `ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true`],
      ['ProductVariant', `ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "reservedStock" INTEGER NOT NULL DEFAULT 0`],
      ['ProductVariant', `ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "binLocationId" TEXT`],
      ['ProductVariant', `ALTER TABLE "ProductVariant" ADD COLUMN IF NOT EXISTS "warehouseId" TEXT`],

      // === Combo Table ===
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "name" TEXT`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "slug" TEXT`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "description" TEXT`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "shortDesc" TEXT`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "basePrice" DECIMAL(10,2) NOT NULL DEFAULT 0`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "salePrice" DECIMAL(10,2)`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "image" TEXT`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "images" JSONB DEFAULT '[]'`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "categoryId" TEXT`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "tags" JSONB DEFAULT '[]'`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "seoMeta" JSONB DEFAULT '{}'`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN NOT NULL DEFAULT false`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "manageStock" BOOLEAN NOT NULL DEFAULT false`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "stock" INTEGER NOT NULL DEFAULT 0`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "startDate" TIMESTAMP(3)`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "endDate" TIMESTAMP(3)`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "reservedStock" INTEGER NOT NULL DEFAULT 0`],
      ['Combo',          `ALTER TABLE "Combo" ADD COLUMN IF NOT EXISTS "warehouseId" TEXT`],
      // === OrderItem Table ===
      ['OrderItem',      `ALTER TABLE "OrderItem" ADD COLUMN IF NOT EXISTS "costingLotId" TEXT`],

      // === Coupon Table ===
      ['Coupon',         `ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "type" TEXT NOT NULL DEFAULT 'flat'`],
      ['Coupon',         `ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "value" DECIMAL(10,2) NOT NULL DEFAULT 0`],
      ['Coupon',         `ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "minOrderValue" DECIMAL(10,2)`],
      ['Coupon',         `ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "maxUses" INTEGER`],
      ['Coupon',         `ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "usedCount" INTEGER NOT NULL DEFAULT 0`],
      ['Coupon',         `ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "maxUsesPerCustomer" INTEGER`],
      ['Coupon',         `ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "percentageCap" DECIMAL(5,2)`],
      ['Coupon',         `ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "startsAt" TIMESTAMP(3)`],
      ['Coupon',         `ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "expiresAt" TIMESTAMP(3)`],
      ['Coupon',         `ALTER TABLE "Coupon" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true`],

      // === User Table ===
      ['User',           `ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "failedLoginAttempts" INTEGER NOT NULL DEFAULT 0`],
      ['User',           `ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "lockoutUntil" TIMESTAMP(3)`],

      // === Expense Table ===
      ['Expense',        `ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT`],
      ['Expense',        `ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "paymentAccountId" TEXT`],
      ['Expense',        `ALTER TABLE "Expense" ADD COLUMN IF NOT EXISTS "journalEntryId" TEXT`],

      // === Account Table ===
      ['Account',        `ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "createdBy" TEXT`],
      ['Account',        `ALTER TABLE "Account" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT`],

      // === JournalEntry Table ===
      ['JournalEntry',   `ALTER TABLE "JournalEntry" ADD COLUMN IF NOT EXISTS "createdBy" TEXT`],
      ['JournalEntry',   `ALTER TABLE "JournalEntry" ADD COLUMN IF NOT EXISTS "updatedBy" TEXT`],

      // === JournalEntryLine Table ===
      ['JournalEntryLine', `ALTER TABLE "JournalEntryLine" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP`],
      ['JournalEntryLine', `ALTER TABLE "JournalEntryLine" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP`],

      // === OpeningBalance Table ===
      ['OpeningBalance', `ALTER TABLE "OpeningBalance" ADD COLUMN IF NOT EXISTS "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP`],
      ['OpeningBalance', `ALTER TABLE "OpeningBalance" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP`],

      // === expense_categories Table ===
      ['expense_categories', `ALTER TABLE "expense_categories" ADD COLUMN IF NOT EXISTS "accountId" TEXT`],

      // === GoodsReceiptNote Table ===
      ['GoodsReceiptNote', `ALTER TABLE "GoodsReceiptNote" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'draft'`],
    ];


    for (const [table, sql] of columnFixes) {
      try {
        await this.runRaw(sql);
      } catch (err: any) {
        this.logger.warn(`Schema drift fix skipped for ${table}: ${err.message}`);
      }
    }

    // Foreign key constraints — each in its own DO block
    const fkFixes: string[] = [
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Product_brandId_fkey') THEN
          ALTER TABLE "Product" ADD CONSTRAINT "Product_brandId_fkey"
            FOREIGN KEY ("brandId") REFERENCES "Brand"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Product_warehouseId_fkey') THEN
          ALTER TABLE "Product" ADD CONSTRAINT "Product_warehouseId_fkey"
            FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ProductVariant_warehouseId_fkey') THEN
          ALTER TABLE "ProductVariant" ADD CONSTRAINT "ProductVariant_warehouseId_fkey"
            FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Product_sizeChartId_fkey') THEN
          ALTER TABLE "Product" ADD CONSTRAINT "Product_sizeChartId_fkey"
            FOREIGN KEY ("sizeChartId") REFERENCES "SizeChart"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'OrderItem_costingLotId_fkey') THEN
          ALTER TABLE "OrderItem" ADD CONSTRAINT "OrderItem_costingLotId_fkey"
            FOREIGN KEY ("costingLotId") REFERENCES "CostingLot"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'OpeningBalance_accountId_fkey') THEN
          ALTER TABLE "OpeningBalance" ADD CONSTRAINT "OpeningBalance_accountId_fkey"
            FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'OpeningBalance_periodId_fkey') THEN
          ALTER TABLE "OpeningBalance" ADD CONSTRAINT "OpeningBalance_periodId_fkey"
            FOREIGN KEY ("periodId") REFERENCES "FinancialPeriod"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'JournalEntry_periodId_fkey') THEN
          ALTER TABLE "JournalEntry" ADD CONSTRAINT "JournalEntry_periodId_fkey"
            FOREIGN KEY ("periodId") REFERENCES "FinancialPeriod"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'JournalEntryLine_entryId_fkey') THEN
          ALTER TABLE "JournalEntryLine" ADD CONSTRAINT "JournalEntryLine_entryId_fkey"
            FOREIGN KEY ("entryId") REFERENCES "JournalEntry"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'JournalEntryLine_accountId_fkey') THEN
          ALTER TABLE "JournalEntryLine" ADD CONSTRAINT "JournalEntryLine_accountId_fkey"
            FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'expense_categories_accountId_fkey') THEN
          ALTER TABLE "expense_categories" ADD CONSTRAINT "expense_categories_accountId_fkey"
            FOREIGN KEY ("accountId") REFERENCES "Account"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Expense_categoryId_fkey') THEN
          ALTER TABLE "Expense" ADD CONSTRAINT "Expense_categoryId_fkey"
            FOREIGN KEY ("categoryId") REFERENCES "expense_categories"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Expense_paymentAccountId_fkey') THEN
          ALTER TABLE "Expense" ADD CONSTRAINT "Expense_paymentAccountId_fkey"
            FOREIGN KEY ("paymentAccountId") REFERENCES "Account"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Expense_journalEntryId_fkey') THEN
          ALTER TABLE "Expense" ADD CONSTRAINT "Expense_journalEntryId_fkey"
            FOREIGN KEY ("journalEntryId") REFERENCES "JournalEntry"("id") ON DELETE SET NULL ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Purchase_supplierId_fkey') THEN
          ALTER TABLE "Purchase" ADD CONSTRAINT "Purchase_supplierId_fkey"
            FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'PurchaseItem_purchaseId_fkey') THEN
          ALTER TABLE "PurchaseItem" ADD CONSTRAINT "PurchaseItem_purchaseId_fkey"
            FOREIGN KEY ("purchaseId") REFERENCES "Purchase"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'SupplierPayment_supplierId_fkey') THEN
          ALTER TABLE "SupplierPayment" ADD CONSTRAINT "SupplierPayment_supplierId_fkey"
            FOREIGN KEY ("supplierId") REFERENCES "Supplier"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'SupplierPaymentInvoice_paymentId_fkey') THEN
          ALTER TABLE "SupplierPaymentInvoice" ADD CONSTRAINT "SupplierPaymentInvoice_paymentId_fkey"
            FOREIGN KEY ("paymentId") REFERENCES "SupplierPayment"("id") ON DELETE CASCADE ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CouponUsage_couponId_fkey') THEN
          ALTER TABLE "CouponUsage" ADD CONSTRAINT "CouponUsage_couponId_fkey"
            FOREIGN KEY ("couponId") REFERENCES "Coupon"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
      `DO $$ BEGIN
        IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'CouponUsage_orderId_fkey') THEN
          ALTER TABLE "CouponUsage" ADD CONSTRAINT "CouponUsage_orderId_fkey"
            FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
        END IF;
      END $$`,
    ];

    for (const sql of fkFixes) {
      try {
        await this.runRaw(sql);
      } catch (err: any) {
        this.logger.warn(`Schema drift FK fix skipped: ${err.message}`);
      }
    }

    this.logger.log('Schema drift check: all required columns verified ✓');
  }

  private async validateSchemaCompleteness(): Promise<void> {
    try {
      const rows = await this.runRaw<{ table_name: string }[]>(
        `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public' AND table_type = 'BASE TABLE'`
      );
      const existing = new Set(rows.map(r => r.table_name));

      const allModels = [
        'Account', 'Address', 'Attribute', 'AttributeValue', 'BinLocation', 'BlockedIp',
        'BlockedPhone', 'BlockSettings', 'Brand', 'Category', 'CmsPage', 'Combo',
        'ComboItem', 'CostingLot', 'Coupon', 'CouponUsage', 'CourierCredentials',
        'CourierDispatchLog', 'Department', 'Designation', 'EmailCampaign', 'EmailTemplate',
        'Employee', 'Expense', 'expense_categories', 'FinancialPeriod', 'GoodsReceiptNote',
        'GoodsReceiptNoteItem', 'InventoryLog', 'JournalEntry', 'JournalEntryLine',
        'LandingPage', 'LicenseActivation', 'Media', 'MediaAttachment', 'NotificationLog',
        'NotificationSetting', 'OpeningBalance', 'Order', 'OrderCounter', 'OrderItem',
        'OrderStatus', 'Payment', 'PaymentGateway', 'PaymentOption', 'Payslip',
        'PayslipItem', 'Product', 'ProductCategory', 'ProductPaymentOption',
        'ProductTag', 'ProductVariant', 'ProductVariantAttributeValue', 'Purchase',
        'PurchaseItem', 'Referral', 'ReferralLead', 'ReferralReward', 'Refund',
        'RefreshToken', 'Review', 'SalaryStructure', 'Shipment', 'ShippingOption',
        'ShippingZoneGroup', 'SizeChart', 'Supplier', 'SupplierPayment',
        'SupplierPaymentInvoice', 'SystemSetting', 'Tag', 'Task', 'User', 'UserSettings',
        'VerificationToken', 'Warehouse',
      ];

      const missing: string[] = [];
      for (const model of allModels) {
        if (!existing.has(model)) {
          missing.push(model);
        }
      }

      if (missing.length > 0) {
        this.logger.warn(`Schema validation: ${missing.length} table(s) MISSING — ${missing.join(', ')}`);
        this.logger.warn('Run `npx prisma migrate deploy` to apply all pending migrations.');
      } else {
        this.logger.log(`Schema validation: all ${allModels.length} tables present ✓`);
      }
    } catch (err: any) {
      this.logger.warn(`Schema validation skipped: ${err.message}`);
    }
  }

  private async seedAdminUser(): Promise<void> {
    try {
      const email = process.env.ADMIN_EMAIL || 'admin@ecomate.com';
      const plainPassword = process.env.ADMIN_PASSWORD || 'Admin@123';
      const bcrypt = require('bcryptjs');
      const adminPassword = await bcrypt.hash(plainPassword, 12);

      await (this as any).user.upsert({
        where: { email },
        update: {
          password: adminPassword,
        },
        create: {
          firstName: 'Super',
          lastName: 'Admin',
          username: 'superadmin',
          email,
          phoneNumber: '+8801700000000',
          password: adminPassword,
          role: 'superadmin',
          status: 'active',
        },
      });
      this.logger.log(`[License/Seed] Admin user synced/seeded: ${email}`);
    } catch (err: any) {
      this.logger.warn(`Failed to auto-seed admin user: ${err.message}`);
    }
  }

  private async seedSystemSettings(): Promise<void> {
    try {
      await this.systemSetting.upsert({
        where: { key: 'accounting_enabled' },
        update: {},
        create: { key: 'accounting_enabled', value: 'true' },
      });
    } catch (err: any) {
      this.logger.warn(`Failed to seed accounting_enabled setting: ${err.message}`);
    }
  }
}
