-- CreateIndex: exactly-once Purchase ledger
-- One canonical Purchase (and one Refund) per business order. The existing
-- TrackingSnapshot.eventId UNIQUE is the first-line dedup guard; this composite
-- unique is the final safety net against duplicate logical events for the same
-- order even if a different eventId is ever generated by a legacy path. NULL
-- orderIds (non-order browser events) never conflict in Postgres.
CREATE UNIQUE INDEX "TrackingSnapshot_orderId_eventType_key" ON "TrackingSnapshot"("orderId", "eventType");
